import assert from 'node:assert/strict'
import { readFile } from 'node:fs/promises'
import test from 'node:test'

const read = (path) => readFile(new URL(`../${path}`, import.meta.url), 'utf8')

test('Bar POS summary surfaces are fail-closed when the server source is incomplete', async () => {
  const posSales = await read('manager-pwa/src/pages/PosSales.jsx')
  const barReports = await read('manager-pwa/src/pages/Reports.jsx')
  const barMoney = await read('manager-pwa/src/pages/Money.jsx')

  assert.match(posSales, /const snapshotReady = snapshot\?\.complete === true/)
  assert.match(posSales, /value=\{snapshotReady \? money\(snapshot\.net_sales\) : 'Unavailable'\}/)
  assert.match(posSales, /snapshotReady && \(snapshot\?\.by_payment \|\| \[\]\)\.map/)
  assert.match(barReports, /const complete = snapshot\?\.complete === true/)
  assert.match(barMoney, /const confirmed = snapshot\?\.complete === true/)
})

test('Bar route and IPC authorization agree on reports, devices, settings, and product scope', async () => {
  const app = await read('src/renderer/src/App.jsx')
  const main = await read('src/main/index.js')
  const profile = await read('src/shared/barModeProfile.js')
  const product = await read('src/shared/productIdentity.js')

  assert.match(app, /path="hpos\/reports" element=\{<RestaurantOnlyRoute><CapabilityRoute capability="pos\.reports">/)
  assert.match(app, /path="hpos\/team" element=\{<RestaurantOnlyRoute><CapabilityRoute capability="staff\.view">/)
  assert.match(app, /path="hpos\/system-health" element=\{<RestaurantOnlyRoute><CapabilityRoute capability="system\.health">/)
  assert.match(app, /path="hpos\/business-control" element=\{<RestaurantOnlyRoute><CapabilityRoute capability="advanced_reports\.view">/)
  assert.match(app, /path="settings"\s+element=\{<CapabilityRoute capability="settings\.view">/)
  assert.match(main, /pos:getOrders[\s\S]{0,180}requireCapability\('pos\.reports'\)/)
  assert.match(main, /pos:getVoidHistory[\s\S]{0,180}requireCapability\('pos\.reports'\)/)
  assert.match(main, /pos:getTabs[\s\S]{0,700}isPosOutletScopedRole\(user\?\.role\)/)
  assert.match(main, /pos:exportHistoryExcel[\s\S]{0,180}requireCapability\('reports\.export'\)/)
  assert.match(main, /pos:exportHistoryPdf[\s\S]{0,180}requireCapability\('reports\.export'\)/)
  assert.match(main, /settings:updateOperatingProfile[\s\S]{0,220}requireCapability\('settings\.manage_general'\)/)
  assert.match(main, /pos:saveHardwareSettings[\s\S]{0,140}requireCapability\('settings\.manage_general'\)/)
  assert.match(main, /pos:openCashDrawer[\s\S]{0,700}requireCapability\('pos\.cashup'\)/)
  assert.doesNotMatch(product, /allowedRoutePrefixes: freezeRoutes\(CORE_PREAUTH, CORE_SHARED, RESTAURANT_OPS\)/)
  assert.match(product, /CORE_SHARED_HOSPITALITY_POS = Object\.freeze\(CORE_SHARED\.filter\(\(route\) => route !== 'ai'\)\)/)
  assert.match(profile, /route: '\/hpos\/reports',[\s\S]{0,80}capability: 'pos\.reports'/)
  assert.match(profile, /route: '\/hpos\/team',[\s\S]{0,80}capability: 'staff\.view'/)
})

test('Bar export and receipt paths cannot silently invent lodging or receipt identity', async () => {
  const dataManagement = await read('src/renderer/src/components/DataManagement.jsx')
  const main = await read('src/main/index.js')
  const receipt = await read('src/renderer/src/components/shared/POSReceipt.jsx')
  const hardware = await read('src/main/hardware/posHardwareAdapter.js')
  const legacyHardware = await read('legacy-pos/src/main/hardware/posHardwareAdapter.js')
  const legacyMain = await read('legacy-pos/src/main/index.js')
  const invoices = await read('manager-pwa/src/pages/Invoices.jsx')

  assert.match(dataManagement, /isBarOnlyMode\(settings\)/)
  assert.match(main, /restaurantMode && !String\(normalized\.preset\)\.startsWith\('restaurant_'\)/)
  assert.doesNotMatch(receipt, /POS-\$\{Date\.now\(\)\}/)
  assert.match(main, /Printing is blocked until the server-issued receipt number is available/)
  assert.match(receipt, /no server-issued receipt number\. Printing is blocked/)
  assert.match(receipt, /Save is blocked until the sale is refreshed or resolved/)
  assert.match(receipt, /return null/)
  assert.doesNotMatch(receipt, /Number\(item\.quantity \|\| 0\) \* Number\(item\.unit_price \|\| 0\)/)
  assert.match(hardware, /function recordedItemAmount/)
  assert.match(legacyHardware, /function recordedItemAmount/)
  assert.doesNotMatch(hardware, /const total = normalizeMoney\(quantity \* unitPrice\)/)
  assert.doesNotMatch(legacyHardware, /const total = normalizeMoney\(quantity \* unitPrice\)/)
  assert.match(legacyMain, /Printing is blocked until the server-issued receipt number is available/)
  assert.match(invoices, /payment\.method \|\| 'tender unavailable'/)
  assert.doesNotMatch(hardware, /String\(order\.payment_method \|\| ''\)\.toLowerCase\(\) === 'cash'/)
  assert.doesNotMatch(legacyHardware, /String\(order\.payment_method \|\| ''\)\.toLowerCase\(\) === 'cash'/)
})

test('open-tab values and split previews never derive a financial total from line items', async () => {
  const openChecks = await read('src/renderer/src/components/hospitality-pos/HposOpenChecks.jsx')
  const pos = await read('src/renderer/src/components/POS.jsx')

  assert.match(openChecks, /tab\?\.total === null \|\| tab\?\.total === undefined/)
  assert.doesNotMatch(openChecks, /\(tab\.items \|\| \[\]\)\.reduce\(/)
  assert.match(openChecks, /Authoritative total unavailable; refresh before splitting/)
  assert.match(openChecks, /tabValue\(splitTab\) === null/)
  assert.match(openChecks, /financial_complete === true/)
  assert.match(pos, /const recordedLineAmount = \(item = \{\}\) =>/)
  assert.match(pos, /currentOpenTabTotal === null/)
  assert.doesNotMatch(pos, /item\.quantity \* item\.unit_price/)
  assert.doesNotMatch(pos, /currentOpenTab\.items.*reduce\(.*quantity.*unit_price/s)
})

test('Manager snapshot finality is server-certified and timezone-aware', async () => {
  const migration = await read('supabase/migrations/20260812010000_manager_bar_pos_snapshot_finality.sql')
  const api = await read('manager-pwa/src/lib/api.js')

  assert.match(migration, /settings s.*timezone/s)
  assert.match(migration, /'source_coverage_complete', v_unresolved = 0/)
  assert.match(migration, /'financial_truth', case when v_unresolved = 0 then 'server_confirmed' else 'server_incomplete' end/)
  assert.match(api, /snapshot\?\.complete === true/)
  assert.match(api, /financial_truth: serverComplete \? 'server_confirmed' : offline \? 'server_stale'/)
  assert.doesNotMatch(api, /complete:\s*true\s*,\s*financial_truth/)
})

test('Manager Bar report certification requires persisted, reconciled tenders and line amounts', async () => {
  const migration = await read('supabase/migrations/20260812020000_manager_bar_pos_report_detail_finality.sql')
  const truth = await read('src/shared/posFinancialTruth.js')

  assert.match(migration, /v_unresolved_tenders/)
  assert.match(migration, /v_unresolved_items/)
  assert.match(migration, /tender_breakdown_complete/)
  assert.match(migration, /item_detail_complete/)
  assert.match(migration, /'gross_subtotal', i\.gross_subtotal/)
  assert.doesNotMatch(migration, /jsonb_build_array\(/)
  assert.match(truth, /hasRecordedPosTenderEnvelope/)
  assert.match(truth, /if \(parsed\.length === 0\) return false/)
})

test('authoritative POS exports do not certify synthetic tender or line fallbacks', async () => {
  const migration = await read('supabase/migrations/20260812030000_pos_export_detail_finality.sql')
  const main = await read('src/main/index.js')
  const posRenderer = await read('src/renderer/src/components/POS.jsx')

  assert.match(migration, /v_tender_gap_count/)
  assert.match(migration, /v_item_gap_count/)
  assert.match(migration, /'dataset_status', v_dataset_status/)
  assert.match(migration, /case when jsonb_typeof\(coalesce\(i\.payment_breakdown/)
  assert.doesNotMatch(migration, /jsonb_build_array\(jsonb_build_object\('method',coalesce\(i\.payment_method/)
  assert.match(main, /server order line\(s\) have no recorded line amount/)
  assert.match(main, /server transaction\(s\) have no reconciled recorded tender envelope/)
  assert.match(posRenderer, /Number\.isFinite\(Number\(result\.total\)\)/)
  assert.match(posRenderer, /result\.offline === true \? \(result\.payment_breakdown \|\| normalizedPaymentBreakdown\) : \(result\.payment_breakdown \?\? null\)/)
})

test('receipts do not label an unrecorded tender as cash', async () => {
  const receipt = await read('src/renderer/src/components/shared/POSReceipt.jsx')
  assert.match(receipt, /Tender unavailable/)
  assert.doesNotMatch(receipt, /order\.payment_method \|\| 'Cash'/)
})

test('POS history views do not label missing tender evidence as cash', async () => {
  const legacyOrders = await read('legacy-pos/src/renderer/src/screens/Orders.jsx')
  const managerSales = await read('manager-pwa/src/pages/PosSales.jsx')
  assert.match(legacyOrders, /tender unavailable/)
  assert.match(managerSales, /tender unavailable/)
  assert.match(managerSales, /transaction\.financial_complete === true/)
  assert.match(managerSales, /transactionReady = financialReady && transaction\.financial_complete === true/)
})

test('generic restaurant finance and history views fail closed on uncertified POS reads', async () => {
  const pos = await read('src/renderer/src/components/POS.jsx')
  const overview = await read('src/renderer/src/components/restaurant/RestaurantFinanceOverview.jsx')
  const dailyClose = await read('src/renderer/src/components/restaurant/RestaurantDailyClose.jsx')
  const drawer = await read('src/renderer/src/components/restaurant/RestaurantCashDrawer.jsx')

  assert.match(pos, /hasRecordedPosTenderEnvelope/)
  assert.match(pos, /orderReadCompleteness\.tenderComplete/)
  assert.match(pos, /Tender unavailable/)
  assert.match(overview, /snapshotReady = data\.orders\?\._source === 'server'/)
  assert.match(overview, /tenderReady = snapshotReady && data\.orders\?\._tender_complete === true/)
  assert.match(dailyClose, /orderSnapshotReady = orders\?\._source === 'server'/)
  assert.match(drawer, /orderSnapshotReady = todayOrders\._source === 'server'/)
  assert.match(drawer, /POS expectations are unavailable until the server confirms/)
  assert.match(pos, /cashupSummary\?\.complete === false/)
})

test('Legacy cash-up and shared revenue reads label cache estimates and withhold invented tender', async () => {
  const cashupMain = await read('legacy-pos/src/main/index.js')
  const cashupUi = await read('legacy-pos/src/renderer/src/screens/CashUp.jsx')
  const pos = await read('src/main/domains/pos.js')
  const truth = await read('src/shared/posFinancialTruth.js')

  assert.match(cashupMain, /return breakdown\n    \.map\(\(row\) =>/)
  assert.match(cashupMain, /financial_truth: 'cache_estimate'/)
  assert.match(cashupUi, /const summaryReady = summary\?\.complete === true/)
  assert.match(cashupUi, /Financial expectations are unavailable until the server confirms/)
  assert.match(pos, /return \[\]/)
  assert.match(pos, /financial_truth: 'cache_estimate'/)
  assert.match(truth, /Quantity × unit price is a pricing estimate/)
  assert.match(pos, /hasRecordedPosTenderEnvelope\(order\) \? getOrderPaymentRows\(order\) : \[\]/)
  assert.match(cashupMain, /hasRecordedPosTenderEnvelope\(order\)/)
  assert.doesNotMatch(cashupMain, /const paymentRows = getOrderPaymentRows\(order\);/)
})

test('Legacy open-tab and customer-display surfaces do not reconstruct posted money', async () => {
  const tables = await read('legacy-pos/src/renderer/src/screens/Tables.jsx')
  const display = await read('legacy-pos/src/renderer/src/components/CustomerDisplay.jsx')
  const tabsMigration = await read('supabase/migrations/20260807130000_bar_tab_financial_snapshot_and_concurrency.sql')
  const posDomain = await read('src/main/domains/pos.js')
  assert.match(tables, /Amount unavailable/)
  assert.doesNotMatch(tables, /Number\(tab\.total \|\| 0\)/)
  assert.match(display, /recordedLineAmount/)
  assert.match(display, /Estimated total/)
  assert.doesNotMatch(display, /Number\(item\.quantity \|\| 0\) \* Number\(item\.unit_price \|\| 0\)/)
  assert.match(tabsMigration, /financial_complete/)
  assert.doesNotMatch(tabsMigration, /coalesce\(nullif\(value->>'quantity'/)
  assert.match(tabsMigration, /v_missing_line_amount/)
  assert.match(tabsMigration, /left join lateral/)
  assert.match(posDomain, /markCachedPosTabsUncertified/)
  assert.match(posDomain, /markCachedPosTabsUncertified\(pendingLocal\.filter/)
  assert.match(posDomain, /financial_complete: false/)
})

test('generic desktop POS reports do not render an uncertified source as financial truth', async () => {
  const reports = await read('src/renderer/src/components/Reports.jsx')
  const pos = await read('src/main/domains/pos.js')
  const main = await read('src/main/index.js')
  assert.match(reports, /const posSalesReady = posSales\?\.source === 'server'/)
  assert.match(reports, /POS money is unavailable until the server certifies a complete source/)
  assert.match(reports, /!posSalesReady \?/)
  assert.match(reports, /activeTab === 'pos' && !posSalesReady/)
  assert.match(pos, /complete: true, financial_truth: 'server_confirmed'/)
  assert.match(pos, /get_pos_financial_report_export_v2/)
  assert.match(pos, /buildCertifiedPosRevenueSummary/)
  assert.match(main, /posRevenue\?\.complete !== true \|\| posRevenue\?\.financial_truth !== 'server_confirmed'/)
})

test('desktop financial read metadata survives the Electron IPC structured clone', async () => {
  const pos = await read('src/main/domains/pos.js')
  const expenses = await read('src/main/domains/expenses.js')
  const main = await read('src/main/index.js')

  assert.match(pos, /_source: \{ value: source, enumerable: true/)
  assert.match(pos, /_complete: \{ value: complete === true, enumerable: true/)
  assert.match(expenses, /_source: \{ value: source, enumerable: true/)
  assert.match(expenses, /_complete: \{ value: complete, enumerable: true/)
  assert.match(main, /const filtered = \(rows \|\| \[\]\)\.filter\(\(order\) => order\.cashier_id === currentUser\.id\)/)
  assert.match(main, /_tender_complete: \{ value: rows\?\._tender_complete === true/)
})

test('PIN-verified Till history withholds cached totals and corrections until complete', async () => {
  const pos = await read('src/main/domains/pos.js')
  const mySales = await read('src/renderer/src/components/hospitality-pos/HposMySales.jsx')

  assert.match(pos, /complete: false/)
  assert.match(pos, /hasUnresolvedPosRows/)
  assert.match(mySales, /const financialReady = readCompleteness\.complete === true/)
  assert.match(mySales, /financialReady \? money\(order\.total, currency\) : 'Unavailable'/)
  assert.match(mySales, /financialReady && isCompleted\(selected\)/)
})

test('Bar report and business-control detail do not expose incomplete monetary aggregates', async () => {
  const reports = await read('src/renderer/src/components/hospitality-pos/HposReports.jsx')
  const control = await read('src/renderer/src/components/hospitality-pos/HposBusinessControl.jsx')
  const pwa = await read('manager-pwa/src/pages/PosSales.jsx')

  assert.match(reports, /financialReady.*money\(order\.total/s)
  assert.match(reports, /const hasRecordedMoney = \(value\)/)
  assert.match(reports, /(?:financialReady && hasRecordedMoney\(lineAmount\)|itemDetailReady && \(selectedOrder\.pos_order_items)/)
  assert.match(reports, /tenderReady \? \(posTenderRows\(order\)/)
  assert.match(reports, /hasRecordedPosTenderEnvelope/)
  assert.match(reports, /Tender allocation is unavailable until the server confirms a complete recorded payment envelope/)
  assert.match(reports, /Tender allocation is unavailable until the server confirms a complete recorded payment envelope/)
  assert.match(control, /const posFinancialReady = data\.orders\?\._complete === true/)
  assert.match(control, /calculatePosFinancialTruth\(data\.orders/)
  assert.match(control, /Sales contribution and margin are unavailable until the server confirms a complete POS source/)
  assert.match(control, /const recordedItemAmount = \(item = \{\}\)/)
  assert.doesNotMatch(control, /lineAmount == null\s*\?\s*Number\(item\.quantity/)
  assert.match(control, /itemDetailComplete/)
  assert.match(pwa, /TransactionDetail transaction=\{selected\} financialReady=\{snapshotReady\}/)
  assert.match(pwa, /hasRecordedMoney\(item\.unit_price\)/)
  assert.match(pwa, /const rowReady = \(transaction\) => snapshotReady && transaction\?\.financial_complete === true/)
  assert.match(pwa, /rowReady\(transaction\) \? money\(transaction\.total\) : 'Unavailable'/)
})

test('Business Control never treats a missing owner-digest expense as zero', async () => {
  const control = await read('src/renderer/src/components/hospitality-pos/HposBusinessControl.jsx')
  assert.match(control, /digest\.expenses_complete === true/)
  assert.match(control, /recordedExpenses === null \? 'Unavailable'/)
  assert.match(control, /Operating movement \(certified sources only\)/)
  assert.doesNotMatch(control, /Number\(digest\.total_expenses \|\| 0\)/)
})

test('Bar tab and export RPCs fail closed at the database boundary', async () => {
  const migration = await read('supabase/migrations/20260814010000_bar_pos_authorization_hardening.sql')
  assert.match(migration, /get_pos_financial_report_export_v2_unscoped/)
  assert.match(migration, /cashier', 'supervisor.*requires one assigned outlet/s)
  assert.match(migration, /app_require_pos_outlet_access\(p_lodge_id, p_outlet_id\)/)
  assert.match(migration, /get_restaurant_pos_tabs_financial_truth_unscoped/)
  assert.match(migration, /update_pos_tab_status_unscoped/)
  assert.match(migration, /before_snapshot[\s\S]*after_snapshot/)
  assert.match(migration, /revoke all on function public\.upsert_pos_tab\(jsonb\) from anon/)
})

test('Accounting exports and period close expose explicit capability gates', async () => {
  const main = await read('src/main/index.js')
  const ui = await read('src/renderer/src/components/restaurant-accounting/RestaurantAccountingUi.jsx')
  const balance = await read('src/renderer/src/components/restaurant-accounting/RestaurantBalanceSheet.jsx')
  assert.match(main, /exportStatements: \['accounting\.export'/)
  assert.match(main, /exportPayrollRegister: \['accounting\.payroll_export'/)
  assert.match(main, /preparePeriodClose: \['accounting\.close'/)
  assert.match(main, /approvePeriodClose: \['accounting\.close'/)
  assert.match(main, /reopenPeriodClose: \['accounting\.close'/)
  assert.match(ui, /const requiredCapability = exportOperation === 'exportPayrollRegister' \? 'accounting\.payroll_export' : 'accounting\.export'/)
  assert.match(balance, /canAccessCapability\(access,'accounting\.close'\)/)
  assert.match(balance, /Requires Accounting period-close permission/)
})

test('Bar exports and Legacy POS history withhold unrecorded transaction amounts', async () => {
  const main = await read('src/main/index.js')
  const legacyOrders = await read('legacy-pos/src/renderer/src/screens/Orders.jsx')

  assert.match(main, /getRecordedPosItemAmount/)
  assert.match(main, /server order line\(s\) have no recorded line amount/)
  assert.doesNotMatch(main, /item\.subtotal \|\| \(Number\(item\.quantity/)
  assert.match(legacyOrders, /function getDisplayOrderTotal/)
  assert.match(legacyOrders, /Server-confirmed total unavailable for this transaction state/)
  assert.match(legacyOrders, /return 'Needs review'/)
})

test('Manager PWA bar navigation excludes lodging night-audit and maintenance surfaces', async () => {
  const shell = await read('manager-pwa/src/lib/productShell.js')
  const app = await read('manager-pwa/src/App.jsx')
  const more = await read('manager-pwa/src/pages/More.jsx')
  const expenses = await read('manager-pwa/src/pages/Expenses.jsx')

  assert.match(shell, /if \(barOnly && path === '\/audit'\) return false/)
  assert.match(app, /ProductRouteGuard path="\/audit"/)
  assert.match(more, /can\('audit\.view'\) && !barOnly/)
  assert.match(expenses, /barOnly \? Promise\.resolve\(\[\]\) : listMaintenanceTickets/)
  assert.match(expenses, /expenseSourceComplete \? money\(expense\.amount\) : 'Unavailable'/)
})

test('Manager bar operations withhold incomplete snapshot money', async () => {
  const operations = await read('manager-pwa/src/pages/RestaurantOperations.jsx')
  assert.match(operations, /const snapshotReady = snapshot\?\.complete === true/)
  assert.match(operations, /snapshotReady \? money\(snapshot\.net_sales\) : 'Unavailable'/)
  assert.match(operations, /snapshotReady \? money\(cashTotal\) : 'Unavailable'/)
  assert.match(operations, /const openCount = snapshotReady \? Number\(snapshot\?\.open_count \|\| 0\) : null/)
  assert.match(operations, /openCount == null \? 'Unavailable' : openCount/)
  assert.match(operations, /snapshotReady \? money\(transaction\.total\) : 'Unavailable'/)
})

test('Bar stock counts refuse to derive audited adjustments from cached quantities', async () => {
  const stock = await read('src/renderer/src/components/hospitality-pos/HposStock.jsx')
  assert.match(stock, /itemsRead.*complete: false/)
  assert.match(stock, /stockAction\.mode === 'count' && !stockCountsReady/)
  assert.match(stock, /cached quantity cannot be used to calculate an audited adjustment/)
})

test('stock-cost reports and exports require explicit spend finality and recorded line totals', async () => {
  const reports = await read('src/renderer/src/components/Reports.jsx')
  const main = await read('src/main/index.js')
  const inventory = await read('src/main/domains/inventory.js')
  const supplies = await read('src/main/domains/supplies.js')
  const migration = await read('supabase/migrations/20260812040000_spend_report_finality.sql')
  const sharedFinality = await read('supabase/migrations/20260812050000_shared_report_finality.sql')

  assert.match(reports, /const costsReady = invSpend\?\.source === 'server'/)
  assert.match(reports, /invSpend\?\.purchases \|\| \[\]\)\.every\(\(row\) => recordedAmount\(row, \['total_cost'\]\) !== null\)/)
  assert.match(reports, /reportMoney\(recordedAmount\(p, \['total_cost'\]\)\)/)
  assert.doesNotMatch(reports, /Number\(p\.total_cost \|\| 0\)\.toFixed\(2\)/)
  assert.match(main, /requireCompleteReportRead\(invSpend, 'Inventory spend source'\)/)
  assert.match(main, /requireCompleteReportRead\(supSpend, 'Supply spend source'\)/)
  assert.doesNotMatch(main, /p\.quantity_purchased \* Number\(p\.unit_cost/)
  assert.match(inventory, /_complete: data\.complete === true \|\| data\._complete === true/)
  assert.match(supplies, /_complete: data\.complete === true \|\| data\._complete === true/)
  assert.match(migration, /'financial_truth', case when v_unresolved = 0 then 'server_confirmed'/)
  assert.match(migration, /count\(\*\) filter \(where total_cost is null\)/)
  assert.match(migration, /'unresolved_count', v_unresolved/)
  assert.match(sharedFinality, /get_revenue_report_before_finality/)
  assert.match(sharedFinality, /get_profit_loss_summary_before_finality/)
  assert.match(sharedFinality, /get_room_profitability_summary_before_finality/)
  assert.match(sharedFinality, /'financial_truth', case when v_unresolved = 0 then 'server_confirmed'/)
})

test('expense report exports preserve unavailable amounts instead of coercing null to zero', async () => {
  const reports = await read('src/renderer/src/components/Reports.jsx')
  const main = await read('src/main/index.js')

  assert.match(reports, /const expensesReady = expenses\?\._complete === true/)
  assert.match(reports, /reportMoney\(amount\)/)
  assert.match(main, /recordedReportAmount\(e, \['amount'\]\)/)
  assert.match(main, /recordedReportAmount\(m, \['actual_cost', 'total_cost'\]\)/)
  assert.doesNotMatch(main, /expenses\.forEach\(\(e\) => \{ byCategory\[e\.category \|\| 'Other'\].*Number\(e\.amount \|\| 0\)/s)
})

test('shared booking, occupancy, and P&L reports do not present uncertified server aggregates as final', async () => {
  const reports = await read('src/renderer/src/components/Reports.jsx')
  const domain = await read('src/main/domains/reports.js')
  const rooms = await read('src/main/domains/rooms.js')

  assert.match(domain, /_complete: data\.complete === true \|\| data\._complete === true/)
  assert.match(domain, /withReportMetadata\(rows, bookingsSource === 'server'/)
  assert.match(domain, /bookingsComplete = bookings\.every/)
  assert.match(domain, /const serverComplete = .*every/)
  assert.match(rooms, /withReadMetadata\(data \|\| \[\], 'server', true\)/)
  assert.match(reports, /const revenueReady = revenue\?\.source === 'server' && revenue\?\._complete === true/)
  assert.match(reports, /const profitLossReady = pl\?\.source === 'server' && pl\?\._complete === true/)
  assert.match(reports, /Booking revenue is unavailable until the server certifies a complete source/)
  assert.match(reports, /Profit &amp; Loss is unavailable until the server certifies a complete source/)
  assert.match(reports, /activeTab === 'bookings' && !revenueReady/)
  assert.match(reports, /activeTab === 'pl' && !profitLossReady/)
})

test('cash-up history does not turn an unavailable read into an empty history', async () => {
  const main = await read('src/main/index.js')
  const pos = await read('src/renderer/src/components/POS.jsx')
  const drawer = await read('src/renderer/src/components/restaurant/RestaurantCashDrawer.jsx')

  assert.match(main, /ipcMain\.handle\('pos:getCashups',[\s\S]{0,700}unavailablePosRead\(e, 'Cash-up history'\)/)
  assert.doesNotMatch(pos, /getCashups\(12, \{ cashier_id: currentOperator\.id \|\| null \}\)\.catch\(\(\) => \[\]\)/)
  assert.match(pos, /history\?\._available === false/)
  assert.match(drawer, /historyUnavailable/)
})

test('owner digest uses the certified POS envelope and never invents financial zeros', async () => {
  const migration = await read('supabase/migrations/20260814010000_bar_pos_authorization_hardening.sql')
  const owner = await read('src/renderer/src/components/restaurant/RestaurantOwnerDigest.jsx')
  const dailyClose = await read('src/renderer/src/components/restaurant/RestaurantDailyClose.jsx')
  const control = await read('src/renderer/src/components/hospitality-pos/HposBusinessControl.jsx')

  assert.match(migration, /create or replace function public\.generate_owner_digest\(p_lodge_id uuid\)/)
  assert.match(migration, /get_pos_financial_report_export_v2\(p_lodge_id, v_today, v_today, null\)/)
  assert.match(migration, /'financial_complete', v_complete/)
  assert.match(migration, /'total_revenue', case when v_complete then v_controls->'net_recorded_sales' else null end/)
  assert.match(migration, /revoke all on function public\.generate_owner_digest\(uuid\) from public, anon/)
  assert.doesNotMatch(migration, /sum\(o\.total\)/)
  assert.match(owner, /financial_complete === true/)
  assert.doesNotMatch(owner, /Number\(s\.total_revenue \|\| 0\)/)
  assert.doesNotMatch(owner, /Number\(s\.total_expenses \|\| 0\)/)
  assert.match(dailyClose, /result\?\.digest \|\| result\?\.summary/)
  assert.match(dailyClose, /digest\.financial_complete === true/)
  assert.match(control, /result\?\.digest \|\| result\?\.summary/)
  assert.match(control, /digest\?\.financial_complete !== true/)
})

test('staff performance withholds sales and shift zeros when source reads are incomplete', async () => {
  const staff = await read('src/renderer/src/components/restaurant/RestaurantStaffPerformance.jsx')
  const main = await read('src/main/index.js')
  assert.match(staff, /ordersComplete/)
  assert.match(staff, /shiftsAvailable/)
  assert.match(staff, /server confirms complete sources/)
  assert.match(staff, /staff\.sales == null \? 'Unavailable'/)
  assert.match(main, /unavailablePosRead\(e, 'Shift history'\)/)
  assert.match(main, /unavailablePosRead\(e, 'Recipe variance'\)/)
  assert.match(main, /unavailablePosRead\(e, 'Preparation losses'\)/)
})

test('recipe variance and preparation-loss pages do not turn failed RPC reads into zero-cost reports', async () => {
  const variance = await read('src/renderer/src/components/restaurant/RestaurantRecipeVariance.jsx')
  const pos = await read('src/main/domains/pos.js')
  assert.match(variance, /sourceComplete/)
  assert.match(variance, /Variance evidence is unavailable until the server confirms complete report sources/)
  assert.match(variance, /sourceComplete \? `P \$\{totalVarianceValue\.toFixed\(2\)\}` : 'Unavailable'/)
  assert.doesNotMatch(variance, /Number\(loss\.preparation_loss_cost\) \|\| 0\)\.toFixed/)
  assert.match(pos, /p_outlet_id: outletId \|\| null\n    \}\)/)
  assert.doesNotMatch(pos, /p_include_reservation_waitlist: includeReservationWaitlist/)
})

test('finance overview does not convert unavailable settlement, deposit, tip or expense reads to zero', async () => {
  const overview = await read('src/renderer/src/components/restaurant/RestaurantFinanceOverview.jsx')
  const main = await read('src/main/index.js')
  assert.match(overview, /settlementsAvailable/)
  assert.match(overview, /depositsAvailable/)
  assert.match(overview, /tipsAvailable/)
  assert.match(overview, /expensesAvailable/)
  assert.match(overview, /settlementVariance == null/)
  assert.match(main, /unavailablePosRead\(e, 'Settlements'\)/)
  assert.match(main, /unavailablePosRead\(e, 'Reservation deposits'\)/)
  assert.match(main, /unavailablePosRead\(e, 'Tip balances'\)/)
})
