import test from 'node:test'
import assert from 'node:assert/strict'
import fs from 'node:fs'

const root = new URL('..', import.meta.url)
const read = (path) => fs.readFileSync(new URL(path, root), 'utf8')

test('deferred Bar migration is transactional and fail-closed for immutable proof evidence', () => {
  const sql = read('supabase/migrations/20260820140000_bar_base_deferred_service_tranche.sql')
  assert.match(sql, /^begin;/m)
  assert.match(sql, /commit;\s*$/m)
  assert.match(sql, /public\.pos_cashup_proof_storage_access\(name, true\)/)
  assert.match(sql, /public\.pos_cashup_proof_storage_access\(name, false\)/)
  assert.doesNotMatch(sql, /create policy private_cashup_proofs_delete/i)
  assert.match(sql, /on delete restrict/i)
  assert.match(sql, /prevent_pos_cashup_proof_mutation/)
  assert.match(sql, /v_row\.status <> 'submitted'/)
  assert.match(sql, /metadata->>'mimetype'/)
  assert.match(sql, /sha256.*\{64\}/i)
})

test('ticket mutation callers use the four-argument guarded RPC and stable operation key', () => {
  const desktop = read('src/main/domains/pos.js')
  const legacy = read('legacy-pos/src/main/index.js')
  const pwa = read('manager-pwa/src/lib/api.js')
  const probe = read('legacy-pos/scripts/probe-database-contract.mjs')
  assert.match(desktop, /p_operation_id: operationId/)
  assert.match(legacy, /p_operation_id: operationId/)
  assert.match(pwa, /p_operation_id: `pwa-ticket:/)
  assert.match(probe, /p_operation_id: 'probe-ticket-status'/)
  assert.match(read('src/main/domains/mesh/meshQueueMerge.js'), /missing ticket or operation id/)
})

test('Bar board and team controls preserve guarded UX contracts', () => {
  const board = read('src/renderer/src/components/hospitality-pos/HposKitchen.jsx')
  const team = read('src/renderer/src/components/hospitality-pos/HposTeam.jsx')
  const reports = read('src/renderer/src/components/hospitality-pos/HposReports.jsx')
  assert.match(board, /ticket\.tab_name \? 'tab'/)
  assert.match(board, /loadedOnceRef\.current/)
  assert.match(board, /ticketCollapseOverrides/)
  assert.match(board, /state === 'running'/)
  assert.match(team, /getBarActiveShifts/)
  assert.match(team, /handoverOperationId/)
  assert.match(team, /saveShiftHandoverNote/)
  assert.match(reports, /BAR_PRODUCT_CATEGORIES/)
  assert.match(reports, /product_id \|\| item\.menu_item_id \|\| item\.item_id/)
  assert.match(reports, /itemDetailReady/)
  assert.match(read('supabase/migrations/20260820140000_bar_base_deferred_service_tranche.sql'), /pg_advisory_xact_lock\(hashtext\(v_lodge::text \|\| ':' \|\| v_operation\)\)/)
})

test('cash-up proof uses the session-bound Storage client and fails closed without deployed app context', () => {
  const auth = read('src/main/domains/authClients.js')
  const domain = read('src/main/domains/pos.js')
  const main = read('src/main/index.js')
  const close = read('src/renderer/src/components/hospitality-pos/HposCashClose.jsx')
  const proofs = read('src/renderer/src/components/hospitality-pos/HposCashupProofs.jsx')
  const myCashup = read('src/renderer/src/components/hospitality-pos/HposMyCashup.jsx')
  const migration = read('supabase/migrations/20260820140000_bar_base_deferred_service_tranche.sql')
  const supabaseClient = read('node_modules/@supabase/supabase-js/src/SupabaseClient.ts')
  const storageClient = read('node_modules/@supabase/storage-js/src/StorageClient.ts')

  assert.match(auth, /global:\s*\{\s*headers: token \? \{ 'x-boroko-session': token \} : \{\}\s*\}/s)
  assert.match(auth, /state\.supabase = buildSupabaseClient\(SUPABASE_ANON_KEY, state\.backendSession\?\.token \|\| null\)/)
  assert.match(supabaseClient, /this\.storage = new SupabaseStorageClient\([\s\S]*this\.headers,[\s\S]*this\.fetch/)
  assert.match(storageClient, /return new StorageFileApi\(this\.url, this\.headers, id, this\.fetch\)/)
  assert.match(domain, /state\.supabase\.storage\.from\('private-cashup-proofs'\)/)
  assert.match(main, /pos:attachCashupProof[\s\S]*requireCapability\('pos\.view'\)/)
  assert.match(domain, /proof metadata requires a live authorized connection/)
  assert.doesNotMatch(domain, /file_base64|local_path|\.remove\(/)
  assert.match(proofs, /file\.arrayBuffer\(\)/)
  assert.match(proofs, /crypto\.subtle\.digest\('SHA-256'/)
  assert.match(proofs, /localStorage\.(getItem|setItem)/)
  assert.match(proofs, /attachCashupProof/)
  assert.match(proofs, /getCashupProofAttachments/)
  assert.match(proofs, /createCashupProofSignedUrl/)
  assert.match(close, /HposCashupProofs/)
  assert.match(myCashup, /HposCashupProofs/)
  assert.match(migration, /if v_lodge is distinct from public\.app_current_lodge_id\(\) then return false/)
  assert.match(migration, /exception when others then\s*return false/)
  assert.match(close, /deployed Storage policy is unavailable/)
  assert.doesNotMatch(proofs, /file_base64|local_path|createObjectURL|data:/i)
})
