import test from 'node:test'
import assert from 'node:assert/strict'
import { readFileSync, readdirSync } from 'node:fs'
import { join } from 'node:path'

const root = new URL('..', import.meta.url)
const read = (path) => readFileSync(new URL(path, root), 'utf8')
const workspace = read('src/renderer/src/components/restaurant/RestaurantWorkspace.jsx')
const restaurantDirectory = new URL('src/renderer/src/components/restaurant/', root)

test('restaurant workspaces expose a focused tab set with a recovery boundary', () => {
  for (const workspaceName of ['floor', 'kitchen', 'menu', 'stock', 'team', 'finance', 'control']) assert.match(workspace, new RegExp(`${workspaceName}:\\s*\\{`))
  assert.match(workspace, /RestaurantWorkspaceErrorBoundary/)
  assert.match(workspace, /No sale or stock change was made/)
  assert.match(workspace, /<ActiveComponent workspace=\{workspace\} tabKey=\{activeTab.key\}/)
})

test('Finance & close is the canonical home for financial controls, while guest controls stay separate', () => {
  for (const label of ['Cash-ups & Drawers', 'Sales & Payments', 'Settlements', 'Customer Funds', 'Expenses', 'Tips & Payouts', 'Daily Close', 'Owner Review & Digest']) {
    assert.match(workspace, new RegExp(label.replace(/[&]/g, '\\&')))
  }
  assert.match(workspace, /RestaurantCommercialControl section="settlements"/)
  assert.match(workspace, /RestaurantCommercialControl section="feedback"/)
  assert.match(workspace, /RestaurantCommercialControl section="deposits"/)
  assert.match(workspace, /key: 'policies', label: 'Guest Policies'/)
  assert.doesNotMatch(workspace, /key: 'commercial', label: 'Feedback & Deposits'/)
})

test('Sales & Payments makes receipt evidence visible and routes voids through the protected PIN contract', () => {
  const reports = read('src/renderer/src/components/hospitality-pos/HposReports.jsx')
  const posDomain = read('src/main/domains/pos.js')
  const numbering = read('supabase/migrations/20260716030000_pos_daily_order_and_receipt_numbers.sql')
  assert.match(reports, /Receipt & audit trail/)
  assert.match(reports, /Payment information/)
  assert.match(reports, /Void audit reference/)
  assert.match(reports, /approveVoidWithPin/)
  assert.match(reports, /Authorised approver PIN/)
  assert.match(reports, /reason are required/)
  assert.match(reports, /Packaged stock is restored only when returned unopened/)
  assert.match(reports, /settled\. Use the protected return workflow/)
  assert.match(reports, /transactionLabel/)
  assert.match(reports, /Order #\$\{order\.order_number\}/)
  assert.match(posDomain, /gte\('business_date', startDate\)/)
  assert.match(posDomain, /daily_order_number/)
  assert.match(posDomain, /transaction_type/)
  assert.match(numbering, /pos_daily_order_sequences/)
  assert.match(numbering, /Africa\/Gaborone/)
  assert.match(numbering, /'R-'/)
  assert.match(numbering, /lpad\(new\.daily_order_number::text, 4, '0'\)/)
  assert.match(numbering, /pos_orders_lodge_business_day_number_uidx/)
  const timezoneAuthority = read('supabase/migrations/20260716031000_pos_business_date_timezone_authority.sql')
  const voidDisposition = read('supabase/migrations/20260716032000_pos_void_packaged_stock_disposition.sql')
  assert.match(reports, /dateKeyInTimeZone/)
  assert.match(timezoneAuthority, /public\.settings/)
  assert.match(timezoneAuthority, /pos_business_date_at/)
  assert.match(reports, /Packaged stock outcome/)
  assert.match(reports, /direct_stock_disposition/)
  assert.match(reports, /Food, cocktails and other recipe items always remain consumed/)
  assert.match(reports, /hpos-transaction-status/)
  assert.match(voidDisposition, /direct_stock_disposition/)
  assert.match(voidDisposition, /recipe_stock_disposition', 'consumed'/)
  assert.match(voidDisposition, /public\._restore_pos_order_stock/)
})

test('waiters can request a correction from My Shift without seeing the outlet-wide void audit', () => {
  const reports = read('src/renderer/src/components/hospitality-pos/HposReports.jsx')
  const myShift = read('src/renderer/src/components/hospitality-pos/HposMyShift.jsx')
  const layout = read('src/renderer/src/components/hospitality-pos/HposLayout.jsx')
  const preload = read('src/preload/index.js')
  const main = read('src/main/index.js')
  assert.match(myShift, /Request sale correction/)
  assert.match(myShift, /supervisor or manager reviews it later/)
  assert.match(layout, /route: '\/hpos\/sale-correction'/)
  assert.match(reports, /Only your own Till sales appear here/)
  assert.match(reports, /correctionMode \? Promise\.resolve\(\[\]\) : window\.api\?\.pos\?\.getVoidHistory/)
  assert.match(preload, /getMyOrders: \(start, end\) => (?:invoke|ipcRenderer\.invoke)\('pos:getMyOrders', start, end\)/)
  assert.match(main, /ipcMain\.handle\('pos:getMyOrders'/)
  assert.match(main, /order\.cashier_id === currentUser\.id/)
})

test('shared Till exposes fast PIN-scoped operator history without granting access to another waiter’s sales', () => {
  const mySales = read('src/renderer/src/components/hospitality-pos/HposMySales.jsx')
  const terminal = read('src/renderer/src/components/hospitality-pos/HposTerminal.jsx')
  const preload = read('src/preload/index.js')
  const main = read('src/main/index.js')
  const posDomain = read('src/main/domains/pos.js')
  assert.match(terminal, /My sales/)
  assert.match(terminal, /lockSharedTillOperator/)
  assert.match(mySales, /My sales/)
  assert.match(mySales, /Showing this terminal’s saved sales/)
  assert.match(mySales, /getSharedTillHistory.*refresh: false/)
  assert.match(mySales, /getSharedTillHistory.*refresh: true/)
  assert.match(mySales, /Void sale \/ packaged return/)
  assert.match(mySales, /Record prepared-item cancellation/)
  assert.match(mySales, /ingredients stay consumed/)
  assert.match(mySales, /Authorised approver PIN/)
  assert.match(mySales, /direct_stock_disposition/)
  assert.match(preload, /getSharedTillHistory: \(start, end, options\) => (?:invoke|ipcRenderer\.invoke)\('pos:getSharedTillHistory'/)
  assert.match(preload, /lockSharedTillOperator: \(\) => (?:invoke|ipcRenderer\.invoke)\('pos:lockSharedTillOperator'\)/)
  assert.match(main, /resolveSharedTillHistoryAccess/)
  assert.match(main, /Unlock Till with your Staff PIN to view your sales history/)
  assert.match(main, /getSharedTillOperatorOrders\(start, end, outletFilter, access\.session\.staffId/)
  assert.match(posDomain, /getSharedTillOperatorOrders/)
  assert.match(posDomain, /order\?\.cashier_id === operatorId/)
  assert.match(posDomain, /direct_stock_disposition: payload\?\.direct_stock_disposition/)
})

test('interrupted POS submissions recover via a stable main-process envelope that must not double-charge', () => {
  const terminal = read('src/renderer/src/components/hospitality-pos/HposTerminal.jsx')
  const preload = read('src/preload/index.js')
  const main = read('src/main/index.js')
  const posDomain = read('src/main/domains/pos.js')
  const journal = read('src/main/domains/posSubmitJournal.js')
  const database = read('src/main/database.js')
  assert.match(terminal, /submitEnvelopeRef/)
  assert.match(terminal, /getPendingPosSubmitAttempt/)
  assert.doesNotMatch(terminal, /clearPendingPosSubmitAttempt/)
  assert.match(terminal, /Retry this exact attempt/)
  assert.doesNotMatch(terminal, /Start a new sale instead/)
  assert.match(terminal, /if it was not recorded, retry may complete that older sale now/)
  assert.match(terminal, /do not retry if you already entered a replacement sale/)
  assert.match(terminal, /The original operation completed or replayed under its existing key/)
  assert.match(terminal, /retryingSubmit = pendingEnvelope\?\.status === ["']pending["']/)
  assert.match(preload, /getPendingPosSubmitAttempt: \(\) => (?:invoke|ipcRenderer\.invoke)\('pos:getPendingPosSubmitAttempt'\)/)
  assert.doesNotMatch(preload, /clearPendingPosSubmitAttempt/)
  assert.match(main, /ipcMain\.handle\('pos:getPendingPosSubmitAttempt'/)
  assert.doesNotMatch(main, /pos:clearPendingPosSubmitAttempt/)
  assert.match(database, /getPendingPosSubmitAttempt/)
  assert.doesNotMatch(database, /clearPendingPosSubmitAttempt/)
  assert.match(posDomain, /resolvePosSubmitAttempt/)
  assert.match(posDomain, /commitPosSubmitAttempt/)
  assert.match(posDomain, /pos_submit_recovery_server_check_failed/)
  assert.doesNotMatch(posDomain, /getPosOrderById\(attempt\.orderId\)\.catch\(\(\) => null\)/)
  assert.match(posDomain, /idempotency_conflict/)
  assert.match(journal, /pos-submit-attempts\.json/)
  assert.match(journal, /digest/)
  assert.match(journal, /sha256/)
  assert.match(journal, /pos_submit_recovery_required/)
  assert.match(journal, /Reconcile or retry that exact attempt before starting a new sale/)
})

test('shift close uses the authoritative cash-up contract online and through guarded offline replay', () => {
  const posDomain = read('src/main/domains/pos.js')
  const main = read('src/main/index.js')
  const posUi = read('src/renderer/src/components/POS.jsx')
  const closeBody = posDomain.slice(
    posDomain.indexOf('export async function closePosShift'),
    posDomain.indexOf('export async function getPosHardwareSettings')
  )
  assert.match(closeBody, /finalize_pos_shift_cashup_v2/, 'close must route through the authoritative finalize RPC')
  assert.match(closeBody, /pos-cashup-close:\$\{shift\.id\}/, 'close must use a stable idempotency key per shift')
  assert.match(closeBody, /queueOperation\('rpc', 'finalize_pos_shift_cashup_v2'/, 'offline close must queue the same authoritative finalizer')
  assert.match(closeBody, /_depends_on_all: dependencies/, 'offline close must wait for every queued shift sale dependency')
  assert.match(closeBody, /provisional: true/, 'offline close must remain visibly provisional until server replay')
  assert.match(closeBody, /readAuthoritativeShiftClose/, 'ambiguous closes must use an exact server resolution read')
  assert.doesNotMatch(closeBody, /status: 'closed'\s*\}/, 'failed results must not force a local closed state')
  assert.match(closeBody, /appendPosAudit\('shift_closed'/, 'closed shift must be audited')
  assert.match(main, /ipcMain\.handle\('pos:closeShift'[\s\S]*requireCapability\('pos\.cashup'\)/, 'shift close must require the pos.cashup capability')
  assert.match(posUi, /Closing reconciles and settles this shift on the server and requires supervisor or manager access/)
})

test('recipe cancellations are reported as preparation loss, separate from financial revenue', () => {
  const variance = read('src/renderer/src/components/restaurant/RestaurantRecipeVariance.jsx')
  const posDomain = read('src/main/domains/pos.js')
  const preload = read('src/preload/index.js')
  const main = read('src/main/index.js')
  const migration = read('supabase/migrations/20260716034000_recipe_preparation_loss_reporting.sql')
  assert.match(variance, /Preparation loss/)
  assert.match(variance, /operational waste, not financial revenue/)
  assert.match(variance, /Frozen recipe cost/)
  assert.match(variance, /getRecipePreparationLosses/)
  assert.match(variance, /Preparation loss by ingredient/)
  assert.match(variance, /This is not a percentage of stock bought/)
  assert.match(posDomain, /get_recipe_preparation_losses/)
  assert.match(preload, /pos:getRecipePreparationLosses/)
  assert.match(main, /ipcMain\.handle\('pos:getRecipePreparationLosses'/)
  assert.match(migration, /pos_order_voided/)
  assert.match(migration, /recipe_stock_disposition' = 'consumed'/)
  assert.match(migration, /sum\(abs\(coalesce\(m\.theoretical_cost, 0\)\)\)/)
  assert.match(migration, /app_require_lodge_role/)
  const ingredientSummary = read('supabase/migrations/20260716035000_recipe_preparation_loss_ingredient_summary.sql')
  assert.match(ingredientSummary, /get_recipe_preparation_loss_ingredient_summary/)
  assert.match(ingredientSummary, /total_recipe_quantity/)
  assert.match(ingredientSummary, /loss_percentage/)
})

test('shared Till sales use the PIN-verified shift owner instead of the manager login', () => {
  const migration = read('supabase/migrations/20260716033000_pos_order_operator_from_shift.sql')
  assert.match(migration, /assign_pos_order_operator_from_shift/)
  assert.match(migration, /s\.id = new\.shift_id/)
  assert.match(migration, /new\.cashier_id := v_shift\.cashier_id/)
  assert.match(migration, /trg_pos_orders_assign_operator_from_shift/)
  assert.match(migration, /pos_order_operator_repaired/)
  assert.match(migration, /Rows without a[\s\S]*remain untouched/)
})

test('Outlet control provides guarded Restaurant & Bar outlet setup instead of a Till shortcut', () => {
  const outletControl = read('src/renderer/src/components/MultiOutletPos.jsx')
  const migration = read('supabase/migrations/20260716015000_restaurant_outlet_control_pos_entitlement.sql')
  assert.match(outletControl, /Create another outlet/)
  assert.match(outletControl, /createRestaurantOutlet/)
  assert.match(outletControl, /updateRestaurantOutlet/)
  assert.match(outletControl, /Sales from this Till now draw from that stock location/)
  assert.match(outletControl, /hpos-outlet-editor__field/)
  assert.match(outletControl, /Display priority/)
  assert.match(migration, /app_require_feature\(p_lodge_id, 'pos', array\['manager', 'admin', 'super_admin'\]\)/)
  assert.match(migration, /Keep at least one active outlet/)
  assert.match(migration, /restaurant_outlet_control_audit/)
})

test('outlet transfers move allocated stock while keeping business stock aggregate intact', () => {
  const migration = read('supabase/migrations/20260716018000_restaurant_outlet_stock_balances.sql')
  const outletControl = read('src/renderer/src/components/MultiOutletPos.jsx')
  assert.match(migration, /restaurant_outlet_stock_balances/)
  assert.match(migration, /v_source_after := public\.restaurant_apply_outlet_stock_balance/)
  assert.match(migration, /v_destination_after := public\.restaurant_apply_outlet_stock_balance/)
  assert.match(migration, /v_transfer_id uuid := coalesce\(nullif\(payload->>'id'/)
  assert.match(outletControl, /Source balance:/)
  assert.match(outletControl, /crypto\.randomUUID\(\)/)
})

test('stock locations are separate from sales outlets and are selected when goods are received', () => {
  const migration = read('supabase/migrations/20260716019000_restaurant_stock_locations.sql')
  const purchasing = read('src/renderer/src/components/restaurant/RestaurantPurchasing.jsx')
  const outletControl = read('src/renderer/src/components/MultiOutletPos.jsx')
  const posDomain = read('src/main/domains/pos.js')
  assert.match(migration, /restaurant_stock_locations/)
  assert.match(migration, /Shared business stock/)
  assert.match(migration, /restaurant_outlet_stock_locations/)
  assert.match(migration, /stock_location_id/)
  assert.match(migration, /record_recipe_stock_depletion/)
  assert.match(purchasing, /Receive goods into/)
  assert.match(purchasing, /This is where the goods physically arrive\. It is not the Till/)
  assert.match(outletControl, /Sales outlets can share stock/)
  assert.match(outletControl, /From stock location/)
  assert.match(outletControl, /Stock by physical location/)
  assert.match(outletControl, /Unallocated/)
  assert.match(posDomain, /getRestaurantStockLocations/)
  assert.match(posDomain, /getRestaurantStockLocationBalances/)
  const serverAtomic = read('supabase/migrations/20260805090000_pos_recipe_stock_depletion_server_atomic.sql')
  assert.match(serverAtomic, /restaurant_apply_recipe_sale_depletion/)
  assert.match(serverAtomic, /trg_restaurant_recipe_sale_depletion/)
  assert.match(serverAtomic, /derive.*authoritative|from public\.pos_order_items/)
  assert.match(serverAtomic, /get_pos_orders_missing_recipe_movements/)
  assert.doesNotMatch(posDomain, /await recordRecipeStockDepletion\(result\.id \|\| orderId/)
})

test('direct-stock menu items consume the assigned stock location and restore it on void', () => {
  const migration = read('supabase/migrations/20260716024000_restaurant_direct_stock_location_depletion.sql')
  assert.match(migration, /restaurant_apply_direct_pos_stock_location_depletion/)
  assert.match(migration, /trg_restaurant_direct_pos_stock_location_depletion/)
  assert.match(migration, /restaurant_outlet_stock_locations/)
  assert.match(migration, /restaurant_apply_stock_location_balance/)
  assert.match(migration, /create or replace function public\._restore_pos_order_stock/)
})

test('new menu items start with a blank section and require an intentional selection', () => {
  const menu = read('src/renderer/src/components/hospitality-pos/HposMenu.jsx')
  assert.match(menu, /const emptyDraft = \(\) => \(\{\s*name: "",\s*category: ""/)
  assert.match(menu, /placeholder="Choose a section"/)
  assert.match(menu, /choose a menu section/)
})

test('menu setup distinguishes packaged stock from recipe-required food and cocktails', () => {
  const menu = read('src/renderer/src/components/hospitality-pos/HposMenu.jsx')
  const recipes = read('src/renderer/src/components/restaurant/RestaurantRecipes.jsx')
  const migration = read('supabase/migrations/20260716025000_restaurant_menu_stock_methods.sql')
  assert.match(menu, /Prepared food or cocktail — recipe required/)
  assert.match(menu, /Packaged \/ pre-made item — direct stock/)
  assert.match(menu, /Non-stock service — no inventory/)
  assert.match(menu, /restaurant\/menu-production\?tab=recipes/)
  assert.match(recipes, /Saving the recipe will make this menu item available at Till/)
  assert.match(migration, /stock_method in \('direct', 'recipe', 'non_stock'\)/)
  assert.match(migration, /restaurant_menu_category_requires_recipe/)
  assert.match(migration, /menu_item_activated/)
  assert.match(migration, /This menu item no longer matches its configured stock method/)
})

test('open checks require the serving operator and active Till shift, while recipes show their actual commercial data', () => {
  const terminal = read('src/renderer/src/components/hospitality-pos/HposTerminal.jsx')
  const posDomain = read('src/main/domains/pos.js')
  const menu = read('src/renderer/src/components/hospitality-pos/HposMenu.jsx')
  const recipes = read('src/renderer/src/components/restaurant/RestaurantRecipes.jsx')
  const migration = read('supabase/migrations/20260716026000_restaurant_open_tab_operator_and_recipe_clarity.sql')
  const priceGuard = read('supabase/migrations/20260716027000_restaurant_menu_price_guard.sql')
  assert.match(terminal, /verify their Staff PIN before holding an open check/)
  assert.match(terminal, /shift_id: currentShift\.id/)
  assert.match(posDomain, /Unlock Till with the serving staff PIN and start their shift before holding an open check/)
  assert.match(migration, /waiter_id uuid references public\.users/)
  assert.match(migration, /shift_id uuid references public\.pos_shifts/)
  assert.match(migration, /s\.cashier_id = v_waiter_id/)
  assert.match(migration, /pos_audit_log/)
  assert.match(menu, /price greater than P0\.00 before setting up stock or a recipe/)
  assert.match(menu, /min="0\.01"/)
  assert.match(priceGuard, /enforce_restaurant_menu_positive_price/)
  assert.match(priceGuard, /Set a menu price greater than P0\.00/)
  assert.match(recipes, /ing\.inventory_item_name/)
  assert.match(recipes, /ing\.latest_unit_cost/)
  assert.match(recipes, /Linked menu item:/)
  assert.match(recipes, /Recipe revision/)
  assert.doesNotMatch(recipes, /v\{recipe\.version\}/)
})

test('recipe costing converts compatible inventory units and Stock Control exposes the governed unit cost', () => {
  const migration = read('supabase/migrations/20260716028000_restaurant_recipe_unit_integrity.sql')
  const stock = read('src/renderer/src/components/restaurant/RestaurantStock.jsx')
  const recipes = read('src/renderer/src/components/restaurant/RestaurantRecipes.jsx')
  assert.match(migration, /p_quantity \/ 1000/)
  assert.match(migration, /Recipe unit % is not compatible with the inventory counting unit %/)
  assert.match(migration, /v_depleted:=public\.restaurant_recipe_quantity_in_inventory_unit/)
  assert.match(migration, /set_inventory_unit_cost/)
  assert.match(stock, /Current unit cost/)
  assert.match(stock, /latest_unit_cost/)
  assert.match(recipes, /recipe_unit_cost/)
  assert.match(recipes, /role="alert"/)
})

test('Till keeps an outlet preference on this terminal without making it a server setting', () => {
  const terminal = read('src/renderer/src/components/hospitality-pos/HposTerminal.jsx')
  assert.match(terminal, /hpos-terminal-outlet:/)
  assert.match(terminal, /window\.localStorage\?\.setItem/)
  assert.match(terminal, /preferredOutlet/)
  assert.match(terminal, /resumedOutlet \|\| preferredOutlet \|\| activeOutlets\[0\]/)
  assert.match(terminal, /Saved on this computer only/)
})

test('shared Till PIN and receipt print controls remain touch-first', () => {
  const styles = read('src/renderer/src/styles/hospitality-pos.css')
  const receipt = read('src/renderer/src/components/shared/POSReceipt.jsx')
  assert.match(styles, /\.hpos-till-keypad button\{min-height:64px/)
  assert.match(styles, /\.hpos-till-unlock-confirm\{display:flex;width:min\(420px,100%\);min-height:58px/)
  assert.match(receipt, /Print receipt/)
  assert.match(receipt, /bg-emerald-600/)
})

test('growth controls do not duplicate unrelated management forms across tabs', () => {
  const growth = read('src/renderer/src/components/restaurant/RestaurantGrowthControls.jsx')
  for (const gate of ['showGift', 'showTips', 'showLots', 'showPolicy']) assert.match(growth, new RegExp(`\\{${gate} &&`))
  assert.match(growth, /const title = showLots/)
})

test('restaurant components remain isolated from accommodation APIs', () => {
  const files = readdirSync(restaurantDirectory).filter((file) => file.endsWith('.jsx'))
  for (const file of files) {
    const source = read(`src/renderer/src/components/restaurant/${file}`)
    assert.doesNotMatch(source, /window\.api\.(bookings|rooms|guests|housekeeping|conference|dayuse)/, `${file} must not call accommodation APIs`)
  }
})

test('table configuration is manager-only and reservation errors are visible to operators', () => {
  const tables = read('src/renderer/src/components/restaurant/RestaurantTables.jsx')
  const floor = read('src/renderer/src/components/hospitality-pos/HposFloorPlan.jsx')
  const reservations = read('src/renderer/src/components/restaurant/RestaurantReservations.jsx')
  assert.match(tables, /canAccessCapability\(access, 'pos\.manage'\)/)
  assert.match(tables, /window\.api\?\.pos\?\.saveTable/)
  assert.match(tables, /Resolve the running check or reservation before archiving this table/)
  assert.match(floor, /start or continue its Till transaction/)
  assert.doesNotMatch(floor, /saveTable|Manage table|Archive/)
  assert.match(reservations, /Could not update reservation/)
  assert.match(reservations, /\['booked', 'confirmed'\]\.includes\(r\.status\)/)
})
