import assert from 'node:assert/strict'
import fs from 'node:fs'
import path from 'node:path'
import test from 'node:test'

const root = path.resolve(import.meta.dirname, '..')
const read = (file) => fs.readFileSync(path.join(root, file), 'utf8')

test('waiters have a bounded, audited reservation and waitlist service workflow', () => {
  const access = read('src/shared/accessControl.js')
  const main = read('src/main/index.js')
  const preload = read('src/preload/index.js')
  const page = read('src/renderer/src/components/hospitality-pos/HposServiceReservations.jsx')
  const manager = read('src/renderer/src/components/restaurant/RestaurantReservations.jsx')
  const floor = read('src/renderer/src/components/hospitality-pos/HposFloorPlan.jsx')
  const migration = read('supabase/migrations/20260716040000_restaurant_service_reservations_waitlist.sql')
  assert.match(access, /'pos\.service': 'Run table service, reservations and waitlist'/)
  assert.match(access, /cashier:[\s\S]*'pos\.service'/)
  assert.match(main, /pos:updateRestaurantWaitlistEntry[\s\S]*requireCapability\('pos\.service'\)/)
  assert.match(main, /pos:createRestaurantReservation[\s\S]*requireCapability\('pos\.service'\)/)
  assert.match(main, /pos:serviceRestaurantReservationAction[\s\S]*requireCapability\('pos\.service'\)/)
  assert.match(preload, /updateRestaurantWaitlistEntry/)
  assert.match(preload, /removeRestaurantWaitlistEntry/)
  assert.match(page, /Edit walk-in/)
  assert.match(page, /recorded; it is not deleted/)
  assert.match(page, /serviceRestaurantReservationAction/)
  assert.match(page, /Add reservation/)
  assert.match(page, /reservation_capacity_full/)
  assert.match(page, /Add to reservation waitlist/)
  assert.match(page, /shared guest list/)
  assert.doesNotMatch(page, /bg-slate|text-slate|bg-white\/10/)
  assert.match(manager, /updateRestaurantWaitlistEntry/)
  assert.match(manager, /removeRestaurantWaitlistEntry/)
  assert.match(manager, /Edit walk-in/)
  assert.match(manager, /Remove from waitlist/)
  assert.match(floor, /Reservations & waitlist/)
  assert.match(migration, /restaurant_service_events/)
  assert.match(migration, /Only an active waitlist entry can be removed/)
  assert.match(migration, /This reservation action is not available during service/)
  assert.match(migration, /for update/)
  const phoneReservationMigration = read('supabase/migrations/20260716041000_restaurant_phone_reservations_and_waitlist.sql')
  assert.match(phoneReservationMigration, /pg_advisory_xact_lock/)
  assert.match(phoneReservationMigration, /reservation_capacity_full/)
  assert.match(phoneReservationMigration, /reservation_waitlist_created/)
})
