import test from 'node:test'
import assert from 'node:assert/strict'
import fs from 'node:fs'
const sql=fs.readFileSync(new URL('../supabase/migrations/20260720060000_restaurant_accounting_tax_working_papers.sql',import.meta.url),'utf8')
test('uses versioned effective tax configurations and lodge accounts',()=>{assert.match(sql,/jurisdiction_code text not null/);assert.match(sql,/rule_version text not null/);assert.match(sql,/effective_from<=p_period_start/);assert.match(sql,/output tax account must be an active lodge liability/i);assert.match(sql,/input tax account must be an active lodge asset/i)})
test('derives working papers from posted ledger sources',()=>{assert.match(sql,/restaurant_journal_entries e join public\.restaurant_journal_lines/);assert.match(sql,/e\.source_type in\('pos_sale','pos_return'\)/);assert.match(sql,/e\.source_type='ap_bill'/);assert.doesNotMatch(sql,/from public\.expenses/)})
test('stores immutable source snapshots and hashes',()=>{assert.match(sql,/source_snapshot jsonb/);assert.match(sql,/snapshot_hash text/);assert.match(sql,/v_hash:=encode\(digest\(v_snapshot::text,'sha256'\)/);assert.match(sql,/working_paper_only',true/)})
test('requires independent preparation review and approval',()=>{assert.match(sql,/Working-paper preparer cannot review it/);assert.match(sql,/Working-paper preparer cannot approve it/);assert.match(sql,/status='reviewed'/);assert.match(sql,/status='approved',approved_by=v_actor,approved_at=now\(\)/)})
test('cannot claim filed without immutable approval and reference',()=>{assert.match(sql,/Authoritative filing reference is required/);assert.match(sql,/Approved immutable working paper is required before filing/);assert.match(sql,/Working-paper approver cannot record the filing/);assert.match(sql,/filing_reference=btrim\(p_filing_reference\)/)})
test('keeps tax rebuild service-role only',()=>{assert.doesNotMatch(sql,/grant execute[\s\S]*to authenticated/i);for(const n of ['generate_restaurant_tax_working_paper','review_restaurant_tax_working_paper','approve_restaurant_tax_working_paper','record_restaurant_tax_filing'])assert.match(sql,new RegExp(`revoke all on function public\\.${n}`))})
