import assert from 'node:assert/strict'
import { readFileSync } from 'node:fs'
import { resolve } from 'node:path'

const read = (path) => readFileSync(resolve(path), 'utf8')
const terminal = read('src/renderer/src/components/hospitality-pos/HposTerminal.jsx')
const cashClose = read('src/renderer/src/components/hospitality-pos/HposCashClose.jsx')
const manageHub = read('src/renderer/src/components/hospitality-pos/HposManageHub.jsx')
const reports = read('src/renderer/src/components/hospitality-pos/HposReports.jsx')
const expenses = read('src/renderer/src/components/hospitality-pos/HposExpenses.jsx')
const hposStyles = read('src/renderer/src/styles/hospitality-pos.css')
const kitchen = read('src/renderer/src/components/hospitality-pos/HposKitchen.jsx')
const floor = read('src/renderer/src/components/hospitality-pos/HposFloorPlan.jsx')
const layout = read('src/renderer/src/components/hospitality-pos/HposLayout.jsx')
const openChecks = read('src/renderer/src/components/hospitality-pos/HposOpenChecks.jsx')
const commandPalette = read('src/renderer/src/components/hospitality-pos/HposCommandPalette.jsx')
const ui = read('src/renderer/src/components/hospitality-pos/HposUi.jsx')
const health = read('src/renderer/src/components/hospitality-pos/HposSystemHealth.jsx')
const businessControl = read('src/renderer/src/components/hospitality-pos/HposBusinessControl.jsx')
const accessControl = read('src/shared/accessControl.js')
const barModeProfile = read('src/shared/barModeProfile.js')
const restaurantWorkspace = read('src/renderer/src/components/restaurant/RestaurantWorkspace.jsx')
const restaurantPageGuide = read('src/renderer/src/components/restaurant/RestaurantPageGuide.jsx')
const restaurantStock = read('src/renderer/src/components/restaurant/RestaurantStock.jsx')
const restaurantRecipes = read('src/renderer/src/components/restaurant/RestaurantRecipes.jsx')
const restaurantWorkspaceStyles = read('src/renderer/src/styles/restaurant-workspaces.css')
const quickStock = read('src/renderer/src/components/hospitality-pos/HposStock.jsx')
const purchaseSuggestions = read('src/renderer/src/components/restaurant/RestaurantPurchaseSuggestions.jsx')
const inventoryLots = read('src/renderer/src/components/restaurant/RestaurantInventoryLots.jsx')
const login = read('src/renderer/src/components/Login.jsx')
const app = read('src/renderer/src/App.jsx')
const promotionRepair = read('supabase/migrations/20260713140000_pos_promotion_checkout_repair.sql')
const safeMenuDelete = read('supabase/migrations/20260714249000_safe_pos_menu_item_delete.sql')
const menuArchiveState = read('supabase/migrations/20260714250000_pos_menu_archive_state.sql')
const restaurantGuardRepair = read('supabase/migrations/20260714251000_restaurant_guard_settings_scope_repair.sql')
const menuStockReadiness = read('supabase/migrations/20260715001000_pos_menu_stock_readiness.sql')
const recipeMovementRepair = read('supabase/migrations/20260715002000_restore_recipe_sale_stock_movements.sql')
const stocktakeLedgerRepair = read('supabase/migrations/20260715003000_inventory_stocktake_read_and_ledger_repair.sql')
const purchaseSuggestionSupplierAssignment = read('supabase/migrations/20260715005000_purchase_suggestion_supplier_assignment.sql')
const purchaseOrderQuantityGuardrails = read('supabase/migrations/20260715006000_purchase_order_quantity_guardrails.sql')
const inventoryLotActorGuard = read('supabase/migrations/20260715008000_inventory_lot_actor_guard.sql')
const inventoryLotExpiryCorrections = read('supabase/migrations/20260715009000_inventory_lot_expiry_corrections.sql')
const expiredLotWriteoff = read('supabase/migrations/20260715010000_expired_lot_writeoff.sql')
const restaurantShiftStaffGuard = read('supabase/migrations/20260715011000_restaurant_shift_staff_guard.sql')
const restaurantTipPayoutStaffGuard = read('supabase/migrations/20260715012000_restaurant_tip_payout_staff_guard.sql')

for (const source of [terminal, cashClose, manageHub, kitchen, floor]) {
  assert.doesNotMatch(source, /window\.api\?\.rpc\?\./, 'Restaurant workspaces must use explicit preload APIs.')
}

assert.match(kitchen, /window\.api\?\.pos\?\.getTickets\?\./, 'Kitchen must load real prep tickets.')
assert.match(kitchen, /function getTicketReference/, 'Kitchen must display an operator-friendly ticket reference.')
assert.match(kitchen, /Ticket \$\{reference\.slice\(-6\)\.toUpperCase\(\)\}/, 'Kitchen must not expose full UUIDs as its primary ticket reference.')
assert.match(kitchen, /item\.item_name \|\| item\.name/, 'Kitchen tickets must display the line-item name from the authoritative prep-ticket payload.')
assert.match(kitchen, /const \[serviceDate, setServiceDate\] = useState\(\(\) => localDateKey\(\)\)/, 'Kitchen must default to the current service date.')
assert.match(kitchen, /type="date"/, 'Kitchen must let operators select a service date.')
assert.match(kitchen, /Manage stations/, 'Kitchen must expose station management to operators.')
assert.match(openChecks, /window\.api\?\.pos\?\.getTabs\?\./, 'Open Checks must use authoritative POS tabs.')
assert.match(openChecks, /navigate\('\/hpos\/pos'/, 'Open Checks must resume inside the native terminal.')
assert.match(layout, /liveCounts/, 'HPOS rail must expose live operational intelligence.')
assert.match(layout, /e\.ctrlKey\s*\|\|\s*e\.metaKey/, 'HPOS shell must provide a cross-platform command shortcut.')
assert.match(layout, /HPOS_SEARCH_ACTIONS/, 'Global search must maintain an explicit index of operational actions.')
assert.match(layout, /label: 'Reservation deposits'/, 'Global search must expose reservation deposits by their financial action name.')
assert.match(layout, /route: '\/restaurant\/finance-close\?tab=customer-funds'/, 'Reservation-deposit search results must open the Finance customer-funds tab.')
assert.match(layout, /label: 'Settlement reconciliation'/, 'Global search must expose settlement reconciliation by its financial action name.')
assert.match(commandPalette, /role="dialog"/, 'Command palette must be an accessible modal dialog.')
assert.match(ui, /HposPageHero/, 'HPOS must expose reusable product UI primitives.')
assert.match(health, /window\.api\?\.sync\?\.getStatus\?\./, 'HPOS System Health must use the real sync status contract.')
assert.doesNotMatch(health, /window\.api\?\.(?:bookings|rooms|guests)/, 'HPOS System Health must not load accommodation APIs.')
assert.match(businessControl, /record pour \/ waste variance/i, 'Business Control must expose bar variance accountability.')
assert.match(businessControl, /adjustStock/, 'Bar variance must reuse the authoritative inventory adjustment contract.')
assert.match(businessControl, /getPromotions/, 'Business Control must expose server-backed promotion management.')
assert.match(businessControl, /getRestaurantReservations/, 'Business Control must expose reservation and guest-flow signals.')
assert.match(businessControl, /getLowStockPurchaseSuggestions/, 'Business Control must expose procurement intelligence.')
assert.match(businessControl, /saveRestaurantShiftPlan/, 'Business Control must expose persistent labour planning.')
assert.match(businessControl, /starts_at/, 'Business Control must expose scheduled promotion timing.')
assert.match(terminal, /promotion_id:\s*selectedPromotion\?\.id/, 'The terminal must submit the selected promotion to authoritative pricing.')
assert.match(terminal, /minimum_spend/, 'The terminal must explain promotion eligibility before payment.')
assert.match(promotionRepair, /Promotion minimum spend is not met/, 'Checkout must enforce promotion minimum spend server-side.')
assert.match(promotionRepair, /Promotion is outside its scheduled period/, 'Checkout must enforce promotion timing server-side.')
assert.match(promotionRepair, /customer_segment/, 'Checkout must enforce customer-segment offers server-side.')
assert.match(businessControl, /rows\.some\(\(row\) => row\.supplier_id !== supplier\)/, 'Purchase suggestions from different suppliers must not share one PO.')
assert.match(businessControl, /await onReload\(\)/, 'Persistent manager actions must refresh their live view.')
assert.match(businessControl, /Expected closing quantity/, 'Bar variance must compare expected and measured closing stock.')
assert.match(businessControl, /Repeated void pattern/, 'Manager control must surface repeated void risk signals.')
assert.doesNotMatch(terminal, /if \(e\.key === 'Escape'\) \{\s*setCart\(\[\]\)/, 'Escape must never silently discard a live cart.')
assert.match(kitchen, /window\.api\?\.pos\?\.updateTicketStatus\?\./, 'Kitchen status changes must use the authoritative ticket contract.')
assert.match(floor, /Object\.keys\(TABLE_STATES\)/, 'Floor summary keys must be derived from TABLE_STATES.')
assert.match(floor, /normalizeTableStatus\(table\.status\) === status/, 'Floor counts must use the same status normalization as its table cards.')
assert.doesNotMatch(floor, /(?:^|\n)\s{4}attention:\s*tables\.filter/m, 'Floor must not emit an undefined attention state key.')

assert.doesNotMatch(terminal, /import POS from ['"]\.\.\/POS['"]/, 'The restaurant app must not render the Lodge app POS component.')
assert.doesNotMatch(cashClose, /import POS from ['"]\.\.\/POS['"]/, 'Restaurant cash close must remain restaurant-native.')
assert.match(terminal, /window\.api\.pos\.createOrder\(/, 'Restaurant sales must use the authoritative POS order contract.')
assert.match(terminal, /submit_intent_id:\s*submitIntentId/, 'The restaurant terminal must preserve stable idempotency intent IDs.')
assert.match(terminal, /window\.api\.pos\.openTableSession\(/, 'Table service must use the authoritative table session contract.')
assert.match(terminal, /window\.api\?\.pos\?\.openShift\?\./, 'Restaurant operators must be able to start an accountable shift in the new app.')
assert.match(terminal, /Start your shift/, 'Missing-shift guidance must be visible in the restaurant design.')
assert.match(terminal, /Record payment & close check/, 'Table settlement must be labelled as a distinct action.')
assert.ok(
  terminal.indexOf('{(submitError || successMessage) && (') < terminal.indexOf('{/* Totals + Payment */}'),
  'Order confirmation must remain visible after checkout clears the cart.'
)
assert.match(terminal, /CheckCircle/, 'Completed orders must have a clear visual success signal.')
assert.match(terminal, /minHeight: 52/, 'Order confirmation must remain touch-visible after checkout.')
assert.match(terminal, /const addToCart = useCallback\(\(item\) => \{\s*\/\/ A completed sale[\s\S]*?setSuccessMessage\(''\)/, 'Starting a new order must clear the prior sale confirmation.')
assert.match(terminal, /mobile_money/, 'The restaurant payment chooser must include mobile money.')
assert.match(terminal, /open check loaded/, 'Selecting an occupied table must restore its open check.')
assert.match(terminal, /serviceMode === 'delivery'/, 'The restaurant terminal must retain delivery service.')
assert.match(terminal, /delivery_address:/, 'Delivery orders must preserve their address.')
assert.match(terminal, /customer_account_charge:/, 'Customer-account charges must remain authoritative.')
assert.match(terminal, /getModifierGroups/, 'The restaurant terminal must load modifiers.')
assert.match(terminal, /modifier_total/, 'Modifier totals must be preserved.')
assert.match(terminal, /awardLoyalty/, 'The restaurant terminal must retain loyalty awards.')
assert.match(terminal, /redeemVoucher/, 'The restaurant terminal must retain voucher redemption.')
assert.match(read('src/renderer/src/components/hospitality-pos/HposMenu.jsx'), /Mark sold out/, 'Menu must support a rapid 86-item action during service.')
assert.match(read('src/renderer/src/components/hospitality-pos/HposMenu.jsx'), /Make available/, 'Menu must restore an item after it is available again.')
assert.match(read('src/renderer/src/components/hospitality-pos/HposMenu.jsx'), /updateMenuItem\(item\.id/, 'Availability changes must use the authoritative menu update contract.')
assert.match(read('src/renderer/src/components/hospitality-pos/HposMenu.jsx'), /availabilityBusy \? 'Saving…'/, 'Menu availability actions must visibly acknowledge an in-progress save.')
assert.match(read('src/renderer/src/components/hospitality-pos/HposMenu.jsx'), /RESTAURANT_MENU_SECTIONS/, 'Restaurant menus must provide standard category suggestions.')
assert.match(read('src/renderer/src/components/hospitality-pos/HposMenu.jsx'), /'Desserts'/, 'Restaurant menus must include a dessert section.')
assert.match(read('src/renderer/src/components/hospitality-pos/HposMenu.jsx'), /'Mains'/, 'Restaurant menus must include a mains section.')
assert.match(read('src/renderer/src/components/hospitality-pos/HposMenu.jsx'), /'Drinks'/, 'Restaurant menus must include a drinks section for bar routing.')
assert.match(read('src/renderer/src/components/hospitality-pos/HposMenu.jsx'), /> Delete/, 'Menu deletion must be clearly labelled for touch operators.')
assert.match(read('src/renderer/src/components/hospitality-pos/HposMenu.jsx'), /Delete \$\{item\.name\}/, 'Menu deletion must require an explicit confirmation.')
assert.match(safeMenuDelete, /FROM public\.pos_order_items WHERE menu_item_id = p_id/, 'Menu deletion must preserve financial history when an item has been sold.')
assert.match(safeMenuDelete, /DELETE FROM public\.pos_menu_items/, 'Unused menu items must be removable without leaving setup clutter.')
assert.match(read('src/renderer/src/components/hospitality-pos/HposMenu.jsx'), /Item archived because it has sale history/, 'Operators must be told when deletion safely becomes archival.')
assert.match(menuArchiveState, /ADD COLUMN IF NOT EXISTS archived_at/, 'Archived menu items must have distinct persisted state.')
assert.match(menuArchiveState, /archived_at = now\(\)/, 'Sale-linked menu deletions must be visibly archived, not merely marked sold out.')
assert.match(read('src/renderer/src/components/hospitality-pos/HposMenu.jsx'), /Show archived items/, 'Archived menu items must be out of the normal service-management view by default.')
assert.match(read('src/renderer/src/components/hospitality-pos/HposMenu.jsx'), /Direct stock link/, 'Restaurant operators must be able to link a packaged item to existing stock.')
assert.match(read('src/renderer/src/components/hospitality-pos/HposMenu.jsx'), /Save as draft/, 'Unlinked prepared food must remain a draft while its recipe is created.')
assert.match(read('src/renderer/src/components/hospitality-pos/HposMenu.jsx'), /Needs stock setup/, 'Existing untracked menu items must be visible for manager repair.')
assert.match(read('src/renderer/src/components/hospitality-pos/HposMenu.jsx'), /not sold out/, 'Stock-repair drafts must not be represented as sold-out menu items.')
assert.match(read('src/renderer/src/components/hospitality-pos/HposMenu.jsx'), /Recipes &amp; Costing/, 'Menu must tell operators how to repair prepared-food stock setup.')
assert.match(read('src/renderer/src/components/hospitality-pos/HposMenu.jsx'), /Recipe stock method active/, 'Menu editing must explain why a prepared item without a direct stock link can be available.')
assert.match(read('src/renderer/src/components/hospitality-pos/HposMenu.jsx'), /disabled=\{editingStockMethod === 'recipe'\}/, 'Recipe-backed items must not allow a direct stock link to be added and double-deplete stock.')
assert.match(read('src/renderer/src/components/hospitality-pos/HposMenu.jsx'), /window\.api\?\.inventory\?\.getItems/, 'Menu stock links must load the authoritative inventory catalogue.')
assert.match(restaurantRecipes, /Waste %/, 'Recipe ingredients must clearly label the optional waste percentage field.')
assert.match(restaurantRecipes, /Quantity per serving/, 'Recipe ingredients must clearly label the quantity field.')
assert.match(restaurantWorkspaceStyles, /backdrop-filter: none/, 'Restaurant modal backdrops must avoid Electron blur hit-testing failures.')
assert.match(terminal, /const tillMenuItems = useMemo/, 'Till must maintain an active, non-archived menu catalogue.')
assert.match(terminal, /menuItems\.filter\(\(item\) => !item\.archived_at\)/, 'Archived menu items must be excluded from Till.')
assert.match(terminal, /Stock setup required/, 'Till must explain when a disabled item needs manager stock setup rather than being sold out.')
assert.match(terminal, /window\.api\?\.pos\?\.getRecipes/, 'Till must identify recipe-backed items before showing a stock-setup warning.')
assert.match(menuStockReadiness, /_pos_menu_item_has_stock_recipe/, 'Menu availability must recognise a recipe with stock ingredients.')
assert.match(menuStockReadiness, /pos_order_item_stock_readiness/, 'Sales must reject menu items that bypass stock readiness.')
assert.match(menuStockReadiness, /set is_available = false/, 'Existing untracked sellable items must become repairable drafts.')
assert.match(recipeMovementRepair, /insert into public\.inventory_movements/, 'Recipe sales must be recorded in the standard inventory ledger.')
assert.match(recipeMovementRepair, /Order line was not found for recipe stock depletion/, 'Recipe depletion must resolve an authoritative order-line id for idempotency.')
assert.match(stocktakeLedgerRepair, /inventory_stocktakes_lodge_scope_select/, 'Stocktake drafts must be readable by their restaurant operators.')
assert.match(stocktakeLedgerRepair, /inventory_stocktake_lines_lodge_scope_select/, 'Stocktake count lines must be readable by their restaurant operators.')
assert.match(stocktakeLedgerRepair, /stocktake_adjustment/, 'Posting a physical count must create an audited inventory movement.')
assert.match(restaurantStock, /window\.api\.inventory\.adjustStock/, 'Stock control adjustments must use the authoritative inventory contract.')
assert.match(restaurantStock, /window\.api\.inventory\.getMovements/, 'Stock control must expose the inventory movement ledger.')
assert.match(restaurantStock, /type="date"/, 'Movement ledger must provide a date filter.')
assert.match(restaurantStock, /start_date: selectedMovementDate/, 'Movement ledger must query its selected date rather than only showing an undated recent list.')
assert.match(restaurantStock, /window\.api\.inventory\.createStocktake/, 'Stock control must start authoritative stocktakes.')
assert.match(restaurantStock, /window\.api\.inventory\.saveStocktakeCounts/, 'Stocktake counts must use the authoritative stocktake contract.')
assert.match(restaurantStock, /window\.api\.inventory\.postStocktake/, 'Posted stocktakes must use the authoritative stocktake contract.')
assert.match(restaurantStock, /window\.api\.inventory\.updateItem/, 'Inventory Control must let managers maintain reorder and catalogue details.')
assert.match(restaurantStock, /Add inventory item/, 'Inventory Control must be the manager location for creating stock items.')
assert.match(restaurantStock, /canAccessCapability\(access, 'inventory\.manage'\)/, 'Inventory mutations must be hidden from view-only staff.')
assert.match(quickStock, /Service stock view/, 'Sidebar Stock must identify its fast service purpose.')
assert.match(quickStock, /navigate\('\/restaurant\/inventory'\)/, 'Sidebar Stock must route manager work to Inventory Control.')
assert.doesNotMatch(quickStock, /Add Item|Add stock item|createItem/, 'Sidebar Stock must not allow active service staff to create inventory records.')
assert.match(quickStock, /Needs attention/, 'Sidebar Stock must make low-stock decisions visually obvious.')
assert.match(purchaseSuggestions, /Each purchase order must have one supplier/, 'Purchase Suggestions must prevent mixed-supplier purchase orders.')
assert.match(purchaseSuggestions, /Supplier setup needed/, 'Purchase Suggestions must explain how to repair an item with no preferred supplier.')
assert.match(purchaseSuggestions, /setPreferredSupplierForInventoryItem/, 'Purchase Suggestions must allow a manager to set a preferred supplier without leaving the workflow.')
assert.match(purchaseSuggestionSupplierAssignment, /set_restaurant_preferred_supplier_item/, 'Preferred supplier assignment must be enforced by an authoritative database function.')
assert.match(purchaseSuggestionSupplierAssignment, /Receiving proves this supplier can provide this item/, 'Receiving a PO must retain the supplier relationship for future suggestions.')
assert.match(purchaseOrderQuantityGuardrails, /current_stock, 0\) < coalesce\(ii\.reorder_level/, 'Items exactly at reorder level must not create a zero-quantity suggestion.')
assert.match(purchaseOrderQuantityGuardrails, /v_quantity <= 0/, 'Database purchasing guardrails must reject a zero-quantity order line.')
assert.match(purchaseOrderQuantityGuardrails, /update_purchase_order_draft/, 'Draft purchase orders must be repairable before approval.')
assert.match(read('src/renderer/src/components/restaurant/RestaurantPurchasing.jsx'), /Edit draft/, 'Purchasing must let an operator correct a draft PO before approval.')
assert.match(read('src/renderer/src/components/restaurant/RestaurantPurchasing.jsx'), /Download PDF/, 'Purchasing must let operators save a supplier-ready purchase order PDF.')
assert.match(read('src/renderer/src/components/restaurant/RestaurantPurchasing.jsx'), /Email supplier/, 'Purchasing must support sending an approved purchase order to its supplier.')
assert.match(read('src/main/index.js'), /pos:sendPurchaseOrderEmail/, 'Purchase order email must remain a main-process, capability-gated action.')
assert.match(inventoryLotActorGuard, /public\.app_current_user_id\(\)/, 'Inventory lot receipt must use the desktop canonical business actor, not auth.uid().')
assert.match(inventoryLotActorGuard, /Your staff session could not be verified/, 'Inventory lots must provide an actionable recovery message when the actor is unavailable.')
assert.match(inventoryLotActorGuard, /ii\.id = v_inventory_item_id and ii\.lodge_id = v_lodge_id/, 'Inventory lot registration must validate the stock item belongs to the current business.')
assert.match(inventoryLots, /recordInventoryLot/, 'Lots and expiry must retain the authoritative lot recording contract.')
assert.match(inventoryLots, /Correct expiry/, 'Expiry watch must let a manager correct a mistyped expiry date.')
assert.match(inventoryLots, /Reason for correction/, 'Expiry corrections must require an operator reason.')
assert.match(inventoryLotExpiryCorrections, /restaurant_inventory_lot_expiry_corrections/, 'Expiry corrections must keep an authoritative audit trail.')
assert.match(inventoryLotExpiryCorrections, /for update/, 'Expiry correction must lock its lot row before writing the correction.')
assert.match(inventoryLots, /Expires today/, 'Expiry watch must make same-day expiry visibly prominent.')
assert.match(inventoryLots, /Write off expired lot/, 'Expiry watch must expose a manager-confirmed expired lot write-off.')
assert.match(inventoryLots, /itemNames\.get\(row\.inventory_item_id\)/, 'Expiry watch must resolve each lot to its inventory item name.')
assert.match(inventoryLots, /Enter the reason for this write-off/, 'Expired-lot write-offs must explain missing required audit details in the dialog.')
assert.match(expiredLotWriteoff, /write_off_expired_restaurant_inventory_lot/, 'Expired-lot write-off must use an authoritative database function.')
assert.match(expiredLotWriteoff, /inventory_movements/, 'Expired-lot write-off must create an inventory movement ledger entry.')
assert.match(expiredLotWriteoff, /idempotency_key/, 'Expired-lot write-off must be safe to retry.')
assert.match(restaurantShiftStaffGuard, /staff_user_id/, 'Restaurant shifts must reference a real staff account.')
assert.match(restaurantShiftStaffGuard, /restaurant_shifts_active_staff_user_unique/, 'Restaurant shifts must prevent duplicate active shifts for a staff member.')
assert.match(restaurantShiftStaffGuard, /clocked_in_by/, 'Restaurant shift clock-ins must retain the acting manager for audit.')
assert.match(restaurantShiftStaffGuard, /clocked_out_by/, 'Restaurant shift clock-outs must retain the acting manager for audit.')
assert.match(restaurantShiftStaffGuard, /idempotency_key/, 'Restaurant shift clock-ins must be retry-safe.')
assert.match(read('src/renderer/src/components/restaurant/RestaurantShifts.jsx'), /window\.api\.pos\.getStaff\(\)/, 'Restaurant shifts must load the active staff roster through the Restaurant POS contract.')
assert.match(read('src/renderer/src/components/restaurant/RestaurantGrowthControls.jsx'), /Choose active staff member/, 'Tip payouts must select from the active staff roster.')
assert.match(read('src/renderer/src/components/restaurant/RestaurantGrowthControls.jsx'), /Recent payouts/, 'Tip payouts must display recent payout history.')
assert.match(restaurantTipPayoutStaffGuard, /public\.app_current_user_id\(\)/, 'Tip payouts must retain the canonical approving staff identity.')
assert.match(restaurantTipPayoutStaffGuard, /get_restaurant_tip_payouts/, 'Tip payout history must use an authoritative server read path.')
assert.match(restaurantGuardRepair, /WHERE lodge_id = p_lodge_id/, 'Restaurant guards must look up settings by the company lodge_id, not the settings-row ID.')

assert.match(layout, /hpos-primary-rail/, 'Daily service navigation must stay persistently visible.')
assert.ok(barModeProfile.includes("{ route: '/hpos/menu', label: 'Menu', iconKey: 'menu'"), 'Restaurant operators must have always-visible menu access during service.')
assert.match(layout, /navigate\('\/hpos\/manage'\)/, 'Secondary tools must open in a full manager workspace.')
assert.match(layout, /canAccessCapability/, 'Primary navigation must respect role capabilities.')
assert.match(manageHub, /getHposMoreItems/, 'The manager hub must use the shared product navigation profile.')
assert.match(manageHub, /canAccessCapability/, 'The manager hub must filter tools by role capability.')
assert.match(manageHub, /Manager workspace/, 'The manager workspace must identify itself clearly.')
assert.match(manageHub, /Run service/, 'Manage must present consolidated restaurant service operations.')
assert.match(manageHub, /Money & oversight/, 'Manage must give financial accountability its own top-level grouping.')
assert.ok(barModeProfile.includes("{ route: '/restaurant/inventory', label: 'Inventory control'"), 'Restaurant inventory control must have one visible operational entry point.')
for (const route of ['floor-workspace', 'kitchen-workspace', 'menu-production', 'inventory', 'team-workspace', 'finance-close', 'control-workspace']) {
  assert.match(manageHub, new RegExp(`/restaurant/${route.replace('-', '\\-')}`), `${route} must be a consolidated Manage workspace.`)
}
assert.doesNotMatch(manageHub, /restaurant-operations/, 'Manage must not present a second grid of duplicate restaurant pages.')
assert.doesNotMatch(`${terminal}\n${cashClose}\n${manageHub}\n${barModeProfile}`, /Advanced POS/, 'A second advanced POS destination must not be exposed.')
assert.match(hposStyles, /linear-gradient\(180deg, #2f222a 0%, #211920 100%\)/, 'The service rail must use the dimensional restaurant navigation treatment.')
assert.match(hposStyles, /\.hpos-money-hero/, 'Money pages must use the restaurant-native layered finance surface.')
assert.match(hposStyles, /\.hpos-money-kpi/, 'Money KPIs must have their own dimensional visual system.')
assert.match(reports, /hpos-money-hero/, 'Restaurant reports must use the modern Money composition.')
assert.match(expenses, /hpos-money-ledger/, 'Restaurant expenses must use the modern ledger composition.')
assert.doesNotMatch(`${reports}\n${expenses}\n${cashClose}`, /#4d835d|#386b49|rgba\(34,\s*197,\s*94/, 'Restaurant Money surfaces must not regress to the inherited green palette.')
assert.match(barModeProfile, /label: 'Cash & close', iconKey: 'cash'/, 'Cash and close must remain a primary action.')
assert.match(barModeProfile, /route: '\/staff', label: 'Staff management'/, 'Restaurant Manage must surface staff-account setup for roster-based shifts.')
assert.match(accessControl, /'pos\.cashup': 'Open shifts and reconcile cash-up'/, 'Cash-up must be a real capability, not a dead UI permission.')

assert.match(login, /getProductDefinition\(getRuntimeProductId\(\)\)/, 'Sign-in must render the compiled product identity.')
assert.match(login, /BUILD_PRODUCT\.brandName/, 'The Restaurant build must render its compiled Tsa Bonno sign-in identity.')
assert.match(restaurantWorkspace, /import HposMenu from '\.\.\/hospitality-pos\/HposMenu'/, 'The consolidated Menu workspace must reuse the tested HPOS menu screen.')
assert.doesNotMatch(restaurantWorkspace, /import RestaurantMenu from/, 'The manager Menu workspace must not retain a second menu implementation.')
assert.match(restaurantWorkspace, /const WORKSPACE_PRESENTATION =/, 'Canonical restaurant workspaces must share an explicit Restaurant and Bar presentation system.')
assert.match(restaurantWorkspace, /Stock, purchasing & control/, 'Inventory workspace navigation must use Restaurant and Bar operations language.')
assert.match(restaurantWorkspace, /!isInventoryWorkspace && <RestaurantPageGuide/, 'Inventory tabs must not render the inherited white workspace guide above their native dashboard headers.')
assert.match(restaurantWorkspace, /bg-\[linear-gradient\(135deg,#261b23_0%,#4b2e38_58%,#764335_100%\)\]/, 'Every consolidated restaurant workspace must use the native dark service header.')
assert.match(restaurantWorkspace, /role="tablist"/, 'Workspace navigation must expose tab semantics to assistive technology.')
assert.match(restaurantPageGuide, /Next move:/, 'Workspace guidance must be a compact operational next-move cue.')
assert.match(read('src/renderer/src/components/restaurant/RestaurantReservations.jsx'), /restaurant-reservation-hero-actions/, 'Reservations must provide dedicated top action controls.')
assert.match(read('src/renderer/src/components/restaurant/RestaurantReservations.jsx'), /restaurant-reservation-action is-confirm/, 'Reservation confirmation must use a visible action button.')
assert.match(read('src/renderer/src/components/restaurant/RestaurantReservations.jsx'), /restaurant-reservation-action is-cancel/, 'Reservation cancellation must use a visible action button.')
assert.match(restaurantWorkspaceStyles, /restaurant-reservation-action/, 'Reservation action buttons must have a dedicated visual treatment.')

for (const label of ['Reservations', 'Recipes & costing', 'Purchasing', 'Daily close', 'Combos', 'Prep batches', 'Recipe variance', 'Analytics', 'Purchase suggestions', 'Staff performance', 'Owner digest']) {
  assert.match(restaurantWorkspace, new RegExp(label.replace(/[&]/g, '\\&'), 'i'), `${label} must remain discoverable inside a canonical restaurant workspace.`)
}

for (const component of ['HposFloorPlan', 'HposKitchen', 'HposMenu', 'HposStock', 'HposTeam', 'HposCashClose', 'HposCustomers', 'HposControl', 'HposManageHub']) {
  assert.match(app, new RegExp(`<Lazy><${component}`), `${component} must be reachable through the restaurant shell.`)
}

for (const [route, workspace, tab] of [
  ['recipes', 'menu', 'recipes'], ['purchasing', 'stock', 'purchasing'],
  ['reservations', 'floor', 'reservations'], ['combos', 'menu', 'combos'], ['recipe-variance', 'menu', 'variance'],
  ['staff-performance', 'team', 'performance'], ['prep-batches', 'menu', 'prep'], ['kitchen-analytics', 'kitchen', 'analytics'],
  ['purchase-suggestions', 'stock', 'suggestions'], ['stations', 'kitchen', 'stations'],
  ['lots-expiry', 'stock', 'lots']
]) {
  const escapedRoute = route.replace('-', '\\-')
  assert.match(app, new RegExp(`path="restaurant/${escapedRoute}"[^\\n]*RestaurantWorkspace workspace="${workspace}" defaultTab="${tab}"`), `restaurant/${route} must open in the unified restaurant workspace.`)
}

for (const [route, workspace, tab] of [
  ['floor-workspace', 'floor', 'tables'], ['kitchen-workspace', 'kitchen', 'live'], ['menu-production', 'menu', 'menu'],
  ['team-workspace', 'team', 'shifts'], ['finance-close', 'finance', 'overview'], ['control-workspace', 'control', 'checklists']
]) {
  const escapedRoute = route.replace('-', '\\-')
  assert.match(app, new RegExp(`path="restaurant/${escapedRoute}"[^\\n]*RestaurantWorkspace workspace="${workspace}" defaultTab="${tab}"`), `restaurant/${route} must open its consolidated manager workspace.`)
}

for (const [route, destination] of [
  ['cash-close', '/restaurant/finance-close?tab=cashups'], ['daily-close', '/restaurant/finance-close?tab=daily-close'],
  ['owner-digest', '/restaurant/finance-close?tab=owner-review'], ['tips', '/restaurant/finance-close?tab=tips'],
  ['settlements', '/restaurant/finance-close?tab=settlements'], ['feedback-deposits', '/restaurant/finance-close?tab=customer-funds'],
  ['gift-cards-policies', '/restaurant/finance-close?tab=customer-funds']
]) {
  const escapedRoute = route.replace('-', '\\-')
  assert.match(app, new RegExp(`path="restaurant/${escapedRoute}"[^\\n]*Navigate to="${destination.replace(/[?]/g, '\\?')}"`), `restaurant/${route} must preserve its legacy link through the Finance workspace.`)
}

console.log('Restaurant HPOS service contract checks passed.')
