import { useCallback, useEffect, useState } from 'react'
import { Calculator, Check, Download, Printer, RefreshCw, Send, Settings2, Users } from 'lucide-react'
import { useAccess, useSettings } from '../../app-context'
import { canAccessCapability } from '../../../../shared/accessControl'
import { AccountingButton, AccountingLoading, AccountingNotice, AccountingPage, AccountingPanel, EmptyState, accountingInvoke, inputClass, labelClass, money, today, unwrap } from './RestaurantAccountingUi'

const currentMonth=()=>({startDate:`${today().slice(0,7)}-01`,endDate:new Date(Number(today().slice(0,4)),Number(today().slice(5,7)),0).toISOString().slice(0,10)})
const csvCell=v=>`"${String(v??'').replaceAll('"','""')}"`
function downloadPayments(payments,period){const headers=['staff_user_id','staff_name','amount','currency','payment_reference','bank_account_name','bank_account_number','bank_branch_code'];const csv=[headers.join(','),...payments.map(p=>headers.map(h=>csvCell(p[h])).join(','))].join('\r\n');const url=URL.createObjectURL(new Blob([csv],{type:'text/csv'}));const a=document.createElement('a');a.href=url;a.download=`payroll-payment-export-${period?.name||'period'}.csv`;a.click();URL.revokeObjectURL(url)}
const html=v=>String(v??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]))
function printPayslip(record,period,businessName){const popup=window.open('','_blank','noopener,noreferrer,width=820,height=900');if(!popup)return;const row=(label,value)=>`<tr><th>${html(label)}</th><td>${html(value)}</td></tr>`;popup.document.write(`<!doctype html><html><head><title>Payslip — ${html(record.staff_name)}</title><style>body{font:14px system-ui;color:#17202a;margin:40px}header{border-bottom:3px solid #17613f;padding-bottom:18px;margin-bottom:24px}h1{margin:0}small{color:#64748b}table{width:100%;border-collapse:collapse;margin-top:20px}th,td{padding:10px;border-bottom:1px solid #e2e8f0;text-align:left}th{width:55%;color:#475569}.net{font-size:18px;font-weight:800}.foot{margin-top:28px;padding-top:14px;border-top:1px solid #cbd5e1;font-size:11px;color:#64748b}@media print{button{display:none}}</style></head><body><header><small>CONFIDENTIAL PAYSLIP</small><h1>${html(businessName||'Business')}</h1><p>${html(period?.name||'Pay period')} · ${html(period?.start_date||'')} to ${html(period?.end_date||'')}</p></header><h2>${html(record.staff_name||'Employee')}</h2><table>${row('Regular hours',record.regular_hours)}${row('Overtime hours',record.overtime_hours)}${row('Gross pay',money(record.gross_pay))}${row('Total deductions',money(record.total_deductions))}${row('Net pay',money(record.net_pay))}</table><p class="foot">Calculation snapshot: ${html(record.snapshot_hash||'Unavailable')}<br>This payslip reports an approved calculation snapshot. It is not proof that a bank payment has settled.</p><button onclick="window.print()">Print / save PDF</button></body></html>`);popup.document.close()}

export default function RestaurantPayroll(){
 const access=useAccess(),canManage=canAccessCapability(access,'accounting.payroll_manage')
 const {settings}=useSettings()
 const [accounts,setAccounts]=useState([]),[data,setData]=useState({employees:[],periods:[],configurations:[],terms:[],time_inputs:[],gl_settings:null}),[periodId,setPeriodId]=useState(''),[records,setRecords]=useState([])
 const month=currentMonth()
 const [terms,setTerms]=useState({staffUserId:'',effectiveFrom:month.startDate,effectiveTo:'',payType:'salary',monthlySalary:'',hourlyRate:'',overtimeMultiplier:'1.5',standardMonthlyHours:'173.33',paymentReference:'',bankAccountName:'',bankAccountNumber:'',bankBranchCode:''})
 const [config,setConfig]=useState({jurisdictionCode:'BW',ruleVersion:'',effectiveFrom:month.startDate,effectiveTo:'',taxBrackets:'[{"from":0,"to":"","rate":0}]',socialSecurityRate:'0',pensionRate:'0',healthAmount:'0',currency:'BWP'})
 const [period,setPeriod]=useState({name:today().slice(0,7),startDate:month.startDate,endDate:month.endDate,configurationId:''})
 const [time,setTime]=useState({periodId:'',staffUserId:'',regularHours:'',overtimeHours:'0',sourceReference:''})
 const [gl,setGl]=useState({payrollExpenseAccountId:'',netPayableAccountId:'',taxPayableAccountId:'',deductionsPayableAccountId:''})
 const [loading,setLoading]=useState(true),[busy,setBusy]=useState(''),[error,setError]=useState(''),[notice,setNotice]=useState('')
 const load=useCallback(async()=>{setLoading(true);setError('');try{const[w,a]=await Promise.all([accountingInvoke('getPayroll'),accountingInvoke('getAccounts')]);const next=unwrap(w,{employees:[],periods:[],configurations:[],terms:[],time_inputs:[],gl_settings:null});setData(next);setAccounts(unwrap(a,[]));if(next.gl_settings)setGl({payrollExpenseAccountId:next.gl_settings.payroll_expense_account_id||'',netPayableAccountId:next.gl_settings.net_payable_account_id||'',taxPayableAccountId:next.gl_settings.tax_payable_account_id||'',deductionsPayableAccountId:next.gl_settings.deductions_payable_account_id||''})}catch(e){setError(e.message)}finally{setLoading(false)}},[])
 useEffect(()=>{load()},[load])
 useEffect(()=>{if(!periodId){setRecords([]);return}accountingInvoke('getPayrollRecords',periodId).then(r=>setRecords(unwrap(r,[]))).catch(e=>setError(e.message))},[periodId])
 const employeeName=id=>data.employees.find(e=>e.id===id)?.name||id
 const submit=async(kind,payload)=>{setBusy(kind);setError('');setNotice('');try{if(kind==='terms')await accountingInvoke('setPayrollTerms',{...terms,monthlySalary:Number(terms.monthlySalary||0),hourlyRate:Number(terms.hourlyRate||0),overtimeMultiplier:Number(terms.overtimeMultiplier),standardMonthlyHours:Number(terms.standardMonthlyHours)});if(kind==='config'){let brackets;try{brackets=JSON.parse(config.taxBrackets)}catch{throw new Error('Tax brackets must be valid JSON')};await accountingInvoke('setPayrollConfig',{...config,taxBrackets:brackets,socialSecurityRate:Number(config.socialSecurityRate),pensionRate:Number(config.pensionRate),healthAmount:Number(config.healthAmount)})}if(kind==='period')await accountingInvoke('createPayPeriod',period);if(kind==='time')await accountingInvoke('setPayrollTime',{...time,regularHours:Number(time.regularHours||0),overtimeHours:Number(time.overtimeHours||0)});if(kind==='gl')await accountingInvoke('setPayrollGl',gl);setNotice({terms:'Effective-dated employment and private bank terms saved.',config:'Versioned statutory configuration saved.',period:'Draft pay period created.',time:'Separate regular and overtime input saved for independent approval.',gl:'Payroll ledger control accounts saved.'}[kind]);await load()}catch(e){setError(e.message)}finally{setBusy('')}}
 const act=async(kind,id)=>{setBusy(`${kind}:${id}`);setError('');try{if(kind==='approve-time')await accountingInvoke('approvePayrollTime',id);if(kind==='calculate')await accountingInvoke('calculatePayroll',id);if(kind==='approve')await accountingInvoke('approvePayroll',id);if(kind==='post')await accountingInvoke('postPayroll',id);if(kind==='export'){const r=await accountingInvoke('exportPayroll',id);downloadPayments(r?.data?.payments||[],data.periods.find(p=>p.id===id));setNotice('Payment instructions exported. Payroll remains explicitly not paid until an external bank settlement is independently confirmed.')}else setNotice({ 'approve-time':'Time input independently approved.',calculate:'Payroll calculated into immutable employee snapshots.',approve:'Payroll run independently approved.',post:'Approved payroll posted as a balanced ledger journal; it remains unpaid.'}[kind]);await load();if(periodId===id){const rr=await accountingInvoke('getPayrollRecords',id);setRecords(unwrap(rr,[]))}}catch(e){setError(e.message)}finally{setBusy('')}}
 const expenses=accounts.filter(a=>a.is_active&&a.account_type==='expense'),liabilities=accounts.filter(a=>a.is_active&&a.account_type==='liability')
 return <AccountingPage title="Payroll" description="Private, effective-dated payroll terms; approved time inputs; versioned statutory rules; immutable calculations; maker-checker approval; ledger posting; and explicit unpaid payment export." actions={<AccountingButton tone="secondary" onClick={load}><RefreshCw size={15}/>Refresh</AccountingButton>}>
  <AccountingNotice type="warning">Payroll access is separate from generic Accounting. Exporting payment instructions does not mark staff paid and does not initiate a bank payment.</AccountingNotice>{error&&<AccountingNotice type="error">{error}</AccountingNotice>}{notice&&<AccountingNotice type="success">{notice}</AccountingNotice>}
  {loading?<AccountingLoading/>:<div className="space-y-4">
   <AccountingPanel title="Pay periods">{data.periods.length===0?<EmptyState title="No pay periods"/>:<div className="overflow-x-auto"><table className="w-full text-sm"><thead><tr className="border-b text-left text-xs text-slate-500"><th className="py-2">Period</th><th>Status</th><th>Snapshot / journal</th><th/></tr></thead><tbody>{data.periods.map(p=><tr key={p.id} className="border-b border-slate-100"><td className="py-2"><button className="text-left font-bold text-emerald-800" onClick={()=>setPeriodId(p.id)}>{p.name}</button><br/><small>{p.start_date}–{p.end_date}</small></td><td>{p.status}{p.payment_exported_at&&<><br/><small>Instructions exported</small></>}</td><td className="max-w-xs truncate text-xs">{p.calculation_snapshot_hash||'Not calculated'}{p.journal_entry_id&&<><br/>Journal {p.journal_entry_id}</>}</td><td className="text-right"><div className="flex flex-wrap justify-end gap-2">{canManage&&p.status==='draft'&&<AccountingButton onClick={()=>act('calculate',p.id)} busy={busy===`calculate:${p.id}`}><Calculator size={13}/>Calculate</AccountingButton>}{canManage&&p.status==='processing'&&<AccountingButton onClick={()=>act('approve',p.id)} busy={busy===`approve:${p.id}`}><Check size={13}/>Approve</AccountingButton>}{canManage&&p.status==='approved'&&!p.journal_entry_id&&<AccountingButton onClick={()=>act('post',p.id)} busy={busy===`post:${p.id}`}><Send size={13}/>Post GL</AccountingButton>}{canManage&&p.status==='approved'&&<AccountingButton tone="amber" onClick={()=>act('export',p.id)} busy={busy===`export:${p.id}`}><Download size={13}/>Export unpaid file</AccountingButton>}</div></td></tr>)}</tbody></table></div>}</AccountingPanel>
   {periodId&&<AccountingPanel title="Employee calculation snapshots">{records.length===0?<EmptyState title="No calculated records for this period"/>:<div className="overflow-x-auto"><table className="w-full text-sm"><thead><tr className="border-b text-left text-xs text-slate-500"><th className="py-2">Employee</th><th className="text-right">Regular h</th><th className="text-right">Overtime h</th><th className="text-right">Gross</th><th className="text-right">Deductions</th><th className="text-right">Net</th><th/></tr></thead><tbody>{records.map(r=><tr key={r.id} className="border-b border-slate-100"><td className="py-2"><b>{r.staff_name}</b><br/><small className="font-mono">{r.snapshot_hash?.slice(0,12)}…</small></td><td className="text-right">{r.regular_hours}</td><td className="text-right">{r.overtime_hours}</td><td className="text-right">{money(r.gross_pay)}</td><td className="text-right">{money(r.total_deductions)}</td><td className="text-right font-bold">{money(r.net_pay)}</td><td className="pl-3 text-right"><AccountingButton tone="secondary" onClick={()=>printPayslip(r,data.periods.find(p=>p.id===periodId),settings?.company_name||settings?.lodge_name)}><Printer size={13}/>Payslip</AccountingButton></td></tr>)}</tbody></table></div>}</AccountingPanel>}
   <AccountingPanel title="Time inputs">{data.time_inputs.length===0?<EmptyState title="No time inputs"/>:<div className="space-y-2">{data.time_inputs.map(t=><div key={t.id} className="flex flex-wrap items-center justify-between gap-3 rounded-xl border border-slate-200 p-3 text-sm"><span><b>{employeeName(t.staff_user_id)}</b> · regular {t.regular_hours}h · overtime {t.overtime_hours}h · {t.source_reference}<br/><small>{t.approved_at?'Approved':'Awaiting independent approval'}</small></span>{canManage&&!t.approved_at&&<AccountingButton onClick={()=>act('approve-time',t.id)} busy={busy===`approve-time:${t.id}`}><Check size={13}/>Approve time</AccountingButton>}</div>)}</div>}</AccountingPanel>
   {canManage&&<div className="grid gap-4 xl:grid-cols-2">
    <AccountingPanel title="Employment and payment terms" description="Creates a new non-overlapping effective version. Bank details never appear in the read model."><form className="grid gap-3 sm:grid-cols-2" onSubmit={e=>{e.preventDefault();submit('terms')}}><label className={labelClass}>Employee<select required className={inputClass} value={terms.staffUserId} onChange={e=>setTerms({...terms,staffUserId:e.target.value})}><option value="">Select</option>{data.employees.map(x=><option key={x.id} value={x.id}>{x.name}</option>)}</select></label><label className={labelClass}>Pay type<select className={inputClass} value={terms.payType} onChange={e=>setTerms({...terms,payType:e.target.value})}><option value="salary">Monthly salary</option><option value="hourly">Hourly</option></select></label><label className={labelClass}>Effective from<input required type="date" className={inputClass} value={terms.effectiveFrom} onChange={e=>setTerms({...terms,effectiveFrom:e.target.value})}/></label><label className={labelClass}>Effective to<input type="date" className={inputClass} value={terms.effectiveTo} onChange={e=>setTerms({...terms,effectiveTo:e.target.value})}/></label>{terms.payType==='salary'?<label className={labelClass}>Monthly salary<input required type="number" min="0.01" step="0.01" className={inputClass} value={terms.monthlySalary} onChange={e=>setTerms({...terms,monthlySalary:e.target.value})}/></label>:<label className={labelClass}>Hourly rate<input required type="number" min="0.01" step="0.01" className={inputClass} value={terms.hourlyRate} onChange={e=>setTerms({...terms,hourlyRate:e.target.value})}/></label>}<label className={labelClass}>Overtime multiplier<input required type="number" min="1" step="0.01" className={inputClass} value={terms.overtimeMultiplier} onChange={e=>setTerms({...terms,overtimeMultiplier:e.target.value})}/></label><label className={labelClass}>Bank account name<input className={inputClass} value={terms.bankAccountName} onChange={e=>setTerms({...terms,bankAccountName:e.target.value})}/></label><label className={labelClass}>Bank account number<input className={inputClass} value={terms.bankAccountNumber} onChange={e=>setTerms({...terms,bankAccountNumber:e.target.value})}/></label><label className={labelClass}>Bank branch code<input className={inputClass} value={terms.bankBranchCode} onChange={e=>setTerms({...terms,bankBranchCode:e.target.value})}/></label><label className={labelClass}>Payment reference<input className={inputClass} value={terms.paymentReference} onChange={e=>setTerms({...terms,paymentReference:e.target.value})}/></label><AccountingButton busy={busy==='terms'}><Users size={15}/>Save new terms</AccountingButton></form></AccountingPanel>
    <AccountingPanel title="Versioned statutory configuration"><form className="space-y-3" onSubmit={e=>{e.preventDefault();submit('config')}}><div className="grid gap-3 sm:grid-cols-2"><label className={labelClass}>Jurisdiction<input required className={inputClass} value={config.jurisdictionCode} onChange={e=>setConfig({...config,jurisdictionCode:e.target.value})}/></label><label className={labelClass}>Rule version<input required className={inputClass} value={config.ruleVersion} onChange={e=>setConfig({...config,ruleVersion:e.target.value})}/></label><label className={labelClass}>Effective from<input required type="date" className={inputClass} value={config.effectiveFrom} onChange={e=>setConfig({...config,effectiveFrom:e.target.value})}/></label><label className={labelClass}>Effective to<input type="date" className={inputClass} value={config.effectiveTo} onChange={e=>setConfig({...config,effectiveTo:e.target.value})}/></label></div><label className={labelClass}>Progressive tax brackets JSON<textarea required rows="4" className={inputClass} value={config.taxBrackets} onChange={e=>setConfig({...config,taxBrackets:e.target.value})}/></label><div className="grid gap-3 sm:grid-cols-3"><label className={labelClass}>Social security %<input type="number" min="0" step="0.01" className={inputClass} value={config.socialSecurityRate} onChange={e=>setConfig({...config,socialSecurityRate:e.target.value})}/></label><label className={labelClass}>Pension %<input type="number" min="0" step="0.01" className={inputClass} value={config.pensionRate} onChange={e=>setConfig({...config,pensionRate:e.target.value})}/></label><label className={labelClass}>Health amount<input type="number" min="0" step="0.01" className={inputClass} value={config.healthAmount} onChange={e=>setConfig({...config,healthAmount:e.target.value})}/></label></div><AccountingButton busy={busy==='config'}><Settings2 size={15}/>Save rule version</AccountingButton></form></AccountingPanel>
    <AccountingPanel title="Create monthly pay period"><form className="space-y-3" onSubmit={e=>{e.preventDefault();submit('period')}}><label className={labelClass}>Name<input required className={inputClass} value={period.name} onChange={e=>setPeriod({...period,name:e.target.value})}/></label><div className="grid gap-3 sm:grid-cols-2"><label className={labelClass}>Start<input required type="date" className={inputClass} value={period.startDate} onChange={e=>setPeriod({...period,startDate:e.target.value})}/></label><label className={labelClass}>End<input required type="date" className={inputClass} value={period.endDate} onChange={e=>setPeriod({...period,endDate:e.target.value})}/></label></div><label className={labelClass}>Statutory configuration<select required className={inputClass} value={period.configurationId} onChange={e=>setPeriod({...period,configurationId:e.target.value})}><option value="">Select</option>{data.configurations.map(c=><option key={c.id} value={c.id}>{c.rule_version} · {c.effective_from}</option>)}</select></label><AccountingButton busy={busy==='period'}>Create draft period</AccountingButton></form></AccountingPanel>
    <AccountingPanel title="Enter regular and overtime hours"><form className="space-y-3" onSubmit={e=>{e.preventDefault();submit('time')}}><label className={labelClass}>Draft period<select required className={inputClass} value={time.periodId} onChange={e=>setTime({...time,periodId:e.target.value})}><option value="">Select</option>{data.periods.filter(p=>p.status==='draft').map(p=><option key={p.id} value={p.id}>{p.name}</option>)}</select></label><label className={labelClass}>Employee<select required className={inputClass} value={time.staffUserId} onChange={e=>setTime({...time,staffUserId:e.target.value})}><option value="">Select</option>{data.employees.map(x=><option key={x.id} value={x.id}>{x.name}</option>)}</select></label><div className="grid gap-3 sm:grid-cols-2"><label className={labelClass}>Regular hours<input required type="number" min="0" step="0.01" className={inputClass} value={time.regularHours} onChange={e=>setTime({...time,regularHours:e.target.value})}/></label><label className={labelClass}>Overtime hours<input required type="number" min="0" step="0.01" className={inputClass} value={time.overtimeHours} onChange={e=>setTime({...time,overtimeHours:e.target.value})}/></label></div><label className={labelClass}>Source reference<input required className={inputClass} placeholder="Approved timesheet or rota reference" value={time.sourceReference} onChange={e=>setTime({...time,sourceReference:e.target.value})}/></label><AccountingButton busy={busy==='time'}>Save time input</AccountingButton></form></AccountingPanel>
    <AccountingPanel title="Payroll ledger controls"><form className="space-y-3" onSubmit={e=>{e.preventDefault();submit('gl')}}><label className={labelClass}>Payroll expense<select required className={inputClass} value={gl.payrollExpenseAccountId} onChange={e=>setGl({...gl,payrollExpenseAccountId:e.target.value})}><option value="">Select</option>{expenses.map(a=><option key={a.id} value={a.id}>{a.code} — {a.name}</option>)}</select></label>{[['netPayableAccountId','Net pay payable'],['taxPayableAccountId','Tax payable'],['deductionsPayableAccountId','Other deductions payable']].map(([key,label])=><label key={key} className={labelClass}>{label}<select required className={inputClass} value={gl[key]} onChange={e=>setGl({...gl,[key]:e.target.value})}><option value="">Select</option>{liabilities.map(a=><option key={a.id} value={a.id}>{a.code} — {a.name}</option>)}</select></label>)}<AccountingButton busy={busy==='gl'}>Save ledger controls</AccountingButton></form></AccountingPanel>
   </div>}
  </div>}
 </AccountingPage>
}

