import { useCallback, useEffect, useState } from 'react'
import { Check, CreditCard, FilePlus2, RefreshCw, Send } from 'lucide-react'
import { useAccess } from '../../app-context'
import { canAccessCapability } from '../../../../shared/accessControl'
import { AccountingButton, AccountingLoading, AccountingNotice, AccountingPage, AccountingPanel, EmptyState, accountingInvoke, inputClass, labelClass, money, runIdempotent, today, unwrap } from './RestaurantAccountingUi'

const blank=()=>({supplierName:'',billNumber:'',billDate:today(),dueDate:today(),notes:'',description:'',quantity:'1',unitCost:'',taxAmount:'0',expenseAccountId:''})

export default function RestaurantAccountsPayable(){
 const access=useAccess(),canManage=canAccessCapability(access,'accounting.manage'),canPay=canAccessCapability(access,'accounting.ap_pay')
 const [accounts,setAccounts]=useState([]),[data,setData]=useState({bills:[],summary:{}}),[form,setForm]=useState(blank()),[settings,setSettings]=useState({payableAccountId:'',inputTaxAccountId:''})
 const [payment,setPayment]=useState({billId:'',paymentDate:today(),amount:'',paymentAccountId:'',reference:'',notes:''})
 const [loading,setLoading]=useState(true),[busy,setBusy]=useState(''),[error,setError]=useState(''),[notice,setNotice]=useState('')
 const load=useCallback(async()=>{setLoading(true);setError('');try{const[a,w]=await Promise.all([accountingInvoke('getAccounts'),accountingInvoke('getAp')]);setAccounts(unwrap(a,[]));setData(unwrap(w,{bills:[],summary:{}}))}catch(e){setError(e.message)}finally{setLoading(false)}},[])
 useEffect(()=>{load()},[load])
 const create=async(e)=>{e.preventDefault();setBusy('create');setError('');try{await runIdempotent(`bill:${form.supplierName}:${form.billNumber}`,operationKey=>accountingInvoke('createBill',{...form,operationKey,lines:[{description:form.description,quantity:Number(form.quantity),unit_cost:Number(form.unitCost),tax_amount:Number(form.taxAmount||0),expense_account_id:form.expenseAccountId}]}));setForm(blank());setNotice('Draft bill and its lines were created atomically. Totals were derived by the server.');await load()}catch(e2){setError(e2.message)}finally{setBusy('')}}
 const action=async(name,bill)=>{setBusy(`${name}:${bill.id}`);setError('');try{if(name==='submit')await accountingInvoke('submitBill',bill.id);else await runIdempotent(`bill-approval:${bill.id}`,key=>accountingInvoke('approveBill',bill.id,key));setNotice(name==='submit'?'Bill submitted for independent approval.':'Bill approved and accrued to the ledger.');await load()}catch(e){setError(e.message)}finally{setBusy('')}}
 const pay=async(e)=>{e.preventDefault();setBusy('pay');setError('');try{await runIdempotent(`bill-payment:${payment.billId}:${payment.reference||payment.paymentDate}`,operationKey=>accountingInvoke('payBill',{...payment,amount:Number(payment.amount),operationKey}));setPayment({billId:'',paymentDate:today(),amount:'',paymentAccountId:'',reference:'',notes:''});setNotice('Payment recorded once and posted to the ledger.');await load()}catch(e2){setError(e2.message)}finally{setBusy('')}}
 const saveSettings=async(e)=>{e.preventDefault();setBusy('settings');setError('');try{await accountingInvoke('setApSettings',settings);setNotice('AP control accounts saved.')}catch(e2){setError(e2.message)}finally{setBusy('')}}
 const liabilities=accounts.filter(a=>a.is_active&&a.account_type==='liability'),assets=accounts.filter(a=>a.is_active&&a.account_type==='asset'),expenseAccounts=accounts.filter(a=>a.is_active&&['asset','expense'].includes(a.account_type))
 return <AccountingPage title="Accounts payable" description="Capture supplier invoices atomically, accrue only after independent approval, and pay approved balances with duplicate and overpayment protection." actions={<AccountingButton tone="secondary" onClick={load}><RefreshCw size={15}/>Refresh</AccountingButton>}>
  <AccountingNotice>Bill creation, approval, and payment are separate states. The creator cannot approve the same bill, and only approved outstanding amounts can be paid.</AccountingNotice>{error&&<AccountingNotice type="error">{error}</AccountingNotice>}{notice&&<AccountingNotice type="success">{notice}</AccountingNotice>}
  {loading?<AccountingLoading/>:<div className="space-y-4">
   <div className="grid gap-3 md:grid-cols-3"><AccountingPanel title="Open bills"><b className="text-2xl">{data.summary.open_bills||0}</b></AccountingPanel><AccountingPanel title="Outstanding"><b className="text-2xl">{money(data.summary.total_outstanding)}</b></AccountingPanel><AccountingPanel title="Overdue"><b className="text-2xl text-rose-700">{money(data.summary.overdue_outstanding)}</b></AccountingPanel></div>
   <AccountingPanel title="Supplier bills">{data.bills.length===0?<EmptyState title="No supplier bills"/>:<div className="overflow-x-auto"><table className="w-full text-sm"><thead><tr className="border-b text-left text-xs text-slate-500"><th className="py-2">Supplier / invoice</th><th>Dates</th><th className="text-right">Total</th><th className="text-right">Outstanding</th><th>Status</th><th/></tr></thead><tbody>{data.bills.map(b=><tr key={b.id} className="border-b border-slate-100"><td className="py-2"><b>{b.supplier_name}</b><br/><small>{b.bill_number}</small></td><td>{b.bill_date}<br/><small>Due {b.due_date}</small></td><td className="text-right">{money(b.total)}</td><td className="text-right">{money(Number(b.total)-Number(b.amount_paid))}</td><td>{b.status}</td><td className="text-right"><div className="flex justify-end gap-2">{canManage&&b.status==='draft'&&<AccountingButton tone="secondary" busy={busy===`submit:${b.id}`} onClick={()=>action('submit',b)}><Send size={13}/>Submit</AccountingButton>}{canManage&&b.status==='submitted'&&<AccountingButton busy={busy===`approve:${b.id}`} onClick={()=>action('approve',b)}><Check size={13}/>Approve</AccountingButton>}{canPay&&['approved','partially_paid'].includes(b.status)&&<AccountingButton tone="amber" onClick={()=>setPayment({...payment,billId:b.id,amount:String(Number(b.total)-Number(b.amount_paid))})}><CreditCard size={13}/>Pay</AccountingButton>}</div></td></tr>)}</tbody></table></div>}</AccountingPanel>
   <div className="grid gap-4 xl:grid-cols-2">
    {canManage&&<div className="space-y-4"><AccountingPanel title="AP control accounts"><form className="space-y-3" onSubmit={saveSettings}><label className={labelClass}>Payable liability<select required className={inputClass} value={settings.payableAccountId} onChange={e=>setSettings({...settings,payableAccountId:e.target.value})}><option value="">Select</option>{liabilities.map(a=><option key={a.id} value={a.id}>{a.code} — {a.name}</option>)}</select></label><label className={labelClass}>Input tax asset (optional)<select className={inputClass} value={settings.inputTaxAccountId} onChange={e=>setSettings({...settings,inputTaxAccountId:e.target.value})}><option value="">None</option>{assets.map(a=><option key={a.id} value={a.id}>{a.code} — {a.name}</option>)}</select></label><AccountingButton busy={busy==='settings'}>Save controls</AccountingButton></form></AccountingPanel><AccountingPanel title="Create supplier bill"><form className="grid gap-3 sm:grid-cols-2" onSubmit={create}><label className={labelClass}>Supplier<input required className={inputClass} value={form.supplierName} onChange={e=>setForm({...form,supplierName:e.target.value})}/></label><label className={labelClass}>Invoice number<input required className={inputClass} value={form.billNumber} onChange={e=>setForm({...form,billNumber:e.target.value})}/></label><label className={labelClass}>Bill date<input required type="date" className={inputClass} value={form.billDate} onChange={e=>setForm({...form,billDate:e.target.value})}/></label><label className={labelClass}>Due date<input required type="date" className={inputClass} value={form.dueDate} onChange={e=>setForm({...form,dueDate:e.target.value})}/></label><label className={`${labelClass} sm:col-span-2`}>Line description<input required className={inputClass} value={form.description} onChange={e=>setForm({...form,description:e.target.value})}/></label><label className={labelClass}>Quantity<input required type="number" min="0.001" step="0.001" className={inputClass} value={form.quantity} onChange={e=>setForm({...form,quantity:e.target.value})}/></label><label className={labelClass}>Unit cost<input required type="number" min="0" step="0.01" className={inputClass} value={form.unitCost} onChange={e=>setForm({...form,unitCost:e.target.value})}/></label><label className={labelClass}>Tax amount<input type="number" min="0" step="0.01" className={inputClass} value={form.taxAmount} onChange={e=>setForm({...form,taxAmount:e.target.value})}/></label><label className={labelClass}>Expense / asset account<select required className={inputClass} value={form.expenseAccountId} onChange={e=>setForm({...form,expenseAccountId:e.target.value})}><option value="">Select</option>{expenseAccounts.map(a=><option key={a.id} value={a.id}>{a.code} — {a.name}</option>)}</select></label><AccountingButton busy={busy==='create'}><FilePlus2 size={15}/>Create draft</AccountingButton></form></AccountingPanel></div>}
    {canPay&&<AccountingPanel title="Record approved bill payment" description="Selecting Pay above fills the outstanding amount."><form className="space-y-3" onSubmit={pay}><label className={labelClass}>Bill<select required className={inputClass} value={payment.billId} onChange={e=>setPayment({...payment,billId:e.target.value})}><option value="">Select approved bill</option>{data.bills.filter(b=>['approved','partially_paid'].includes(b.status)).map(b=><option key={b.id} value={b.id}>{b.supplier_name} · {b.bill_number} · {money(Number(b.total)-Number(b.amount_paid))}</option>)}</select></label><label className={labelClass}>Payment date<input required type="date" className={inputClass} value={payment.paymentDate} onChange={e=>setPayment({...payment,paymentDate:e.target.value})}/></label><label className={labelClass}>Amount<input required type="number" min="0.01" step="0.01" className={inputClass} value={payment.amount} onChange={e=>setPayment({...payment,amount:e.target.value})}/></label><label className={labelClass}>Payment asset account<select required className={inputClass} value={payment.paymentAccountId} onChange={e=>setPayment({...payment,paymentAccountId:e.target.value})}><option value="">Select cash or bank</option>{assets.map(a=><option key={a.id} value={a.id}>{a.code} — {a.name}</option>)}</select></label><label className={labelClass}>Reference<input className={inputClass} value={payment.reference} onChange={e=>setPayment({...payment,reference:e.target.value})}/></label><AccountingButton busy={busy==='pay'}><CreditCard size={15}/>Record payment</AccountingButton></form></AccountingPanel>}
   </div>
  </div>}
 </AccountingPage>
}

