import { useCallback, useEffect, useMemo, useState } from 'react'
import { BookOpen, Link2, RefreshCw, RotateCcw, Send } from 'lucide-react'
import { useAccess } from '../../app-context'
import { canAccessCapability } from '../../../../shared/accessControl'
import { AccountingButton, AccountingLoading, AccountingNotice, AccountingPage, AccountingPanel, EmptyState, accountingInvoke, firstOfMonth, inputClass, labelClass, money, runIdempotent, today, unwrap } from './RestaurantAccountingUi'

const emptyJournal = () => ({ entryDate: today(), description: '', referenceNumber: '', lines: [{ accountId:'',debit:'',credit:'',memo:'' },{ accountId:'',debit:'',credit:'',memo:'' }] })

export default function RestaurantGeneralLedger() {
  const access=useAccess(), canManage=canAccessCapability(access,'accounting.manage')
  const [accounts,setAccounts]=useState([]),[workspace,setWorkspace]=useState({entries:[],trial_balance:[]}),[mappings,setMappings]=useState([])
  const [filters,setFilters]=useState({startDate:firstOfMonth(),endDate:today(),accountId:''}),[journal,setJournal]=useState(emptyJournal())
  const [mapping,setMapping]=useState({mappingType:'category',sourceKey:'',accountId:''}),[orderId,setOrderId]=useState('')
  const [loading,setLoading]=useState(true),[busy,setBusy]=useState(''),[error,setError]=useState(''),[notice,setNotice]=useState('')

  const load=useCallback(async()=>{setLoading(true);setError('');try{const [a,w,m]=await Promise.all([accountingInvoke('getAccounts'),accountingInvoke('getLedger',filters),accountingInvoke('getPosMappings')]);setAccounts(unwrap(a,[]));setWorkspace(unwrap(w,{entries:[],trial_balance:[]}));setMappings(unwrap(m,[]))}catch(e){setError(e.message)}finally{setLoading(false)}},[filters])
  useEffect(()=>{load()},[load])
  const totals=useMemo(()=>workspace.trial_balance.reduce((v,row)=>({debit:v.debit+Number(row.debit||0),credit:v.credit+Number(row.credit||0)}),{debit:0,credit:0}),[workspace])
  const journalTotals=journal.lines.reduce((v,row)=>({debit:v.debit+Number(row.debit||0),credit:v.credit+Number(row.credit||0)}),{debit:0,credit:0})
  const setLine=(index,key,value)=>setJournal({...journal,lines:journal.lines.map((line,i)=>i===index?{...line,[key]:value}:line)})
  const addLine=()=>setJournal({...journal,lines:[...journal.lines,{accountId:'',debit:'',credit:'',memo:''}]})

  const postJournal=async(e)=>{e.preventDefault();setBusy('journal');setError('');setNotice('');try{await runIdempotent(`journal:${journal.entryDate}:${journal.referenceNumber||journal.description}`,operationKey=>accountingInvoke('createJournal',{...journal,operationKey,sourceType:'manual',lines:journal.lines.map(x=>({account_id:x.accountId,debit:Number(x.debit||0),credit:Number(x.credit||0),memo:x.memo||null}))}));setJournal(emptyJournal());setNotice('Balanced journal posted. It can only be corrected by reversal.');await load()}catch(e2){setError(e2.message)}finally{setBusy('')}}
  const reverse=async(entry)=>{const reason=window.prompt('Reason for reversal (required):');if(!reason)return;setBusy(entry.id);setError('');try{await runIdempotent(`reversal:${entry.id}`,operationKey=>accountingInvoke('reverseJournal',{entryId:entry.id,reason,operationKey}));setNotice('Reversal journal posted. The original remains in the audit trail.');await load()}catch(e){setError(e.message)}finally{setBusy('')}}
  const saveMapping=async(e)=>{e.preventDefault();setBusy('mapping');setError('');try{await accountingInvoke('setPosMapping',mapping);setMapping({...mapping,sourceKey:'',accountId:''});setNotice('POS mapping saved. Future order postings use this account.');await load()}catch(e2){setError(e2.message)}finally{setBusy('')}}
  const postOrder=async(e)=>{e.preventDefault();setBusy('order');setError('');try{const result=await accountingInvoke('postPosOrder',orderId.trim());setNotice(result?.data?.replayed?'This POS order was already posted; no duplicate journal was created.':'POS order posted as one retry-safe journal.');setOrderId('');await load()}catch(e2){setError(e2.message)}finally{setBusy('')}}

  return <AccountingPage title="General ledger" description="Review immutable journals, post balanced manual entries, reverse mistakes, and post individual POS orders using explicit revenue, tender, tax, discount, and tip mappings." actions={<AccountingButton tone="secondary" onClick={load}><RefreshCw size={15}/>Refresh</AccountingButton>}>
    <AccountingNotice>Posted journals cannot be edited or deleted. Corrections create dated reversal journals, preserving the original evidence.</AccountingNotice>
    {error&&<AccountingNotice type="error">{error}</AccountingNotice>}{notice&&<AccountingNotice type="success">{notice}</AccountingNotice>}
    <AccountingPanel title="Ledger filters" className="mb-4"><div className="grid gap-3 md:grid-cols-4"><label className={labelClass}>From<input type="date" className={inputClass} value={filters.startDate} onChange={e=>setFilters({...filters,startDate:e.target.value})}/></label><label className={labelClass}>To<input type="date" className={inputClass} value={filters.endDate} onChange={e=>setFilters({...filters,endDate:e.target.value})}/></label><label className={labelClass}>Account<select className={inputClass} value={filters.accountId} onChange={e=>setFilters({...filters,accountId:e.target.value})}><option value="">All accounts</option>{accounts.map(a=><option key={a.id} value={a.id}>{a.code} — {a.name}</option>)}</select></label></div></AccountingPanel>
    {loading?<AccountingLoading/>:<div className="space-y-4">
      <AccountingPanel title="Trial balance" description={`Debits ${money(totals.debit)} · Credits ${money(totals.credit)}`}>
        {workspace.trial_balance.length===0?<EmptyState title="No posted ledger activity in this period"/>:<div className="overflow-x-auto"><table className="w-full text-sm"><thead><tr className="border-b text-left text-xs text-slate-500"><th className="py-2">Account</th><th className="text-right">Debit</th><th className="text-right">Credit</th><th className="text-right">Natural balance</th></tr></thead><tbody>{workspace.trial_balance.map(r=><tr key={r.account_id} className="border-b border-slate-100"><td className="py-2"><b>{r.code}</b> — {r.name}</td><td className="text-right">{money(r.debit)}</td><td className="text-right">{money(r.credit)}</td><td className="text-right font-bold">{money(r.balance)}</td></tr>)}</tbody></table></div>}
      </AccountingPanel>
      <AccountingPanel title="Posted journals">
        {workspace.entries.length===0?<EmptyState title="No journals found"/>:<div className="space-y-3">{workspace.entries.map(e=><article key={e.id} className="rounded-xl border border-slate-200 p-3"><div className="flex flex-wrap justify-between gap-2"><div><b>{e.entry_date} · {e.description}</b><p className="text-xs text-slate-500">{e.source_type} · {e.reference_number||'No reference'} · Key {e.posting_key}</p></div>{canManage&&!e.reversal_of&&<AccountingButton tone="secondary" busy={busy===e.id} onClick={()=>reverse(e)}><RotateCcw size={14}/>Reverse</AccountingButton>}</div><div className="mt-3 grid gap-1">{e.lines.map(line=><div key={line.id} className="grid grid-cols-[1fr_auto_auto] gap-4 text-xs"><span>{line.account_code} — {line.account_name}</span><span>D {money(line.debit)}</span><span>C {money(line.credit)}</span></div>)}</div></article>)}</div>}
      </AccountingPanel>
      {canManage&&<div className="grid gap-4 xl:grid-cols-2">
        <AccountingPanel title="Post manual journal" description="At least two lines; every line must contain exactly one positive debit or credit."><form className="space-y-3" onSubmit={postJournal}><div className="grid gap-3 sm:grid-cols-2"><label className={labelClass}>Date<input required type="date" className={inputClass} value={journal.entryDate} onChange={e=>setJournal({...journal,entryDate:e.target.value})}/></label><label className={labelClass}>Reference<input className={inputClass} value={journal.referenceNumber} onChange={e=>setJournal({...journal,referenceNumber:e.target.value})}/></label></div><label className={labelClass}>Description<input required className={inputClass} value={journal.description} onChange={e=>setJournal({...journal,description:e.target.value})}/></label>{journal.lines.map((line,i)=><div key={i} className="grid gap-2 rounded-xl bg-slate-50 p-2 sm:grid-cols-[1fr_100px_100px]"><select required className={inputClass} value={line.accountId} onChange={e=>setLine(i,'accountId',e.target.value)}><option value="">Account</option>{accounts.filter(a=>a.is_active).map(a=><option key={a.id} value={a.id}>{a.code} — {a.name}</option>)}</select><input aria-label="Debit" placeholder="Debit" type="number" min="0" step="0.01" className={inputClass} value={line.debit} onChange={e=>setLine(i,'debit',e.target.value)}/><input aria-label="Credit" placeholder="Credit" type="number" min="0" step="0.01" className={inputClass} value={line.credit} onChange={e=>setLine(i,'credit',e.target.value)}/></div>)}<div className="flex flex-wrap items-center gap-3"><AccountingButton tone="secondary" onClick={addLine}>Add line</AccountingButton><span className={`text-xs font-bold ${journalTotals.debit===journalTotals.credit&&journalTotals.debit>0?'text-emerald-700':'text-rose-700'}`}>D {money(journalTotals.debit)} · C {money(journalTotals.credit)}</span><AccountingButton busy={busy==='journal'} disabled={journalTotals.debit!==journalTotals.credit||journalTotals.debit<=0}><BookOpen size={15}/>Post journal</AccountingButton></div></form></AccountingPanel>
        <div className="space-y-4"><AccountingPanel title="POS GL mapping"><form className="grid gap-3" onSubmit={saveMapping}><label className={labelClass}>Mapping type<select className={inputClass} value={mapping.mappingType} onChange={e=>setMapping({...mapping,mappingType:e.target.value})}>{['category','tender','discount','tax','tips'].map(x=><option key={x}>{x}</option>)}</select></label><label className={labelClass}>Source key<input required className={inputClass} placeholder="e.g. food, cash, vat" value={mapping.sourceKey} onChange={e=>setMapping({...mapping,sourceKey:e.target.value})}/></label><label className={labelClass}>GL account<select required className={inputClass} value={mapping.accountId} onChange={e=>setMapping({...mapping,accountId:e.target.value})}><option value="">Select</option>{accounts.filter(a=>a.is_active).map(a=><option key={a.id} value={a.id}>{a.code} — {a.name}</option>)}</select></label><AccountingButton busy={busy==='mapping'}><Link2 size={15}/>Save mapping</AccountingButton></form><p className="mt-3 text-xs text-slate-500">{mappings.length} mappings configured.</p></AccountingPanel><AccountingPanel title="Post one POS order" description="Uses the order UUID as the permanent source identity. Retries cannot duplicate it."><form className="flex gap-2" onSubmit={postOrder}><input required className={inputClass} placeholder="POS order UUID" value={orderId} onChange={e=>setOrderId(e.target.value)}/><AccountingButton busy={busy==='order'}><Send size={15}/>Post</AccountingButton></form></AccountingPanel></div>
      </div>}
    </div>}
  </AccountingPage>
}

