import { useCallback, useEffect, useMemo, useState } from 'react'
import { Check, FileUp, Landmark, RefreshCw, SearchCheck } from 'lucide-react'
import { useAccess } from '../../app-context'
import { canAccessCapability } from '../../../../shared/accessControl'
import { AccountingButton, AccountingLoading, AccountingNotice, AccountingPage, AccountingPanel, EmptyState, accountingInvoke, inputClass, labelClass, money, runIdempotent, today, unwrap } from './RestaurantAccountingUi'

function parseCsv(text){
 const lines=text.replace(/^\uFEFF/,'').split(/\r?\n/).filter(Boolean);if(lines.length<2)throw new Error('CSV requires a header and at least one transaction')
 const headers=lines[0].split(',').map(x=>x.trim().toLowerCase())
 const find=(names)=>names.map(n=>headers.indexOf(n)).find(i=>i>=0)
 const date=find(['date','transaction_date']),desc=find(['description','details']),debit=find(['debit','withdrawal']),credit=find(['credit','deposit']),balance=find(['balance','balance_after']),ref=find(['reference','reference_number'])
 if(date==null||desc==null||debit==null||credit==null)throw new Error('CSV headers must include date, description, debit, and credit')
 return lines.slice(1).map((line,index)=>{const c=line.split(',').map(x=>x.trim().replace(/^"|"$/g,''));const n=v=>Number(String(v||'0').replace(/[^0-9.-]/g,''))||0;const row={transaction_date:c[date],description:c[desc],debit:n(c[debit]),credit:n(c[credit]),balance_after:balance==null?null:n(c[balance]),reference_number:ref==null?null:c[ref]};if(!/^\d{4}-\d{2}-\d{2}$/.test(row.transaction_date))throw new Error(`Row ${index+2} needs date YYYY-MM-DD`);if(!row.description||!((row.debit>0&&row.credit===0)||(row.credit>0&&row.debit===0)))throw new Error(`Row ${index+2} needs a description and exactly one debit or credit`);return row})
}

export default function RestaurantBankReconciliation(){
 const access=useAccess(),canManage=canAccessCapability(access,'accounting.manage'),canApprove=canAccessCapability(access,'accounting.bank_approve')
 const [accounts,setAccounts]=useState([]),[bank,setBank]=useState({accounts:[],imports:[],transactions:[],reconciliations:[]}),[bankId,setBankId]=useState('')
 const [account,setAccount]=useState({accountId:'',name:'',bankName:'',accountNumber:'',accountType:'checking',isActive:true}),[file,setFile]=useState({name:'',rows:[]})
 const [recon,setRecon]=useState({statementImportId:'',statementBalance:'',reconciliationDate:today(),transactionIds:[]})
 const [loading,setLoading]=useState(true),[busy,setBusy]=useState(''),[error,setError]=useState(''),[notice,setNotice]=useState('')
 const load=useCallback(async()=>{setLoading(true);setError('');try{const[a,w]=await Promise.all([accountingInvoke('getAccounts'),accountingInvoke('getBank',bankId||null)]);setAccounts(unwrap(a,[]));setBank(unwrap(w,{accounts:[],imports:[],transactions:[],reconciliations:[]}))}catch(e){setError(e.message)}finally{setLoading(false)}},[bankId])
 useEffect(()=>{load()},[load])
 const selectedImport=bank.imports.find(i=>i.id===recon.statementImportId)
 const eligible=useMemo(()=>bank.transactions.filter(t=>(!recon.statementImportId||t.statement_import_id===recon.statementImportId)&&!t.is_reconciled&&(t.reconciled_entry_id||t.exception_reason)),[bank.transactions,recon.statementImportId])
 const saveAccount=async(e)=>{e.preventDefault();setBusy('account');setError('');try{await accountingInvoke('saveBankAccount',account);setAccount({accountId:'',name:'',bankName:'',accountNumber:'',accountType:'checking',isActive:true});setNotice('Bank account linked to an active asset account. No scalar opening balance was created.');await load()}catch(e2){setError(e2.message)}finally{setBusy('')}}
 const chooseFile=async(e)=>{const f=e.target.files?.[0];setFile({name:'',rows:[]});setNotice('');if(!f)return;try{setFile({name:f.name,rows:parseCsv(await f.text())})}catch(err){setError(err.message);e.target.value=''}}
 const importFile=async()=>{setBusy('import');setError('');try{await runIdempotent(`bank-import:${bankId}:${file.name}`,operationKey=>accountingInvoke('importBank',{bankAccountId:bankId,fileName:file.name,transactions:file.rows,operationKey}));setFile({name:'',rows:[]});setNotice('Statement evidence imported immutably. Duplicate rows or conflicting retries are rejected.');await load()}catch(e){setError(e.message)}finally{setBusy('')}}
 const propose=async()=>{setBusy('propose');setError('');try{const r=await accountingInvoke('proposeBank',bankId);setNotice(`${r?.data?.proposed||0} match proposals created for independent review.`);await load()}catch(e){setError(e.message)}finally{setBusy('')}}
 const review=async(id,approve)=>{setBusy(id);setError('');try{await accountingInvoke('reviewBank',id,approve);await load()}catch(e){setError(e.message)}finally{setBusy('')}}
 const exceptTx=async(t)=>{const reason=window.prompt('Document why this statement row is an exception:');if(!reason)return;setBusy(t.id);setError('');try{await accountingInvoke('exceptBank',t.id,reason);await load()}catch(e){setError(e.message)}finally{setBusy('')}}
 const toggle=id=>setRecon({...recon,transactionIds:recon.transactionIds.includes(id)?recon.transactionIds.filter(x=>x!==id):[...recon.transactionIds,id]})
 const createRecon=async(e)=>{e.preventDefault();setBusy('recon');setError('');try{const r=await accountingInvoke('createReconciliation',{bankAccountId:bankId,...recon,statementBalance:Number(recon.statementBalance),adjustments:[]});setNotice(`Draft reconciliation created with difference ${money(r?.data?.difference)}. It can complete only at zero.`);setRecon({statementImportId:'',statementBalance:'',reconciliationDate:today(),transactionIds:[]});await load()}catch(e2){setError(e2.message)}finally{setBusy('')}}
 const complete=async(r)=>{const notes=window.prompt('Completion notes (optional):')||'';setBusy(r.id);setError('');try{await accountingInvoke('completeReconciliation',r.id,notes);setNotice('Reconciliation completed and the accounting period is locked through its date.');await load()}catch(e){setError(e.message)}finally{setBusy('')}}
 const assets=accounts.filter(a=>a.is_active&&a.account_type==='asset')
 return <AccountingPage title="Bank reconciliation" description="Preserve imported statement evidence, propose deterministic matches, require independent review, reconcile to zero, and lock completed periods." actions={<AccountingButton tone="secondary" onClick={load}><RefreshCw size={15}/>Refresh</AccountingButton>}>
  <AccountingNotice>Import evidence cannot be edited or deleted. A different person must approve proposed matches and complete a prepared reconciliation.</AccountingNotice>{error&&<AccountingNotice type="error">{error}</AccountingNotice>}{notice&&<AccountingNotice type="success">{notice}</AccountingNotice>}
  {loading?<AccountingLoading/>:<div className="space-y-4">
   <AccountingPanel title="Bank account"><div className="flex flex-wrap gap-3"><select className={`${inputClass} max-w-md`} value={bankId} onChange={e=>{setBankId(e.target.value);setFile({name:'',rows:[]});setRecon({...recon,statementImportId:'',transactionIds:[]})}}><option value="">All bank accounts</option>{bank.accounts.map(a=><option key={a.id} value={a.id}>{a.name} · {a.account_number} · {money(a.ledger_balance)}</option>)}</select>{bankId&&canManage&&<AccountingButton onClick={propose} busy={busy==='propose'}><SearchCheck size={15}/>Propose matches</AccountingButton>}</div></AccountingPanel>
   <div className="grid gap-4 xl:grid-cols-2">
    {canManage&&<AccountingPanel title="Configure bank account" description="Opening values must be posted in Chart of Accounts, never stored here."><form className="grid gap-3 sm:grid-cols-2" onSubmit={saveAccount}><label className={labelClass}>Display name<input required className={inputClass} value={account.name} onChange={e=>setAccount({...account,name:e.target.value})}/></label><label className={labelClass}>Bank<input className={inputClass} value={account.bankName} onChange={e=>setAccount({...account,bankName:e.target.value})}/></label><label className={labelClass}>Account number<input required className={inputClass} value={account.accountNumber} onChange={e=>setAccount({...account,accountNumber:e.target.value})}/></label><label className={labelClass}>Type<select className={inputClass} value={account.accountType} onChange={e=>setAccount({...account,accountType:e.target.value})}>{['checking','savings','cash','mobile_money'].map(x=><option key={x}>{x}</option>)}</select></label><label className={`${labelClass} sm:col-span-2`}>GL asset account<select required className={inputClass} value={account.accountId} onChange={e=>setAccount({...account,accountId:e.target.value})}><option value="">Select</option>{assets.map(a=><option key={a.id} value={a.id}>{a.code} — {a.name}</option>)}</select></label><AccountingButton busy={busy==='account'}><Landmark size={15}/>Save bank account</AccountingButton></form></AccountingPanel>}
    {canManage&&<AccountingPanel title="Import statement CSV" description="Required headers: date, description, debit, credit. Optional: balance, reference."><div className="space-y-3"><input type="file" accept=".csv,text/csv" className={inputClass} onChange={chooseFile}/>{file.rows.length>0&&<p className="text-sm font-semibold">{file.name}: {file.rows.length} validated rows</p>}<AccountingButton disabled={!bankId||file.rows.length===0} busy={busy==='import'} onClick={importFile}><FileUp size={15}/>Import immutable evidence</AccountingButton></div></AccountingPanel>}
   </div>
   <AccountingPanel title="Statement transactions">{bank.transactions.length===0?<EmptyState title="No statement rows for this selection"/>:<div className="overflow-x-auto"><table className="w-full text-sm"><thead><tr className="border-b text-left text-xs text-slate-500"><th className="py-2">Date / description</th><th className="text-right">Debit</th><th className="text-right">Credit</th><th>Control status</th><th/></tr></thead><tbody>{bank.transactions.map(t=><tr key={t.id} className="border-b border-slate-100"><td className="py-2">{t.transaction_date}<br/><b>{t.description}</b></td><td className="text-right">{money(t.debit)}</td><td className="text-right">{money(t.credit)}</td><td>{t.is_reconciled?'Reconciled':t.exception_reason?'Exception documented':t.proposal?.status?`Match ${t.proposal.status}`:'Unmatched'}</td><td className="text-right"><div className="flex justify-end gap-2">{canApprove&&t.proposal?.status==='pending'&&<><AccountingButton busy={busy===t.proposal.id} onClick={()=>review(t.proposal.id,true)}><Check size={13}/>Approve</AccountingButton><AccountingButton tone="secondary" onClick={()=>review(t.proposal.id,false)}>Reject</AccountingButton></>}{canManage&&!t.is_reconciled&&!t.reconciled_entry_id&&!t.exception_reason&&<AccountingButton tone="secondary" onClick={()=>exceptTx(t)}>Exception</AccountingButton>}</div></td></tr>)}</tbody></table></div>}</AccountingPanel>
   {canManage&&bankId&&<AccountingPanel title="Prepare reconciliation"><form className="space-y-3" onSubmit={createRecon}><div className="grid gap-3 md:grid-cols-3"><label className={labelClass}>Statement import<select required className={inputClass} value={recon.statementImportId} onChange={e=>setRecon({...recon,statementImportId:e.target.value,transactionIds:[]})}><option value="">Select evidence</option>{bank.imports.map(i=><option key={i.id} value={i.id}>{i.file_name||i.id} · {i.period_start}–{i.period_end}</option>)}</select></label><label className={labelClass}>Statement balance<input required type="number" step="0.01" className={inputClass} value={recon.statementBalance} onChange={e=>setRecon({...recon,statementBalance:e.target.value})}/></label><label className={labelClass}>Reconciliation date<input required type="date" min={selectedImport?.period_end} className={inputClass} value={recon.reconciliationDate} onChange={e=>setRecon({...recon,reconciliationDate:e.target.value})}/></label></div><div className="grid gap-2">{eligible.map(t=><label key={t.id} className="flex items-center gap-2 rounded-lg bg-slate-50 p-2 text-sm"><input type="checkbox" checked={recon.transactionIds.includes(t.id)} onChange={()=>toggle(t.id)}/>{t.transaction_date} · {t.description} · {money(Number(t.credit)-Number(t.debit))}</label>)}</div><AccountingButton disabled={recon.transactionIds.length===0} busy={busy==='recon'}>Create draft reconciliation</AccountingButton></form></AccountingPanel>}
   <AccountingPanel title="Reconciliation history">{bank.reconciliations.length===0?<EmptyState title="No reconciliations"/>:<div className="space-y-2">{bank.reconciliations.map(r=><div key={r.id} className="flex flex-wrap items-center justify-between gap-3 rounded-xl border border-slate-200 p-3"><span><b>{r.reconciliation_date}</b> · Statement {money(r.statement_balance)} · Difference {money(r.difference)} · {r.status}</span>{canApprove&&r.status==='draft'&&<AccountingButton disabled={Number(r.difference)!==0} busy={busy===r.id} onClick={()=>complete(r)}>Complete & lock</AccountingButton>}</div>)}</div>}</AccountingPanel>
  </div>}
 </AccountingPage>
}

