import { useCallback, useEffect, useState } from 'react'
import { Check, FileCheck2, RefreshCw, Stamp } from 'lucide-react'
import { useAccess } from '../../app-context'
import { canAccessCapability } from '../../../../shared/accessControl'
import { AccountingButton, AccountingLoading, AccountingNotice, AccountingPage, AccountingPanel, EmptyState, accountingInvoke, firstOfMonth, inputClass, labelClass, money, today, unwrap } from './RestaurantAccountingUi'

export default function RestaurantTaxReturns(){
 const access=useAccess(),canManage=canAccessCapability(access,'accounting.manage'),canFile=canAccessCapability(access,'accounting.tax_file')
 const [accounts,setAccounts]=useState([]),[data,setData]=useState({configurations:[],working_papers:[]})
 const [config,setConfig]=useState({jurisdictionCode:'BW',ruleVersion:'',effectiveFrom:today(),effectiveTo:'',outputTaxAccountId:'',inputTaxAccountId:''})
 const [period,setPeriod]=useState({periodStart:firstOfMonth(),periodEnd:today(),configurationId:''})
 const [loading,setLoading]=useState(true),[busy,setBusy]=useState(''),[error,setError]=useState(''),[notice,setNotice]=useState('')
 const load=useCallback(async()=>{setLoading(true);setError('');try{const[a,w]=await Promise.all([accountingInvoke('getAccounts'),accountingInvoke('getTax')]);setAccounts(unwrap(a,[]));setData(unwrap(w,{configurations:[],working_papers:[]}))}catch(e){setError(e.message)}finally{setLoading(false)}},[])
 useEffect(()=>{load()},[load])
 const saveConfig=async(e)=>{e.preventDefault();setBusy('config');setError('');try{await accountingInvoke('setTaxConfig',config);setNotice('Versioned tax source mapping saved. This config records ledger sources; it does not implement or submit a statutory return.');await load()}catch(e2){setError(e2.message)}finally{setBusy('')}}
 const generate=async(e)=>{e.preventDefault();setBusy('generate');setError('');try{await accountingInvoke('generateTax',period);setNotice('Ledger-derived working paper generated with an immutable source snapshot.');await load()}catch(e2){setError(e2.message)}finally{setBusy('')}}
 const step=async(name,id)=>{setBusy(`${name}:${id}`);setError('');try{if(name==='review')await accountingInvoke('reviewTax',id);else if(name==='approve')await accountingInvoke('approveTax',id);else{const reference=window.prompt('Enter the authoritative tax-authority filing reference:');if(!reference)return;const notes=window.prompt('Filing notes (optional):')||'';await accountingInvoke('fileTax',id,reference,notes)}setNotice(name==='file'?'Filing evidence recorded. The application did not submit anything to the tax authority.':`Working paper ${name} step completed.`);await load()}catch(e){setError(e.message)}finally{setBusy('')}}
 const liabilities=accounts.filter(a=>a.is_active&&a.account_type==='liability'),assets=accounts.filter(a=>a.is_active&&a.account_type==='asset')
 return <AccountingPage title="Tax working papers" description="Generate ledger-derived tax working papers, review and approve immutable snapshots, then record authoritative external filing evidence." actions={<AccountingButton tone="secondary" onClick={load}><RefreshCw size={15}/>Refresh</AccountingButton>}>
  <AccountingNotice type="warning">This is a working-paper and evidence workflow. It does not calculate jurisdiction-specific tax law beyond configured ledger sources, and it never submits a return to a tax authority.</AccountingNotice>{error&&<AccountingNotice type="error">{error}</AccountingNotice>}{notice&&<AccountingNotice type="success">{notice}</AccountingNotice>}
  {loading?<AccountingLoading/>:<div className="space-y-4">
   <AccountingPanel title="Working papers">{data.working_papers.length===0?<EmptyState title="No tax working papers"/>:<div className="overflow-x-auto"><table className="w-full text-sm"><thead><tr className="border-b text-left text-xs text-slate-500"><th className="py-2">Period / rules</th><th className="text-right">Output tax</th><th className="text-right">Input tax</th><th className="text-right">Net payable</th><th>Status</th><th/></tr></thead><tbody>{data.working_papers.map(r=><tr key={r.id} className="border-b border-slate-100"><td className="py-2"><b>{r.period_start}–{r.period_end}</b><br/><small>{r.jurisdiction_code} · {r.rule_version}</small></td><td className="text-right">{money(r.total_tax_collected)}</td><td className="text-right">{money(r.total_input_tax)}</td><td className="text-right font-bold">{money(r.net_tax_payable)}</td><td>{r.status}{r.filing_reference&&<><br/><small>{r.filing_reference}</small></>}</td><td className="text-right"><div className="flex justify-end gap-2">{canManage&&r.status==='draft'&&<AccountingButton busy={busy===`review:${r.id}`} onClick={()=>step('review',r.id)}><FileCheck2 size={13}/>Review</AccountingButton>}{canFile&&r.status==='reviewed'&&<AccountingButton busy={busy===`approve:${r.id}`} onClick={()=>step('approve',r.id)}><Check size={13}/>Approve</AccountingButton>}{canFile&&r.status==='approved'&&<AccountingButton tone="amber" busy={busy===`file:${r.id}`} onClick={()=>step('file',r.id)}><Stamp size={13}/>Record filing</AccountingButton>}</div></td></tr>)}</tbody></table></div>}</AccountingPanel>
   <div className="grid gap-4 xl:grid-cols-2">
    {canManage&&<AccountingPanel title="Versioned tax source mapping"><form className="grid gap-3 sm:grid-cols-2" onSubmit={saveConfig}><label className={labelClass}>Jurisdiction code<input required className={inputClass} value={config.jurisdictionCode} onChange={e=>setConfig({...config,jurisdictionCode:e.target.value})}/></label><label className={labelClass}>Rule version<input required className={inputClass} placeholder="e.g. BW-VAT-2026-01" value={config.ruleVersion} onChange={e=>setConfig({...config,ruleVersion:e.target.value})}/></label><label className={labelClass}>Effective from<input required type="date" className={inputClass} value={config.effectiveFrom} onChange={e=>setConfig({...config,effectiveFrom:e.target.value})}/></label><label className={labelClass}>Effective to<input type="date" className={inputClass} value={config.effectiveTo} onChange={e=>setConfig({...config,effectiveTo:e.target.value})}/></label><label className={labelClass}>Output tax liability<select required className={inputClass} value={config.outputTaxAccountId} onChange={e=>setConfig({...config,outputTaxAccountId:e.target.value})}><option value="">Select</option>{liabilities.map(a=><option key={a.id} value={a.id}>{a.code} — {a.name}</option>)}</select></label><label className={labelClass}>Input tax asset<select required className={inputClass} value={config.inputTaxAccountId} onChange={e=>setConfig({...config,inputTaxAccountId:e.target.value})}><option value="">Select</option>{assets.map(a=><option key={a.id} value={a.id}>{a.code} — {a.name}</option>)}</select></label><AccountingButton busy={busy==='config'}>Save version</AccountingButton></form></AccountingPanel>}
    {canManage&&<AccountingPanel title="Generate working paper"><form className="space-y-3" onSubmit={generate}><label className={labelClass}>Configuration<select required className={inputClass} value={period.configurationId} onChange={e=>setPeriod({...period,configurationId:e.target.value})}><option value="">Select effective rules</option>{data.configurations.map(c=><option key={c.id} value={c.id}>{c.jurisdiction_code} · {c.rule_version} · from {c.effective_from}</option>)}</select></label><label className={labelClass}>Period start<input required type="date" className={inputClass} value={period.periodStart} onChange={e=>setPeriod({...period,periodStart:e.target.value})}/></label><label className={labelClass}>Period end<input required type="date" className={inputClass} value={period.periodEnd} onChange={e=>setPeriod({...period,periodEnd:e.target.value})}/></label><AccountingButton busy={busy==='generate'}>Generate from posted ledger</AccountingButton></form></AccountingPanel>}
   </div>
  </div>}
 </AccountingPage>
}

