import { useCallback, useEffect, useMemo, useState } from 'react'
import { Check, FileUp, Landmark, RefreshCw, SearchCheck, X } from 'lucide-react'
import { useAccess } from '../../app-context'
import { canAccessCapability } from '../../../../shared/accessControl'
import { AccountingButton, AccountingExportButton, AccountingLoading, AccountingNotice, AccountingPage, AccountingPanel, EmptyState, accountingInvoke, inputClass, labelClass, money, runIdempotent, today, unwrap } from './RestaurantAccountingUi'

function parseCsv(text){
 const input=String(text||'').replace(/^\uFEFF/,'');const records=[];let record=[];let field='';let quoted=false;let afterQuote=false
 for(let i=0;i<input.length;i++){const ch=input[i]
  if(quoted){if(ch==='"'&&input[i+1]==='"'){field+='"';i++;continue}if(ch==='"'){quoted=false;afterQuote=true;continue}field+=ch;continue}
  if(afterQuote){if(ch===','){record.push(field.trim());field='';afterQuote=false;continue}if(ch==='\r'||ch==='\n'){record.push(field.trim());if(record.some(Boolean))records.push(record);record=[];field='';afterQuote=false;if(ch==='\r'&&input[i+1]==='\n')i++;continue}if(/\s/.test(ch))continue;throw new Error('CSV has characters after a quoted field')}
  if(ch==='"'&&field.trim()===''){quoted=true;field='';continue}if(ch===','){record.push(field.trim());field='';continue}if(ch==='\r'||ch==='\n'){record.push(field.trim());if(record.some(Boolean))records.push(record);record=[];field='';if(ch==='\r'&&input[i+1]==='\n')i++;continue}field+=ch
 }
 if(quoted)throw new Error('CSV contains an unterminated quoted field');if(field!==''||record.length){record.push(field.trim());if(record.some(Boolean))records.push(record)}
 if(records.length<2)throw new Error('CSV requires a header and at least one transaction')
 return {headers:records[0],records:records.slice(1)}
}

function inferredMapping(headers){
 const normalized=headers.map(x=>String(x||'').trim().toLowerCase());const find=(names)=>names.map(n=>normalized.indexOf(n)).find(i=>i>=0)
 return {date:find(['date','transaction_date']),description:find(['description','details']),debit:find(['debit','withdrawal']),credit:find(['credit','deposit']),balance:find(['balance','balance_after']),reference:find(['reference','reference_number'])}
}

function normalizeBankRows(records,mapping){
 const required=['date','description','debit','credit','balance'];if(required.some(key=>mapping?.[key]==null||mapping?.[key]===-1))throw new Error('Map date, description, debit, credit, and balance_after before importing')
 const n=value=>{const normalized=String(value??'').replace(/\s/g,'').replace(/,/g,'');if(normalized==='')return 0;const parsed=Number(normalized);if(!Number.isFinite(parsed))throw new Error('Bank amounts must be valid decimals');return parsed}
 return records.map((columns,index)=>{const row={transaction_date:String(columns[mapping.date]??'').trim(),description:String(columns[mapping.description]??'').trim(),debit:n(columns[mapping.debit]),credit:n(columns[mapping.credit]),balance_after:n(columns[mapping.balance]),reference_number:mapping.reference==null||mapping.reference===-1?null:String(columns[mapping.reference]??'').trim()||null};if(!/^\d{4}-\d{2}-\d{2}$/.test(row.transaction_date))throw new Error(`Row ${index+2} needs date YYYY-MM-DD`);if(!row.description||!((row.debit>0&&row.credit===0)||(row.credit>0&&row.debit===0)))throw new Error(`Row ${index+2} needs a description and exactly one debit or credit`);return row})
}

export default function RestaurantBankReconciliation(){
 const access=useAccess(),canManage=canAccessCapability(access,'accounting.manage'),canApprove=canAccessCapability(access,'accounting.bank_approve')
 const [accounts,setAccounts]=useState([]),[bank,setBank]=useState({accounts:[],imports:[],transactions:[],reconciliations:[]}),[bankId,setBankId]=useState('')
 const [account,setAccount]=useState({accountId:'',name:'',bankName:'',accountNumber:'',accountType:'checking',isActive:true}),[file,setFile]=useState({name:'',headers:[],records:[],mapping:{}})
 const [openingBalance,setOpeningBalance]=useState(''),[closingBalance,setClosingBalance]=useState('')
 const [recon,setRecon]=useState({statementImportId:'',statementBalance:'',reconciliationDate:today(),transactionIds:[]})
 const [loading,setLoading]=useState(true),[busy,setBusy]=useState(''),[error,setError]=useState(''),[notice,setNotice]=useState('')
 const [match,setMatch]=useState({transactionId:'',candidates:[],candidateId:'',amount:'',reason:'',evidence:''})
 const load=useCallback(async()=>{setLoading(true);setError('');try{const[a,w]=await Promise.all([accountingInvoke('getAccounts'),accountingInvoke('getBank',bankId||null)]);setAccounts(unwrap(a,[]));setBank(unwrap(w,{accounts:[],imports:[],transactions:[],reconciliations:[]}))}catch(e){setError(e.message)}finally{setLoading(false)}},[bankId])
 useEffect(()=>{load()},[load])
 const previewRows=useMemo(()=>{try{return normalizeBankRows(file.records,file.mapping)}catch{return []}},[file.records,file.mapping])
 const requiredBankMapping=['date','description','debit','credit','balance'].every(key=>file.mapping?.[key]!=null&&file.mapping?.[key]!==-1)
 const selectedImport=bank.imports.find(i=>i.id===recon.statementImportId)
 const eligible=useMemo(()=>bank.transactions.filter(t=>(!recon.statementImportId||t.statement_import_id===recon.statementImportId)&&!t.is_reconciled&&(t.reconciled_entry_id||t.exception_reason)),[bank.transactions,recon.statementImportId])
 const saveAccount=async(e)=>{e.preventDefault();setBusy('account');setError('');try{await accountingInvoke('saveBankAccount',account);setAccount({accountId:'',name:'',bankName:'',accountNumber:'',accountType:'checking',isActive:true});setNotice('Bank account linked to an active asset account. No scalar opening balance was created.');await load()}catch(e2){setError(e2.message)}finally{setBusy('')}}
 const chooseFile=async(e)=>{const f=e.target.files?.[0];setFile({name:'',headers:[],records:[],mapping:{}});setNotice('');setError('');if(!f)return;try{const parsed=parseCsv(await f.text());setFile({name:f.name,headers:parsed.headers,records:parsed.records,mapping:inferredMapping(parsed.headers)});setNotice('Preview parsed. Confirm the column mapping, balances, and debit/credit sign convention before importing.')}catch(err){setError(err.message);e.target.value=''}}
 const importFile=async()=>{setBusy('import');setError('');try{if(!requiredBankMapping||previewRows.length===0)throw new Error('Map all required columns and correct the preview before importing');if(openingBalance===''||closingBalance==='')throw new Error('Opening and closing balance evidence is required');await runIdempotent(`bank-import:${bankId}:${file.name}`,operationKey=>accountingInvoke('importBank',{bankAccountId:bankId,fileName:file.name,transactions:previewRows,openingBalance:Number(openingBalance),closingBalance:Number(closingBalance),operationKey}));setFile({name:'',headers:[],records:[],mapping:{}});setOpeningBalance('');setClosingBalance('');setNotice('Statement evidence imported immutably. Duplicate rows or conflicting retries are rejected.');await load()}catch(e){setError(e.message)}finally{setBusy('')}}
 const openMatch=async(t)=>{setBusy(`candidates:${t.id}`);setError('');try{const r=unwrap(await accountingInvoke('getBankCandidates',t.id),{candidates:[]});setMatch({transactionId:t.id,candidates:r.candidates||[],candidateId:'',amount:'',reason:'',evidence:''})}catch(e){setError(e.message)}finally{setBusy('')}}
 const propose=async()=>{setBusy('propose');setError('');try{const candidate=match.candidates.find(x=>x.journal_line_id===match.candidateId);if(!candidate)throw new Error('Select one posted journal line as match evidence.');const amount=Number(match.amount||candidate.available_amount);if(!Number.isFinite(amount)||amount<=0||amount>Number(candidate.available_amount))throw new Error('Allocation amount must be positive and within the available journal-line balance.');if(!match.reason.trim())throw new Error('A reason is required for every bank allocation.');await runIdempotent(`bank-match:${match.transactionId}:${candidate.journal_line_id}:${amount}`,operationId=>accountingInvoke('proposeBankAllocation',{bankTransactionId:match.transactionId,allocations:[{journal_entry_id:candidate.journal_entry_id,journal_line_id:candidate.journal_line_id,allocated_amount:amount}],reason:match.reason.trim(),evidence:{operation_id:operationId,operator_note:match.evidence.trim()||null}}));setMatch({transactionId:'',candidates:[],candidateId:'',amount:'',reason:'',evidence:''});setNotice('Locked bank allocation proposed. A different authorised reviewer must approve it.');await load()}catch(e){setError(e.message)}finally{setBusy('')}}
 const review=async(id,approve)=>{setBusy(id);setError('');try{const reason=approve?'Approved against posted journal evidence.':window.prompt('Reason for rejecting this allocation:')||'';if(!approve&&!reason.trim())return;await accountingInvoke('reviewBankAllocation',id,approve,reason);await load()}catch(e){setError(e.message)}finally{setBusy('')}}
 const exceptTx=async(t)=>{const reason=window.prompt('Document why this statement row is an exception:');if(!reason)return;setBusy(t.id);setError('');try{await accountingInvoke('exceptBank',t.id,reason);await load()}catch(e){setError(e.message)}finally{setBusy('')}}
 const toggle=id=>setRecon({...recon,transactionIds:recon.transactionIds.includes(id)?recon.transactionIds.filter(x=>x!==id):[...recon.transactionIds,id]})
 const createRecon=async(e)=>{e.preventDefault();setBusy('recon');setError('');try{const r=await accountingInvoke('createReconciliation',{bankAccountId:bankId,...recon,statementBalance:Number(recon.statementBalance),adjustments:[]});setNotice(`Draft reconciliation created with difference ${money(r?.data?.difference)}. It can complete only at zero.`);setRecon({statementImportId:'',statementBalance:'',reconciliationDate:today(),transactionIds:[]});await load()}catch(e2){setError(e2.message)}finally{setBusy('')}}
 const complete=async(r)=>{const notes=window.prompt('Completion notes (optional):')||'';setBusy(r.id);setError('');try{await accountingInvoke('completeReconciliation',r.id,notes);setNotice('Bank reconciliation packet completed with immutable statement evidence. Accounting-period close remains a separate control.');await load()}catch(e){setError(e.message)}finally{setBusy('')}}
 const assets=accounts.filter(a=>a.is_active&&a.account_type==='asset')
 return <AccountingPage title="Bank reconciliation" description="Preserve imported statement evidence, propose deterministic matches, require independent review, reconcile to zero, and lock completed periods." actions={<><AccountingExportButton fileName="bank-reconciliation" exportOperation="exportBank" onError={setError}/><AccountingButton tone="secondary" onClick={load}><RefreshCw size={15}/>Refresh</AccountingButton></>}>
  <AccountingNotice>Import evidence cannot be edited or deleted. A different person must approve proposed matches and complete a prepared reconciliation.</AccountingNotice>{error&&<AccountingNotice type="error">{error}</AccountingNotice>}{notice&&<AccountingNotice type="success">{notice}</AccountingNotice>}
  {loading?<AccountingLoading/>:<div className="space-y-4">
   <AccountingPanel title="Bank account"><div className="flex flex-wrap gap-3"><select className={`${inputClass} max-w-md`} value={bankId} onChange={e=>{setBankId(e.target.value);setMatch({transactionId:'',candidates:[],candidateId:'',amount:'',reason:'',evidence:''});setFile({name:'',headers:[],records:[],mapping:{}});setRecon({...recon,statementImportId:'',transactionIds:[]})}}><option value="">All bank accounts</option>{bank.accounts.map(a=><option key={a.id} value={a.id}>{a.name} · {a.account_number} · {money(a.ledger_balance)}</option>)}</select><span className="text-xs text-slate-500">Matches are selected per statement row and allocated against posted journal evidence.</span></div></AccountingPanel>
   <div className="grid gap-4 xl:grid-cols-2">
    {canManage&&<AccountingPanel title="Configure bank account" description="Opening values must be posted in Chart of Accounts, never stored here."><form className="grid gap-3 sm:grid-cols-2" onSubmit={saveAccount}><label className={labelClass}>Display name<input required className={inputClass} value={account.name} onChange={e=>setAccount({...account,name:e.target.value})}/></label><label className={labelClass}>Bank<input className={inputClass} value={account.bankName} onChange={e=>setAccount({...account,bankName:e.target.value})}/></label><label className={labelClass}>Account number<input required className={inputClass} value={account.accountNumber} onChange={e=>setAccount({...account,accountNumber:e.target.value})}/></label><label className={labelClass}>Type<select className={inputClass} value={account.accountType} onChange={e=>setAccount({...account,accountType:e.target.value})}>{['checking','savings','cash','mobile_money'].map(x=><option key={x}>{x}</option>)}</select></label><label className={`${labelClass} sm:col-span-2`}>GL asset account<select required className={inputClass} value={account.accountId} onChange={e=>setAccount({...account,accountId:e.target.value})}><option value="">Select</option>{assets.map(a=><option key={a.id} value={a.id}>{a.code} — {a.name}</option>)}</select></label><AccountingButton busy={busy==='account'}><Landmark size={15}/>Save bank account</AccountingButton></form></AccountingPanel>}
    {canManage&&<AccountingPanel title="Import statement CSV" description="RFC 4180 preview. Map date, description, debit, credit, and balance_after explicitly; every row must carry balance_after. Signed amount is credit minus debit."><div className="space-y-3"><input type="file" accept=".csv,text/csv" className={inputClass} onChange={chooseFile}/>{file.headers.length>0&&<div className="grid gap-2 sm:grid-cols-2">{[['date','Date'],['description','Description'],['debit','Debit / withdrawal'],['credit','Credit / deposit'],['balance','Balance after'],['reference','Reference']].map(([key,label])=><label key={key} className={labelClass}>{label}<select className={inputClass} value={file.mapping?.[key]??''} onChange={e=>setFile({...file,mapping:{...file.mapping,[key]:e.target.value===''?null:Number(e.target.value)}})}><option value="">Not mapped</option>{file.headers.map((header,index)=><option key={`${key}-${index}`} value={index}>{header}</option>)}</select></label>)}</div>}{file.records.length>0&&<><p className="text-sm font-semibold">{file.name}: {previewRows.length} validated rows{!requiredBankMapping&&' · map required columns'}</p><div className="grid gap-2 sm:grid-cols-2"><label className={labelClass}>Opening balance<input required type="number" step="0.01" className={inputClass} value={openingBalance} onChange={e=>setOpeningBalance(e.target.value)}/></label><label className={labelClass}>Closing balance<input required type="number" step="0.01" className={inputClass} value={closingBalance} onChange={e=>setClosingBalance(e.target.value)}/></label></div></>}<AccountingButton disabled={!bankId||previewRows.length===0||!requiredBankMapping||openingBalance===''||closingBalance===''} busy={busy==='import'} onClick={importFile}><FileUp size={15}/>Preview and import immutable evidence</AccountingButton></div></AccountingPanel>}
   </div>
   <AccountingPanel title="Statement transactions">{bank.transactions.length===0?<EmptyState title="No statement rows for this selection"/>:<div className="overflow-x-auto"><table className="w-full text-sm"><thead><tr className="border-b text-left text-xs text-slate-500"><th className="py-2">Date / description</th><th className="text-right">Debit</th><th className="text-right">Credit</th><th>Control status</th><th/></tr></thead><tbody>{bank.transactions.map(t=>{const allocations=t.allocations||[];const pending=allocations.filter(a=>a.status==='proposed');return <tr key={t.id} className="border-b border-slate-100"><td className="py-2">{t.transaction_date}<br/><b>{t.description}</b><br/><span className="text-xs text-slate-500">Signed {money(Number(t.credit)-Number(t.debit))}</span></td><td className="text-right">{money(t.debit)}</td><td className="text-right">{money(t.credit)}</td><td>{t.is_reconciled?'Reconciled':t.exception_reason?'Exception documented':pending.length?`Allocation pending review (${pending.length})`:allocations.some(a=>a.status==='approved')?'Allocation approved':'Unmatched'}</td><td className="text-right"><div className="flex justify-end gap-2">{canApprove&&!t.is_reconciled&&!t.exception_reason&&<AccountingButton tone="secondary" busy={busy===`candidates:${t.id}`} onClick={()=>openMatch(t)}><SearchCheck size={13}/>Select journal evidence</AccountingButton>}{canApprove&&pending.map(a=><span key={a.id} className="inline-flex gap-1"><AccountingButton busy={busy===a.id} onClick={()=>review(a.id,true)}><Check size={13}/>Approve</AccountingButton><AccountingButton tone="secondary" onClick={()=>review(a.id,false)}><X size={13}/>Reject</AccountingButton></span>)}{canManage&&!t.is_reconciled&&!t.reconciled_entry_id&&!t.exception_reason&&<AccountingButton tone="secondary" onClick={()=>exceptTx(t)}>Exception</AccountingButton>}</div></td></tr>})}</tbody></table></div>}</AccountingPanel>
   {canApprove&&match.transactionId&&<AccountingPanel title="Propose locked allocation" description="The server locks the bank row and journal target, enforces both remaining capacities, and records proposer/evidence/reason."><div className="grid gap-3 md:grid-cols-2"><label className={labelClass}>Posted journal evidence<select required className={inputClass} value={match.candidateId} onChange={e=>{const candidate=match.candidates.find(x=>x.journal_line_id===e.target.value);setMatch({...match,candidateId:e.target.value,amount:candidate?String(candidate.available_amount):''})}}><option value="">Select candidate</option>{match.candidates.map(c=><option key={c.journal_line_id} value={c.journal_line_id}>{c.entry_date} · {c.description} · {c.source_type} · available {money(c.available_amount)}{c.exact_amount?' · exact':''}</option>)}</select></label><label className={labelClass}>Allocated amount<input required type="number" min="0.01" step="0.01" className={inputClass} value={match.amount} onChange={e=>setMatch({...match,amount:e.target.value})}/></label><label className={labelClass}>Reason<input required className={inputClass} value={match.reason} onChange={e=>setMatch({...match,reason:e.target.value})}/></label><label className={labelClass}>Evidence note<input className={inputClass} value={match.evidence} onChange={e=>setMatch({...match,evidence:e.target.value})}/></label></div><div className="mt-3 flex gap-2"><AccountingButton busy={busy==='propose'} disabled={!match.candidateId||!match.reason.trim()} onClick={propose}>Propose allocation</AccountingButton><AccountingButton tone="secondary" onClick={()=>setMatch({transactionId:'',candidates:[],candidateId:'',amount:'',reason:'',evidence:''})}>Cancel</AccountingButton></div></AccountingPanel>}
   {canManage&&bankId&&<AccountingPanel title="Prepare reconciliation"><form className="space-y-3" onSubmit={createRecon}><div className="grid gap-3 md:grid-cols-3"><label className={labelClass}>Statement import<select required className={inputClass} value={recon.statementImportId} onChange={e=>setRecon({...recon,statementImportId:e.target.value,transactionIds:[]})}><option value="">Select evidence</option>{bank.imports.map(i=><option key={i.id} value={i.id}>{i.file_name||i.id} · {i.period_start}–{i.period_end}</option>)}</select></label><label className={labelClass}>Statement balance<input required type="number" step="0.01" className={inputClass} value={recon.statementBalance} onChange={e=>setRecon({...recon,statementBalance:e.target.value})}/></label><label className={labelClass}>Reconciliation date<input required type="date" min={selectedImport?.period_end} className={inputClass} value={recon.reconciliationDate} onChange={e=>setRecon({...recon,reconciliationDate:e.target.value})}/></label></div><div className="grid gap-2">{eligible.map(t=><label key={t.id} className="flex items-center gap-2 rounded-lg bg-slate-50 p-2 text-sm"><input type="checkbox" checked={recon.transactionIds.includes(t.id)} onChange={()=>toggle(t.id)}/>{t.transaction_date} · {t.description} · {money(Number(t.credit)-Number(t.debit))}</label>)}</div><AccountingButton disabled={recon.transactionIds.length===0} busy={busy==='recon'}>Create draft reconciliation</AccountingButton></form></AccountingPanel>}
   <AccountingPanel title="Reconciliation history">{bank.reconciliations.length===0?<EmptyState title="No reconciliations"/>:<div className="space-y-2">{bank.reconciliations.map(r=><div key={r.id} className="flex flex-wrap items-center justify-between gap-3 rounded-xl border border-slate-200 p-3"><span><b>{r.reconciliation_date}</b> · Statement {money(r.statement_balance)} · Difference {money(r.difference)} · {r.status}</span>{canApprove&&r.status==='draft'&&<AccountingButton disabled={Number(r.difference)!==0} busy={busy===r.id} onClick={()=>complete(r)}>Complete & lock</AccountingButton>}</div>)}</div>}</AccountingPanel>
  </div>}
 </AccountingPage>
}

