import { useCallback, useEffect, useState } from 'react'
import { RefreshCw } from 'lucide-react'
import { AccountingButton, AccountingExportButton, AccountingLoading, AccountingNotice, AccountingPage, AccountingPanel, EmptyState, accountingInvoke, firstOfMonth, inputClass, labelClass, money, runIdempotent, today, unwrap } from './RestaurantAccountingUi'
import { useAccess } from '../../app-context'
import { canAccessCapability } from '../../../../shared/accessControl'
function Rows({rows,valueKey='balance'}){return rows?.length?<div className="divide-y divide-slate-100">{rows.map(r=><div key={r.id||r.account_id} className="flex justify-between gap-4 py-2 text-sm"><span><b>{r.code}</b> — {r.name}{!r.is_active&&<small className="ml-2 text-slate-400">(inactive)</small>}</span><b>{money(r[valueKey])}</b></div>)}</div>:<EmptyState title="No activity"/>}

export default function RestaurantBalanceSheet(){
 const access=useAccess(),canClose=canAccessCapability(access,'accounting.close')
 const [dates,setDates]=useState({startDate:firstOfMonth(),endDate:today()}),[data,setData]=useState(null),[periodClose,setPeriodClose]=useState(null),[loading,setLoading]=useState(true),[error,setError]=useState('')
 const load=useCallback(async()=>{setLoading(true);setError('');try{const [statement,close]=await Promise.all([accountingInvoke('getStatements',dates.startDate,dates.endDate),accountingInvoke('getPeriodClose',dates.startDate,dates.endDate)]);setData(unwrap(statement,null));setPeriodClose(unwrap(close,null))}catch(e){setError(e.message)}finally{setLoading(false)}},[dates])
 useEffect(()=>{load()},[load])
 const prepareClose=async()=>{try{await runIdempotent(`period-close:${dates.startDate}:${dates.endDate}`,operationKey=>accountingInvoke('preparePeriodClose',{startDate:dates.startDate,endDate:dates.endDate,operationKey}));await load()}catch(e){setError(e.message)}}
 const approveClose=async()=>{try{await accountingInvoke('approvePeriodClose',periodClose.id);await load()}catch(e){setError(e.message)}}
 const reopenClose=async()=>{const reason=window.prompt('Reason for reopening this accounting period:');if(!reason?.trim())return;try{await accountingInvoke('reopenPeriodClose',periodClose.id,reason.trim());await load()}catch(e){setError(e.message)}}
 const bs=data?.balance_sheet,is=data?.income_statement,cf=data?.cash_flow||{}
 return <AccountingPage title="Financial statements" description="Balance sheet, income statement, and explicitly classified cash flow derived only from posted accounting journals." actions={<><AccountingExportButton fileName="financial-statements" exportOperation="exportStatements" exportArgs={[dates.startDate,dates.endDate]} onError={setError}/><AccountingButton tone="secondary" onClick={load}><RefreshCw size={15}/>Refresh</AccountingButton></>}>
  <AccountingNotice>Historical activity remains visible when an account is deactivated. Cash movements with missing or conflicting classifications are reported as unclassified—not guessed.</AccountingNotice>{error&&<AccountingNotice type="error">{error}</AccountingNotice>}
  <AccountingPanel title="Statement period" className="mb-4"><div className="grid max-w-xl gap-3 sm:grid-cols-2"><label className={labelClass}>From<input type="date" className={inputClass} value={dates.startDate} onChange={e=>setDates({...dates,startDate:e.target.value})}/></label><label className={labelClass}>To<input type="date" className={inputClass} value={dates.endDate} onChange={e=>setDates({...dates,endDate:e.target.value})}/></label></div></AccountingPanel>
   {loading?<AccountingLoading/>:data&&<div className="space-y-4">
   <AccountingPanel title="Period close control"><div className="flex flex-wrap items-center gap-3 text-sm"><span className="rounded-full bg-slate-100 px-3 py-1 font-bold uppercase tracking-wide text-slate-600">{periodClose?.status||'not prepared'}</span>{canClose? <>{!periodClose&&<AccountingButton tone="secondary" onClick={prepareClose}>Prepare close checklist</AccountingButton>}{periodClose?.status==='blocked'&&<AccountingNotice type="warning">Close is blocked until every checklist exception is resolved.</AccountingNotice>}{periodClose?.status==='prepared'&&<AccountingButton tone="primary" onClick={approveClose}>Approve and close period</AccountingButton>}{periodClose?.status==='closed'&&<AccountingButton tone="secondary" onClick={reopenClose}>Reopen with reason</AccountingButton>}</> : <span className="text-xs font-semibold text-slate-500">Requires Accounting period-close permission.</span>}</div>{periodClose?.checklist&&<pre className="mt-3 overflow-auto rounded-xl bg-slate-50 p-3 text-xs text-slate-600">{JSON.stringify(periodClose.checklist,null,2)}</pre>}</AccountingPanel>
   {Number(bs?.difference||0)!==0&&<AccountingNotice type="error">Balance sheet difference is {money(bs.difference)}. This is a release-blocking ledger exception that must be investigated, not hidden.</AccountingNotice>}
  {cf.complete===false&&<AccountingNotice type="warning">Cash-flow output is incomplete because one or more cash movements lack a single valid classification. Set account cash-flow classifications in Chart of Accounts before relying on this statement.</AccountingNotice>}
  {Number(cf.unclassified||0)!==0&&<AccountingNotice type="warning">{money(cf.unclassified)} of cash movement is unclassified. Set account cash-flow classifications in Chart of Accounts before relying on cash-flow reporting.</AccountingNotice>}
   <div className="grid gap-4 xl:grid-cols-3"><AccountingPanel title="Assets"><Rows rows={bs.assets} valueKey="historical_balance"/><div className="mt-3 flex justify-between border-t pt-3 font-black"><span>Total assets</span><span>{money(bs.assets_total)}</span></div></AccountingPanel><AccountingPanel title="Liabilities"><Rows rows={bs.liabilities} valueKey="historical_balance"/><div className="mt-3 flex justify-between border-t pt-3 font-black"><span>Total liabilities</span><span>{money(bs.liabilities_total)}</span></div></AccountingPanel><AccountingPanel title="Equity"><Rows rows={bs.equity} valueKey="historical_balance"/><div className="mt-3 flex justify-between border-t pt-3 text-sm"><span>Current-period earnings</span><b>{money(bs.current_period_earnings)}</b></div><div className="mt-3 flex justify-between border-t pt-3 font-black"><span>Liabilities + equity</span><span>{money(bs.liabilities_and_equity_total)}</span></div></AccountingPanel></div>
   <div className="grid gap-4 xl:grid-cols-2"><AccountingPanel title="Income statement — revenue"><Rows rows={is.revenue} valueKey="amount"/><div className="mt-3 flex justify-between border-t pt-3 font-black"><span>Total revenue</span><span>{money(is.revenue_total)}</span></div></AccountingPanel><AccountingPanel title="Income statement — expenses"><Rows rows={is.expenses} valueKey="amount"/><div className="mt-3 flex justify-between border-t pt-3 font-black"><span>Total expenses</span><span>{money(is.expense_total)}</span></div></AccountingPanel></div>
   <AccountingPanel title="Period result"><div className="text-3xl font-black text-slate-900">{money(is.net_income)}</div></AccountingPanel>
   <AccountingPanel title="Cash flow classifications"><div className="grid gap-3 sm:grid-cols-4">{['operating','investing','financing','unclassified'].map(k=><div key={k} className="rounded-xl bg-slate-50 p-3"><p className="text-xs font-bold uppercase text-slate-500">{k}</p><b className={k==='unclassified'&&Number(cf[k]||0)!==0?'text-rose-700':'text-slate-900'}>{money(cf[k])}</b></div>)}</div></AccountingPanel>
  </div>}
 </AccountingPage>
}
