import { useCallback, useEffect, useMemo, useState } from 'react'
import { CheckCircle2, Copy, RefreshCw, Save } from 'lucide-react'
import { useAccess } from '../../app-context'
import { canAccessCapability } from '../../../../shared/accessControl'
import { AccountingButton, AccountingExportButton, AccountingLoading, AccountingNotice, AccountingPage, AccountingPanel, EmptyState, accountingInvoke, inputClass, labelClass, money, runIdempotent, unwrap } from './RestaurantAccountingUi'

const months=['Jan','Feb','Mar','Apr','May','Jun','Jul','Aug','Sep','Oct','Nov','Dec']

export default function RestaurantBudgets(){
 const access=useAccess(),canManage=canAccessCapability(access,'accounting.manage')
 const [year,setYear]=useState(new Date().getFullYear()),[data,setData]=useState({matrix:[],templates:[]}),[draft,setDraft]=useState({})
 const [template,setTemplate]=useState({name:'',description:'',accountId:'',defaultAmount:''}),[apply,setApply]=useState({templateId:'',month:new Date().getMonth()+1})
 const [loading,setLoading]=useState(true),[busy,setBusy]=useState(''),[error,setError]=useState(''),[notice,setNotice]=useState('')
 const load=useCallback(async()=>{setLoading(true);setError('');try{const w=unwrap(await accountingInvoke('getBudgets',Number(year)),{matrix:[],templates:[]});setData(w);const d={};w.matrix.forEach(row=>{for(let m=1;m<=12;m++)d[`${row.account_id}:${m}`]=String(row.months?.[m]??row.months?.[String(m)]??0)});setDraft(d)}catch(e){setError(e.message)}finally{setLoading(false)}},[year])
 useEffect(()=>{load()},[load])
 const entries=useMemo(()=>data.matrix.flatMap(row=>months.map((_,i)=>({account_id:row.account_id,month:i+1,amount:Number(draft[`${row.account_id}:${i+1}`]||0)}))),[data.matrix,draft])
 const save=async()=>{setBusy('save');setError('');try{await runIdempotent(`budget-matrix:${year}`,key=>accountingInvoke('saveBudgets',Number(year),entries,key));setNotice(`The complete ${year} budget matrix was saved atomically.`);await load()}catch(e){setError(e.message)}finally{setBusy('')}}
 const approve=async()=>{if(!data.version_id)return;setBusy('approve');setError('');try{await accountingInvoke('approveBudgetVersion',data.version_id);setNotice('The budget version was approved.');await load()}catch(e){setError(e.message)}finally{setBusy('')}}
 const createTemplate=async(e)=>{e.preventDefault();setBusy('template');setError('');try{await runIdempotent(`budget-template:${template.name}`,operationKey=>accountingInvoke('createBudgetTemplate',{name:template.name,description:template.description,operationKey,lines:[{account_id:template.accountId,default_amount:Number(template.defaultAmount)}]}));setTemplate({name:'',description:'',accountId:'',defaultAmount:''});setNotice('Budget template saved with lodge-validated account ownership.');await load()}catch(e2){setError(e2.message)}finally{setBusy('')}}
 const applyTemplate=async(e)=>{e.preventDefault();setBusy('apply');setError('');try{await runIdempotent(`budget-template-apply:${apply.templateId}:${year}:${apply.month}`,operationKey=>accountingInvoke('applyBudgetTemplate',{templateId:apply.templateId,year:Number(year),month:Number(apply.month),operationKey}));setNotice('Template applied atomically to the selected month.');await load()}catch(e2){setError(e2.message)}finally{setBusy('')}}
 return <AccountingPage title="Budgets" description="Maintain a complete monthly revenue and expense matrix. Every account is lodge-validated and each save is atomic and retry-safe." actions={<><AccountingExportButton fileName={`budget-${year}`} exportOperation="exportBudgets" exportArgs={[Number(year)]} onError={setError}/><input aria-label="Budget year" type="number" min="2000" max="2100" className={`${inputClass} w-28`} value={year} onChange={e=>setYear(Number(e.target.value))}/><AccountingButton tone="secondary" onClick={load}><RefreshCw size={15}/>Refresh</AccountingButton>{canManage&&<AccountingButton busy={busy==='save'} onClick={save}><Save size={15}/>Save matrix</AccountingButton>}{canManage&&data.version_id&&data.version_status==='draft'&&<AccountingButton tone="amber" busy={busy==='approve'} onClick={approve}><CheckCircle2 size={15}/>Approve version</AccountingButton>}</>}>
  <AccountingNotice>Only active revenue and expense accounts accept new budgets. Deactivating an account never removes historical statement activity. Version: {data.version_id ? `${data.version_status || 'draft'} · ${data.version_id}` : 'legacy/unversioned'}</AccountingNotice>{error&&<AccountingNotice type="error">{error}</AccountingNotice>}{notice&&<AccountingNotice type="success">{notice}</AccountingNotice>}
  {loading?<AccountingLoading/>:<div className="space-y-4">
   <AccountingPanel title={`${year} monthly matrix`}>{data.matrix.length===0?<EmptyState title="No active revenue or expense accounts" description="Configure the Chart of Accounts first."/>:<div className="overflow-x-auto"><table className="min-w-[1300px] w-full text-xs"><thead><tr className="border-b text-left text-slate-500"><th className="sticky left-0 bg-white py-2">Account</th>{months.map(m=><th key={m} className="text-right">{m}</th>)}<th className="text-right">Annual</th></tr></thead><tbody>{data.matrix.map(row=>{const total=months.reduce((sum,_,i)=>sum+Number(draft[`${row.account_id}:${i+1}`]||0),0);return <tr key={row.account_id} className="border-b border-slate-100"><td className="sticky left-0 bg-white py-2 pr-3"><b>{row.code}</b> — {row.name}</td>{months.map((_,i)=><td key={i} className="pl-2"><input disabled={!canManage} aria-label={`${row.name} ${months[i]}`} type="number" min="0" step="0.01" className="w-20 rounded border border-slate-200 px-2 py-1 text-right disabled:bg-slate-50" value={draft[`${row.account_id}:${i+1}`]??'0'} onChange={e=>setDraft({...draft,[`${row.account_id}:${i+1}`]:e.target.value})}/></td>)}<td className="text-right font-bold">{money(total)}</td></tr>})}</tbody></table></div>}</AccountingPanel>
   {canManage&&<div className="grid gap-4 xl:grid-cols-2"><AccountingPanel title="Create reusable template" description="Start with one default account line; additional templates can be created for other lines."><form className="space-y-3" onSubmit={createTemplate}><label className={labelClass}>Template name<input required className={inputClass} value={template.name} onChange={e=>setTemplate({...template,name:e.target.value})}/></label><label className={labelClass}>Description<input className={inputClass} value={template.description} onChange={e=>setTemplate({...template,description:e.target.value})}/></label><label className={labelClass}>Account<select required className={inputClass} value={template.accountId} onChange={e=>setTemplate({...template,accountId:e.target.value})}><option value="">Select</option>{data.matrix.map(a=><option key={a.account_id} value={a.account_id}>{a.code} — {a.name}</option>)}</select></label><label className={labelClass}>Monthly default<input required type="number" min="0" step="0.01" className={inputClass} value={template.defaultAmount} onChange={e=>setTemplate({...template,defaultAmount:e.target.value})}/></label><AccountingButton busy={busy==='template'}>Create template</AccountingButton></form></AccountingPanel><AccountingPanel title="Apply template to one month"><form className="space-y-3" onSubmit={applyTemplate}><label className={labelClass}>Template<select required className={inputClass} value={apply.templateId} onChange={e=>setApply({...apply,templateId:e.target.value})}><option value="">Select</option>{data.templates.map(t=><option key={t.id} value={t.id}>{t.name}</option>)}</select></label><label className={labelClass}>Month<select className={inputClass} value={apply.month} onChange={e=>setApply({...apply,month:Number(e.target.value)})}>{months.map((m,i)=><option key={m} value={i+1}>{m}</option>)}</select></label><AccountingButton busy={busy==='apply'}><Copy size={15}/>Apply atomically</AccountingButton></form></AccountingPanel></div>}
  </div>}
 </AccountingPage>
}

