import { useCallback, useEffect, useMemo, useState } from 'react'
import { Banknote, CheckCircle2, LogOut, RefreshCw, ShieldCheck, WalletCards } from 'lucide-react'
import { useAuth } from '../../app-context'
import { HposButton, HposNotice, HposPageHero } from './HposUi'
import { clearCashupSubmissionRound, getCashupSubmissionRound } from '../../utils/cashupSubmission'

export default function HposSharedCashup() {
  const { user } = useAuth()
  const [staff, setStaff] = useState([]); const [attendance, setAttendance] = useState([]); const [staffId, setStaffId] = useState(''); const [posShift, setPosShift] = useState(null); const [submission, setSubmission] = useState(null); const [cash, setCash] = useState(''); const [pin, setPin] = useState(''); const [loading, setLoading] = useState(true); const [resolvingShift, setResolvingShift] = useState(false); const [saving, setSaving] = useState(false); const [error, setError] = useState(''); const [notice, setNotice] = useState(''); const [submitted, setSubmitted] = useState(false)
  const refresh = useCallback(async () => { setLoading(true); try { const [members, shifts] = await Promise.all([window.api?.pos?.getStaff?.() || [], window.api?.pos?.getActiveShifts?.() || []]); setStaff((Array.isArray(members) ? members : []).filter((row) => !['suspended', 'inactive'].includes(String(row.status || 'active').toLowerCase()))); setAttendance(Array.isArray(shifts) ? shifts : []) } catch (e) { setError(e?.message || 'Could not load staff cash-up.') } finally { setLoading(false) } }, [])
  useEffect(() => { refresh() }, [refresh]); const member = useMemo(() => staff.find((row) => row.id === staffId), [staff, staffId]); const lodgeId = user?.lodge_id || ''; const managerActorId = user?.id || ''; const attendanceShift = attendance.find((row) => row.staff_user_id === staffId)
  useEffect(() => { let active = true; setPosShift(null); setSubmission(null); setSubmitted(false); setCash(''); setNotice(''); setResolvingShift(Boolean(staffId)); if (!staffId) return; (async () => { try { const shift = await window.api?.pos?.getStaffOpenShift?.(staffId); if (!active) return; setPosShift(shift || null); if (shift) { const existing = await window.api?.pos?.getStaffCashupSubmission?.(shift.id); if (active) { const existingSubmission = existing?.submission || null; setSubmission(existingSubmission); setSubmitted(['submitted', 'approved'].includes(existingSubmission?.status)); if (['submitted', 'approved'].includes(existingSubmission?.status)) clearCashupSubmissionRound({ lodgeId, shiftId: shift.id, actorId: managerActorId, submissionType: 'shared_terminal' }); setCash(String(existingSubmission?.counted_by_method?.cash ?? '')); if (existingSubmission?.status === 'rejected') setNotice(`Cash-up returned for correction. Manager note: ${existingSubmission.review_notes || 'No note was recorded.'}`) } } } catch (e) { if (active) setError(e?.message || 'Could not load this Till shift.') } finally { if (active) setResolvingShift(false) } })(); return () => { active = false } }, [lodgeId, managerActorId, staffId])
  const submit = async () => { if (!posShift?.id || !pin || cash === '') return; setSaving(true); setError(''); try { const submissionPayload = { shift_id: posShift.id, counted_by_method: { cash: Number(cash) }, actor_id: managerActorId || null, operator_id: staffId || null, submission_type: 'shared_terminal' }; const round = getCashupSubmissionRound({ lodgeId, shiftId: posShift.id, actorId: managerActorId, operatorId: staffId, submissionType: 'shared_terminal', payload: submissionPayload, serverStatus: submission?.status, serverIdempotencyKey: submission?.idempotency_key }); if (round.conflict || !round.durable || !round.round) throw new Error(round.error || 'The cash-up round was not durably saved. The server call was not sent.'); const replayPayload = round.round.payload || submissionPayload; const result = await window.api?.pos?.submitCashupWithAttendancePin?.({ ...replayPayload, pin, idempotency_key: round.round.idempotencyKey }); if (!result?.success) throw new Error(result?.error || 'Could not submit cash-up.'); clearCashupSubmissionRound({ lodgeId, shiftId: posShift.id, actorId: managerActorId, submissionType: 'shared_terminal' }); setSubmitted(true); setNotice('Cash-up submitted. The staff member can now clock out with their PIN; manager review happens later.') } catch (e) { setError(e?.message || 'Could not submit cash-up.') } finally { setSaving(false) } }
  const clockOut = async () => { if (!attendanceShift?.id || !pin) return; setSaving(true); setError(''); try { const result = await window.api?.pos?.clockOutStaffWithAttendancePin?.({ shiftId: attendanceShift.id, pin }); if (!result?.success) throw new Error(result?.error || 'Could not clock out.'); setNotice(`${member?.name || 'Staff member'} is clocked out. Their cash-up awaits manager review.`); setStaffId(''); setPin(''); setSubmitted(false); await refresh() } catch (e) { setError(e?.message || 'Could not clock out.') } finally { setSaving(false) } }
  return <div className="hpos-shared-cashup"><HposPageHero eyebrow="Shared terminal" title="Staff cash-up" description="The bartender, cashier or other till operator enters their own PIN and physical cash count. Expected totals stay hidden until manager review." actions={<HposButton icon={RefreshCw} onClick={refresh} disabled={loading || saving}>Refresh</HposButton>}/>{error && <HposNotice tone="error">{error}</HposNotice>}{notice && <HposNotice>{notice}</HposNotice>}<section className="hpos-attendance-card"><header><span><WalletCards size={24}/></span><div><p>Verified handover</p><h2>{member?.name || 'Choose staff member'}</h2></div></header><label><span>Staff member</span><select value={staffId} onChange={(e) => { setStaffId(e.target.value); setPin(''); setError('') }} disabled={loading || saving}><option value="">Choose staff member</option>{staff.map((row) => <option key={row.id} value={row.id}>{row.name || row.email}</option>)}</select></label>{staffId && resolvingShift && <HposNotice>Loading this person’s Till shift…</HposNotice>}{staffId && !resolvingShift && !posShift && <HposNotice tone="warning">This person has no open Till shift to cash up.</HposNotice>}{posShift && <><div className="hpos-my-cashup-figures"><article><small>Cash to count</small><strong>Enter from the drawer</strong></article></div><label><span><Banknote size={17}/> Physical cash counted</span><input type="number" min="0" step="0.01" value={cash} onChange={(e) => setCash(e.target.value)} disabled={saving || submitted}/><small>Cash tips kept from all-cash sales remain excluded from the handover. Expected totals and variances are intentionally withheld from the operator.</small></label></>}<label className="hpos-attendance-pin"><span><ShieldCheck size={17}/> Staff PIN</span><input type="password" inputMode="numeric" value={pin} onChange={(e) => setPin(e.target.value.replace(/\D/g, '').slice(0, 6))} placeholder="Operator enters PIN" disabled={!staffId || saving}/><small>The manager stays signed in. The operator’s PIN proves this handover.</small></label>{!submitted ? <HposButton tone="primary" icon={CheckCircle2} onClick={submit} disabled={!posShift || !pin || cash === '' || saving}>{saving ? 'Submitting…' : 'Submit cash-up'}</HposButton> : <HposButton tone="primary" icon={LogOut} onClick={clockOut} disabled={!attendanceShift || !pin || saving}>{saving ? 'Clocking out…' : 'Clock out staff'}</HposButton>}</section></div>
}
