import { useEffect, useState } from 'react'
import { Gift, HandCoins, PackageCheck, BellRing, RefreshCw } from 'lucide-react'

const today = () => new Date().toISOString().slice(0, 10)

export default function RestaurantGrowthControls({ tabKey = 'growth' }) {
  const [items, setItems] = useState([]); const [expiring, setExpiring] = useState([]); const [notice, setNotice] = useState(''); const [busy, setBusy] = useState(false)
  const [gift, setGift] = useState({ code: '', amount: '', expires_at: '' })
  const [payout, setPayout] = useState({ staff_name: '', amount: '', method: 'cash', business_date: today(), reference: '' })
  const [lot, setLot] = useState({ inventory_item_id: '', lot_code: '', received_quantity: '', unit_cost: '', expires_on: '' })
  const [policy, setPolicy] = useState({ cancellation_cutoff_hours: '24', no_show_forfeit_percent: '100', reminder_hours_before: '24' })
  async function load() { const [stock, expiry] = await Promise.all([window.api.inventory.getItems().catch(() => []), window.api.pos.getExpiryLots(14).catch(() => [])]); setItems(Array.isArray(stock) ? stock : []); setExpiring(Array.isArray(expiry) ? expiry : []) }
  useEffect(() => { load() }, [])
  async function submit(event, action, reset) { event.preventDefault(); setBusy(true); setNotice(''); try { const result = await action(); if (!result?.success) throw new Error(result?.error || 'Could not save'); reset?.(); setNotice('Saved securely.'); await load() } catch (error) { setNotice(error.message || 'Could not save') } finally { setBusy(false) } }
  const input = 'bb-input mt-1 w-full'
  const showGift = tabKey === 'growth', showTips = tabKey === 'tips', showLots = tabKey === 'lots', showPolicy = tabKey === 'growth'
  const title = showLots ? 'Lots & Expiry' : showTips ? 'Tips & Payouts' : 'Gift Cards & Reservation Policies'
  return <div className="mx-auto max-w-7xl p-6"><div className="mb-6 flex items-center justify-between"><div><h1 className="text-2xl font-bold text-slate-900">{title}</h1><p className="mt-1 text-sm text-slate-500">{showLots ? 'Register received stock lots and surface near-expiry items.' : showTips ? 'Record manager-approved tip-pool payouts.' : 'Issue stored-value gift cards and set cancellation/no-show rules.'}</p></div><button onClick={load} className="bb-btn-outline"><RefreshCw size={14}/></button></div>{notice && <div className="mb-4 rounded-lg border border-emerald-200 bg-emerald-50 p-3 text-sm text-emerald-800">{notice}</div>}<div className="grid gap-5 lg:grid-cols-2">
    {showGift &&
    <form className="bb-card p-5" onSubmit={e => submit(e, () => window.api.pos.createGiftCard(gift), () => setGift({ code:'',amount:'',expires_at:'' }))}><h2 className="flex items-center gap-2 font-bold"><Gift size={18}/> Gift card / digital voucher</h2><p className="mb-3 text-xs text-slate-500">Creates stored value; redemption remains through the POS voucher flow.</p><div className="grid grid-cols-2 gap-3"><label className="text-xs">Code<input required value={gift.code} onChange={e=>setGift({...gift,code:e.target.value.toUpperCase()})} className={input}/></label><label className="text-xs">Value<input required type="number" min="0.01" step="0.01" value={gift.amount} onChange={e=>setGift({...gift,amount:e.target.value})} className={input}/></label><label className="col-span-2 text-xs">Expiry (optional)<input type="date" value={gift.expires_at} onChange={e=>setGift({...gift,expires_at:e.target.value})} className={input}/></label></div><button disabled={busy} className="bb-btn-primary mt-4 w-full">Issue gift card</button></form>}
    {showTips && <form className="bb-card p-5" onSubmit={e => submit(e, () => window.api.pos.recordTipPayout(payout), () => setPayout({...payout,staff_name:'',amount:'',reference:''}))}><h2 className="flex items-center gap-2 font-bold"><HandCoins size={18}/> Tips pool payout</h2><p className="mb-3 text-xs text-slate-500">Records a manager-approved payout with a stable audit key.</p><div className="grid grid-cols-2 gap-3"><label className="text-xs">Staff member<input required value={payout.staff_name} onChange={e=>setPayout({...payout,staff_name:e.target.value})} className={input}/></label><label className="text-xs">Amount<input required type="number" min="0.01" step="0.01" value={payout.amount} onChange={e=>setPayout({...payout,amount:e.target.value})} className={input}/></label><label className="text-xs">Method<select value={payout.method} onChange={e=>setPayout({...payout,method:e.target.value})} className={input}>{['cash','bank','mobile_money'].map(x=><option key={x}>{x}</option>)}</select></label><label className="text-xs">Business date<input type="date" value={payout.business_date} onChange={e=>setPayout({...payout,business_date:e.target.value})} className={input}/></label></div><button disabled={busy} className="bb-btn-primary mt-4 w-full">Record tip payout</button></form>}
    {showLots && <form className="bb-card p-5" onSubmit={e => submit(e, () => window.api.pos.recordInventoryLot(lot), () => setLot({inventory_item_id:'',lot_code:'',received_quantity:'',unit_cost:'',expires_on:''}))}><h2 className="flex items-center gap-2 font-bold"><PackageCheck size={18}/> Stock expiry & batch lot</h2><p className="mb-3 text-xs text-slate-500">Register a received lot so managers can work oldest/nearest-expiry stock first.</p><div className="grid grid-cols-2 gap-3"><label className="col-span-2 text-xs">Inventory item<select required value={lot.inventory_item_id} onChange={e=>setLot({...lot,inventory_item_id:e.target.value})} className={input}><option value="">Choose item</option>{items.map(i=><option value={i.id} key={i.id}>{i.name}</option>)}</select></label><label className="text-xs">Lot / batch code<input required value={lot.lot_code} onChange={e=>setLot({...lot,lot_code:e.target.value})} className={input}/></label><label className="text-xs">Quantity<input required type="number" min="0.01" step="0.01" value={lot.received_quantity} onChange={e=>setLot({...lot,received_quantity:e.target.value})} className={input}/></label><label className="text-xs">Unit cost<input type="number" min="0" step="0.01" value={lot.unit_cost} onChange={e=>setLot({...lot,unit_cost:e.target.value})} className={input}/></label><label className="text-xs">Expiry<input type="date" value={lot.expires_on} onChange={e=>setLot({...lot,expires_on:e.target.value})} className={input}/></label></div><button disabled={busy} className="bb-btn-primary mt-4 w-full">Register lot</button><div className="mt-3 text-xs text-amber-700">{expiring.length ? `${expiring.length} lot(s) expire within 14 days.` : 'No near-expiry lots.'}</div></form>}
    {showPolicy && <form className="bb-card p-5" onSubmit={e => submit(e, () => window.api.pos.saveReservationPolicy(policy))}><h2 className="flex items-center gap-2 font-bold"><BellRing size={18}/> Reservation policy & reminders</h2><p className="mb-3 text-xs text-slate-500">Applies the cancellation/no-show terms used by managers and assisted WhatsApp reminders.</p><div className="grid grid-cols-3 gap-3"><label className="text-xs">Cutoff hours<input type="number" min="0" value={policy.cancellation_cutoff_hours} onChange={e=>setPolicy({...policy,cancellation_cutoff_hours:e.target.value})} className={input}/></label><label className="text-xs">No-show forfeit %<input type="number" min="0" max="100" value={policy.no_show_forfeit_percent} onChange={e=>setPolicy({...policy,no_show_forfeit_percent:e.target.value})} className={input}/></label><label className="text-xs">Reminder hours<input type="number" min="1" value={policy.reminder_hours_before} onChange={e=>setPolicy({...policy,reminder_hours_before:e.target.value})} className={input}/></label></div><button disabled={busy} className="bb-btn-primary mt-4 w-full">Save reservation policy</button></form>}
  </div></div>
}
