-- Derive held-tab line values from the persisted unit-price/quantity snapshot.
--
-- HposTerminal deliberately sends unit_price and quantity only when a check is
-- held.  Totals must be generated by PostgreSQL, never copied from a renderer
-- supplied line_total.  Invalid item shapes remain operationally readable but
-- are marked financially incomplete so the UI cannot present an unsafe value.

begin;

create or replace function public.derive_pos_tab_financial_snapshot(p_items jsonb)
returns jsonb
language plpgsql
immutable
security invoker
set search_path = pg_catalog, public
as $$
declare
  v_items jsonb := case
    when p_items is null or jsonb_typeof(p_items) = 'null' then '[]'::jsonb
    else p_items
  end;
  v_normalized jsonb := '[]'::jsonb;
  v_item jsonb;
  v_quantity_text text;
  v_unit_price_text text;
  v_quantity numeric;
  v_unit_price numeric;
  v_line_amount numeric;
  v_subtotal numeric := 0;
  v_complete boolean := false;
begin
  -- An empty or non-array item set is a valid operational payload, but it is
  -- not a bill with a certifiable financial value.
  if jsonb_typeof(v_items) <> 'array' or jsonb_array_length(v_items) = 0 then
    return jsonb_build_object(
      'items', v_items,
      'subtotal', null,
      'discount_total', null,
      'tax_total', null,
      'tip_total', null,
      'total', null,
      'financial_complete', false
    );
  end if;

  v_complete := true;
  for v_item in select value from jsonb_array_elements(v_items) loop
    -- Keep the guard strict and bounded before casting user-controlled text to
    -- numeric.  This rejects malformed values, NaN-like text, and oversized
    -- values without allowing a cast exception to abort the tab read.
    if jsonb_typeof(v_item) <> 'object'
      or (v_item ? 'modifiers' and jsonb_typeof(v_item->'modifiers') not in ('array', 'null')) then
      v_complete := false;
      continue;
    end if;

    v_quantity_text := nullif(btrim(v_item->>'quantity'), '');
    v_unit_price_text := nullif(btrim(v_item->>'unit_price'), '');
    if v_quantity_text is null
      or v_unit_price_text is null
      or length(v_quantity_text) > 30
      or length(v_unit_price_text) > 30
      or v_quantity_text !~ '^[0-9]+([.][0-9]+)?$'
      or v_unit_price_text !~ '^[0-9]+([.][0-9]+)?$' then
      v_complete := false;
      continue;
    end if;

    v_quantity := v_quantity_text::numeric;
    v_unit_price := v_unit_price_text::numeric;
    if v_quantity <= 0 or v_unit_price < 0 then
      v_complete := false;
      continue;
    end if;

    v_line_amount := round(v_unit_price * v_quantity, 2);
    v_subtotal := v_subtotal + v_line_amount;
    -- Existing split rows already carry line fields; overwriting them with
    -- this server-derived value preserves that contract without trusting the
    -- fields supplied by a renderer.
    v_normalized := v_normalized || jsonb_build_array(
      v_item || jsonb_build_object(
        'line_subtotal', v_line_amount,
        'line_total', v_line_amount
      )
    );
  end loop;

  if not v_complete then
    return jsonb_build_object(
      'items', v_items,
      'subtotal', null,
      'discount_total', null,
      'tax_total', null,
      'tip_total', null,
      'total', null,
      'financial_complete', false
    );
  end if;

  return jsonb_build_object(
    'items', v_normalized,
    'subtotal', round(v_subtotal, 2),
    'discount_total', 0,
    'tax_total', 0,
    'tip_total', 0,
    'total', round(v_subtotal, 2),
    'financial_complete', true
  );
end;
$$;

revoke all on function public.derive_pos_tab_financial_snapshot(jsonb)
  from public, anon, authenticated, service_role;
grant execute on function public.derive_pos_tab_financial_snapshot(jsonb)
  to service_role;

-- The wrapper in 20260814010000 remains the authorization boundary.  This
-- service-role-only implementation derives each row at read time, so active
-- rows created before this migration become usable immediately without a
-- blind data rewrite or a client-authored financial backfill.
create or replace function public.get_restaurant_pos_tabs_financial_truth_unscoped(
  p_lodge_id uuid,
  p_outlet_id uuid default null,
  p_status text default null
)
returns jsonb
language plpgsql
security definer
set search_path = public
as $$
declare
  v_rows jsonb;
  v_financial_complete boolean;
begin
  if p_lodge_id is null or not public.app_lodge_access(p_lodge_id) then
    raise exception 'Access denied' using errcode = '42501';
  end if;
  if p_outlet_id is not null then
    perform public.app_require_pos_outlet_access(p_lodge_id, p_outlet_id);
  end if;

  select coalesce(jsonb_agg(x.row_json order by x.updated_at desc, x.id), '[]'::jsonb)
    into v_rows
    from (
      select
        to_jsonb(t) || jsonb_build_object(
          'items', s.items,
          'financial_snapshot', s.financial_snapshot,
          'subtotal', s.subtotal,
          'discount_total', s.discount_total,
          'tax_total', s.tax_total,
          'tip_total', s.tip_total,
          'total', s.total,
          'financial_complete', s.financial_complete,
          'version', t.tab_version,
          'adjustment_total', s.total - s.subtotal
        ) as row_json,
        t.updated_at,
        t.id,
        s.subtotal,
        s.financial_complete
      from public.pos_tabs t
      left join lateral (
        select
          d->'items' as items,
          (d->>'subtotal')::numeric as subtotal,
          coalesce((d->>'financial_complete')::boolean, false) as financial_complete,
          jsonb_build_object(
            'subtotal', d->'subtotal',
            'discount_total', d->'discount_total',
            'tax_total', d->'tax_total',
            'tip_total', d->'tip_total',
            'total', d->'total',
            'financial_complete', d->'financial_complete',
            'calculated_at', coalesce(t.financial_snapshot->'calculated_at', to_jsonb(now()))
          ) as financial_snapshot,
          (d->>'discount_total')::numeric as discount_total,
          (d->>'tax_total')::numeric as tax_total,
          (d->>'tip_total')::numeric as tip_total,
          (d->>'total')::numeric as total
        from public.derive_pos_tab_financial_snapshot(coalesce(t.items, '[]'::jsonb)) d
      ) s on true
      where t.lodge_id = p_lodge_id
        and (p_outlet_id is null or t.outlet_id = p_outlet_id)
        and (
          nullif(btrim(p_status), '') is null
          or (lower(p_status) = 'active' and t.status in ('open', 'running', 'ready', 'delivered'))
          or (lower(p_status) <> 'active' and t.status = lower(p_status))
        )
    ) x;

  select coalesce(
    (select bool_and(coalesce((row->>'financial_complete')::boolean, false))
       from jsonb_array_elements(v_rows) row),
    true
  ) into v_financial_complete;

  return jsonb_build_object(
    'success', true,
    'data', v_rows,
    'source', 'server-authoritative-pos-tab-rpc',
    'complete', true,
    'financial_complete', v_financial_complete
  );
end;
$$;

-- Preserve the existing tab authorization, optimistic version check, table
-- occupancy check, and audit trail while persisting server-derived line fields
-- for newly held/resumed tabs.
create or replace function public.upsert_pos_tab(payload jsonb)
returns jsonb
language plpgsql
security definer
set search_path = public
as $$
declare
  v_id uuid := coalesce(nullif(payload->>'id', '')::uuid, gen_random_uuid());
  v_lodge uuid := nullif(payload->>'lodge_id', '')::uuid;
  v_outlet uuid := nullif(payload->>'outlet_id', '')::uuid;
  v_table text := nullif(btrim(coalesce(payload->>'table_name', '')), '');
  v_waiter_name text := nullif(btrim(coalesce(payload->>'waiter_name', '')), '');
  v_waiter_id uuid := nullif(payload->>'waiter_id', '')::uuid;
  v_shift_id uuid := nullif(payload->>'shift_id', '')::uuid;
  v_status text := lower(coalesce(nullif(payload->>'status', ''), case when v_table is null then 'open' else 'running' end));
  v_expected integer := nullif(payload->>'expected_version', '')::integer;
  v_existing public.pos_tabs%rowtype;
  v_row public.pos_tabs%rowtype;
  v_financial jsonb;
  v_items jsonb;
  v_snapshot jsonb;
begin
  if v_lodge is null or not public.app_lodge_access(v_lodge) then
    return jsonb_build_object('success', false, 'error', 'Access denied.');
  end if;
  perform public.app_require_pos_outlet_access(v_lodge, v_outlet);
  if v_status not in ('open', 'running', 'ready', 'delivered', 'closed', 'cancelled') then
    v_status := case when v_table is null then 'open' else 'running' end;
  end if;
  if v_status in ('open', 'running', 'ready', 'delivered')
    and (v_waiter_id is null or v_waiter_name is null or v_shift_id is null) then
    return jsonb_build_object('success', false, 'error', 'Unlock Till with the serving staff PIN and start their shift before holding an open check.');
  end if;
  if v_status in ('open', 'running', 'ready', 'delivered')
    and not exists (
      select 1 from public.pos_shifts s
      where s.id = v_shift_id
        and s.lodge_id = v_lodge
        and s.outlet_id is not distinct from v_outlet
        and s.cashier_id = v_waiter_id
        and s.status = 'open'
        and s.closed_at is null
    ) then
    return jsonb_build_object('success', false, 'error', 'The selected staff member does not have an active Till shift for this outlet.');
  end if;

  select * into v_existing
    from public.pos_tabs
    where id = v_id and lodge_id = v_lodge
    for update;
  if found and v_expected is not null and v_existing.tab_version <> v_expected then
    return jsonb_build_object(
      'success', false,
      'code', 'tab_version_conflict',
      'error', 'This tab changed on another terminal. Refresh it before saving.',
      'tab', to_jsonb(v_existing)
    );
  end if;
  if v_table is not null
    and v_status in ('open', 'running', 'ready', 'delivered')
    and exists (
      select 1 from public.pos_tabs t
      where t.lodge_id = v_lodge
        and t.outlet_id is not distinct from v_outlet
        and lower(btrim(t.table_name)) = lower(v_table)
        and t.status in ('open', 'running', 'ready', 'delivered')
        and t.id <> v_id
    ) then
    select * into v_existing
      from public.pos_tabs t
      where t.lodge_id = v_lodge
        and t.outlet_id is not distinct from v_outlet
        and lower(btrim(t.table_name)) = lower(v_table)
        and t.status in ('open', 'running', 'ready', 'delivered')
        and t.id <> v_id
      order by t.updated_at desc
      limit 1;
    return jsonb_build_object('success', true, 'already_open', true, 'tab', to_jsonb(v_existing));
  end if;

  v_financial := public.derive_pos_tab_financial_snapshot(coalesce(payload->'items', '[]'::jsonb));
  v_items := v_financial->'items';
  v_snapshot := (v_financial - 'items') || jsonb_build_object('calculated_at', now());

  insert into public.pos_tabs(
    id, lodge_id, outlet_id, table_name, tab_name, customer_name, waiter_name,
    waiter_id, shift_id, room_id, booking_id, items, notes, status, opened_by,
    opened_by_name, created_at, updated_at, closed_at, tab_version,
    financial_snapshot
  ) values (
    v_id, v_lodge, v_outlet, v_table,
    nullif(btrim(coalesce(payload->>'tab_name', '')), ''),
    nullif(btrim(coalesce(payload->>'customer_name', '')), ''),
    v_waiter_name, v_waiter_id, v_shift_id,
    nullif(payload->>'room_id', '')::uuid,
    nullif(payload->>'booking_id', '')::uuid,
    v_items,
    nullif(payload->>'notes', ''),
    v_status,
    coalesce(nullif(payload->>'opened_by', '')::uuid, public.app_current_user_id()),
    nullif(payload->>'opened_by_name', ''),
    coalesce(nullif(payload->>'created_at', '')::timestamptz, now()),
    now(),
    case when v_status in ('closed', 'cancelled') then now() else null end,
    1,
    v_snapshot
  )
  on conflict (id) do update set
    outlet_id = excluded.outlet_id,
    table_name = excluded.table_name,
    tab_name = excluded.tab_name,
    customer_name = excluded.customer_name,
    waiter_name = excluded.waiter_name,
    waiter_id = excluded.waiter_id,
    shift_id = excluded.shift_id,
    room_id = excluded.room_id,
    booking_id = excluded.booking_id,
    items = excluded.items,
    notes = excluded.notes,
    status = excluded.status,
    updated_at = now(),
    closed_at = excluded.closed_at,
    tab_version = public.pos_tabs.tab_version + 1,
    financial_snapshot = excluded.financial_snapshot
  returning * into v_row;

  insert into public.pos_audit_log(
    lodge_id, outlet_id, actor_id, action, entity_type, entity_id, after_snapshot
  ) values (
    v_lodge, v_outlet, public.app_current_user_id(), 'tab_saved', 'pos_tab',
    v_row.id, to_jsonb(v_row)
  );
  return jsonb_build_object('success', true, 'tab', to_jsonb(v_row));
end;
$$;

revoke all on function public.get_restaurant_pos_tabs_financial_truth_unscoped(uuid, uuid, text)
  from public, anon, authenticated;
grant execute on function public.get_restaurant_pos_tabs_financial_truth_unscoped(uuid, uuid, text)
  to service_role;
revoke all on function public.upsert_pos_tab(jsonb)
  from public, anon, authenticated;
grant execute on function public.upsert_pos_tab(jsonb)
  to anon, authenticated, service_role;

notify pgrst, 'reload schema';
commit;
